(()=>{'use strict';
const p=()=>window.STIPSession?.permissions||window.STIPBootCache?.permissions||{},depth=k=>window.STIPSession?.depths?.[k]||window.STIPBootCache?.depths?.[k]||'none';
function explicit(k){const x=p();return Object.prototype.hasOwnProperty.call(x,k)?!!x[k]:false}
const APP_POLICY={personal:()=>explicit('planning_personal'),team:()=>explicit('planning_team'),compare:()=>explicit('planning_team'),change:()=>explicit('change_app'),calendar:()=>explicit('calendar_subscribe'),contacts:()=>explicit('contacts'),responsable:()=>explicit('responsable'),notes:()=>explicit('notes')&&infoLevel('notes')==='pro',newagent:()=>explicit('nouveaux_arrivants'),upload:()=>explicit('file_upload'),activity:()=>explicit('activity'),admin:()=>explicit('admin'),places:()=>explicit('places'),assistant:()=>explicit('assistant_enabled'),access:()=>explicit('access_manage')||explicit('admin'),profile_photo:()=>explicit('profile_photo')};
function canApp(k){return APP_POLICY[k]?.()??false}
function normalizeInfoLevel(v){v=String(v||'').toLowerCase();if(v==='pro'||v==='internal'||v==='internal_stip'||v==='restricted'||v==='admin')return'pro';if(v==='visitor'||v==='visiteur'||v==='public'||v==='basic')return'visitor';return'none'}
function infoLevel(app=''){const lv=p().__levels?.[app];if(lv)return normalizeInfoLevel(lv);const n=normalizeInfoLevel(depth(app));return n!=='none'?n:'visitor'}
function canInfo(level='visitor',app=''){if(app&&!explicit(app))return false;const wanted=normalizeInfoLevel(level),current=infoLevel(app);return wanted==='visitor'?(current==='visitor'||current==='pro'):wanted==='pro'&&current==='pro'}
function applyInfoPolicy(root=document){for(const el of root.querySelectorAll('[data-stip-info],[data-access-level]')){const wanted=el.dataset.stipInfo||el.dataset.accessLevel||'visitor',app=el.dataset.stipApp||el.closest('[data-stip-app]')?.dataset.stipApp||'';el.hidden=!canInfo(wanted,app)}}
function guardRoute(){const r=window.STIPRouter?.get?.()||'';let ok=true;if(r==='planning/personal')ok=canApp('personal');else if(r==='planning/calendar')ok=canApp('calendar');else if(r==='planning/team'||r==='planning/spirit')ok=canApp('team');else if(r==='planning/change')ok=canApp('change');else if(r.startsWith('contacts'))ok=canApp('contacts');if(!ok)window.STIPRouter?.set?.('home',{replace:true})}
function guardStandalone(){const path=location.pathname.toLowerCase();const checks=[['/responsable.html','responsable'],['/assistant.html','assistant'],['/cadre-activite.html','activity'],['/planning-compare-app.html','compare'],['/places.html','places'],['/places-app.html','places'],['/access-manage.html','access']];for(const [needle,key] of checks){if(path.endsWith(needle)&&!canApp(key)){location.replace('./');return false}}return true}
const ICON={personal:'<svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="16" rx="3"/><path d="M8 3v4M16 3v4M3 10h18"/></svg>',team:'<svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"/><path d="M3 20c0-4 2.4-7 6-7s6 3 6 7M16 6.5a2.5 2.5 0 0 1 0 5M17 14c2.5.6 4 2.7 4 5"/></svg>',compare:'<svg viewBox="0 0 24 24"><path d="M4 7h13l-3-3M20 17H7l3 3"/><path d="M17 7l-3 3M7 17l3-3"/></svg>',change:'<svg viewBox="0 0 24 24"><path d="M7 7h11l-3-3M17 17H6l3 3"/></svg>',calendar:'<svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="16" rx="3"/><path d="M8 3v4M16 3v4M3 10h18"/></svg>',contacts:'<svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"/><path d="M3 20c0-4 2.4-7 6-7s6 3 6 7M16 6.5a2.5 2.5 0 0 1 0 5M17 14c2.5.6 4 2.7 4 5"/></svg>',responsable:'<svg viewBox="0 0 24 24"><path d="M12 3 4 7v5c0 5 3.4 8 8 9 4.6-1 8-4 8-9V7z"/><path d="m9 12 2 2 4-4"/></svg>',notes:'<svg viewBox="0 0 24 24"><path d="M4 20h4l11-11-4-4L4 16v4Z"/><path d="m13.5 6.5 4 4M4 20l4-1"/></svg>',newagent:'<svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"/><path d="M3 20c0-4 2.4-7 6-7s6 3 6 7M18 8v6M15 11h6"/></svg>',upload:'<svg viewBox="0 0 24 24"><path d="M12 3v12M7 8l5-5 5 5"/><path d="M5 14v5h14v-5"/></svg>',activity:'<svg viewBox="0 0 24 24"><path d="M4 16l4-5 4 3 5-7 3 2"/><path d="M4 20h16"/></svg>',admin:'<svg viewBox="0 0 24 24"><path d="M12 3 4 7v10l8 4 8-4V7z"/><path d="M9 12h6M12 9v6"/></svg>',places:'<img src="images/icone_app/visiter-les-lieux.webp?v=20260831-icons3" alt="" aria-hidden="true">',assistant:'🦜',access:'🔐'};
const SPECS=[['personal','Planning perso','personal'],['team','Planning équipe','team'],['compare','Comparer les plannings','compare'],['change','Changement','change'],['calendar','Mon agenda','calendar'],['contacts','Contacts','contacts'],['responsable','Responsable','responsable'],['notes','Prendre des notes','notes'],['newagent','Nouvel agent','newagent'],['upload','Importer','upload'],['activity','Activité','activity'],['admin','Admin','admin'],['places','Visiter les lieux','places'],['assistant','Assistant STIP','assistant'],['access','Accès','access']];
function openApp(k,e){e?.preventDefault?.();e?.stopPropagation?.();if(!canApp(k))return;if(k==='personal')return location.href='index.html?quick=personal';if(k==='team')return location.href='index.html?quick=team';if(k==='compare')return location.href='planning-compare-app.html';if(k==='change')return location.href='index.html?quick=change';if(k==='calendar')return location.href='index.html?quick=calendar';if(k==='contacts')return location.href='index.html?quick=contacts';if(k==='responsable')return location.href='responsable.html';if(k==='notes')return location.href='https://sites.google.com/view/hfme-notes/notes-rapides';if(k==='newagent')return location.href='https://esapin69.github.io/Ghe-interne/';if(k==='upload')return location.href='https://admin-ghe.esapin.com/depot.html';if(k==='activity')return location.href='cadre-activite.html';if(k==='admin')return location.href='https://admin-ghe.esapin.com/';if(k==='places')return location.href=`places-app.html?mode=${infoLevel('places')==='pro'?'pro':'visitor'}`;if(k==='assistant')return location.href='assistant.html';if(k==='access')return location.href='access-manage.html'}
function dedupe(box){const seen=new Set();for(const b of [...box.querySelectorAll('.hc-app[data-app]')]){const k=b.dataset.app;if(!k)continue;if(seen.has(k)){b.remove();continue}seen.add(k)}}
function ensureCard(box,key,title,cls){let b=box.querySelector(`[data-app="${key}"]`);if(!canApp(key)){box.querySelectorAll(`[data-app="${key}"]`).forEach(x=>x.remove());return null}if(!b){b=document.createElement('button');b.type='button';b.className=`hc-app ${cls}`;b.dataset.app=key;b.innerHTML=`<span>${ICON[key]||''}</span><strong>${title}</strong>`}b.style.display='';b.onclick=e=>openApp(key,e);return b}
function applyHomePolicy(){const box=document.querySelector('#homeView .hc-apps');if(!box)return;box.querySelectorAll('[data-app="equipe"]').forEach(b=>b.remove());dedupe(box);for(const b of [...box.querySelectorAll('[data-app]')]){const k=b.dataset.app;if(k in APP_POLICY&&!canApp(k))b.remove()}const wanted=[];for(const [key,title,cls] of SPECS){const b=ensureCard(box,key,title,cls);if(b)wanted.push(b)}dedupe(box);const current=[...box.querySelectorAll('.hc-app')];const stable=wanted.length===current.length&&wanted.every((b,i)=>current[i]===b);if(!stable){const frag=document.createDocumentFragment();wanted.forEach(b=>frag.appendChild(b));box.replaceChildren(frag)}const empty=box.querySelector('.hc-empty');if(empty&&wanted.length)empty.remove();if(!wanted.length&&!box.querySelector('.hc-empty'))box.innerHTML='<p class="hc-empty">Aucune application autorisée.</p>'}
function tuneDock(){for(const b of document.querySelectorAll('#stipContextDock [data-root-action]')){const a=b.dataset.rootAction;let ok=true;if(a==='calendar'||a==='personalcal')ok=canApp('calendar');if(a==='teamcal')ok=canApp('team')&&explicit('calendar_subscribe');if(a==='contact-share')ok=canApp('contacts');b.style.display=ok?'':'none'}}
function run(){if(!guardStandalone())return;guardRoute();applyHomePolicy();tuneDock();applyInfoPolicy();document.documentElement.dataset.stipInfoLevel=infoLevel()}
let raf=0;function schedule(){if(raf)return;raf=requestAnimationFrame(()=>{raf=0;run()})}['stip:session-ready','stip:boot-updated','stip:route','stip:lazy-ready','stip:home-rendered'].forEach(e=>window.addEventListener(e,schedule));window.addEventListener('pageshow',schedule);window.STIPAccess={has:k=>explicit(k),allow:k=>explicit(k),app:canApp,depth:k=>depth(k),can:k=>explicit(k),infoLevel,canInfo,applyInfoPolicy,open:openApp};schedule()})();