(()=>{'use strict';
const API='https://yzsrmuxghlengnkyphxj.supabase.co/functions/v1/stip-agent-dates',ACCESS='https://yzsrmuxghlengnkyphxj.supabase.co/functions/v1/stip-access',STORE='stip_session_v1',$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let items=[],active='all',selected='',query='',focus='';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function post(url,action,body={}){const r=await fetch(url,{method:'POST',cache:'no-store',headers:{'content-type':'application/json','x-stip-session':localStorage.getItem(STORE)||''},body:JSON.stringify({action,...body})}),j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw Error(j.error||('Erreur '+r.status));return j}
function dobj(v){return new Date(String(v).slice(0,10)+'T12:00:00')}
function iso(x){const z=new Date(x);z.setMinutes(z.getMinutes()-z.getTimezoneOffset());return z.toISOString().slice(0,10)}
function today(){return iso(new Date())}
function monday(){const x=dobj(today()),n=x.getDay()||7;x.setDate(x.getDate()-(n-1));return x}
function label(k){return({medical:'Visite médicale',intern:'Stagiaire',training:'Formation'})[k]||'Événement'}
function icon(k){return({medical:'🩺',intern:'👶',training:'🎓'})[k]||'📌'}
function filtered(){let a=active==='all'?items:items.filter(x=>x.category===active);if(selected)a=a.filter(x=>x.date===selected);if(query){const q=query.toLocaleLowerCase('fr-FR');a=a.filter(x=>[x.person_name,x.title,x.location,x.time,x.meta?.referent,label(x.category)].join(' ').toLocaleLowerCase('fr-FR').includes(q))}return a}
function counts(){const src=active==='all'?items:items.filter(x=>x.category===active),m=today().slice(0,7),start=monday(),end=new Date(start);end.setDate(end.getDate()+6);$('#daUpcoming').textContent=src.length+' à venir';$('#daWeekCount').textContent=src.filter(x=>{const y=dobj(x.date);return y>=start&&y<=end}).length;$('#daMonthCount').textContent=src.filter(x=>String(x.date).slice(0,7)===m).length}
function renderWeek(){const m=monday(),html=[];for(let i=0;i<7;i++){const x=new Date(m);x.setDate(m.getDate()+i);const di=iso(x),n=(active==='all'?items:items.filter(z=>z.category===active)).filter(z=>z.date===di).length;html.push('<button class="da-day '+(di===today()?'today ':'')+(selected===di?'selected ':'')+(n?'has':'')+'" data-day="'+di+'"><small>'+esc(x.toLocaleDateString('fr-FR',{weekday:'short'}).replace('.',''))+'</small><b>'+x.getDate()+'</b><em>'+n+'</em></button>')}$('#daWeek').innerHTML=html.join('');$$('[data-day]').forEach(b=>b.onclick=()=>{selected=selected===b.dataset.day?'':b.dataset.day;render()})}
function renderList(){const a=filtered(),g=new Map();a.forEach(x=>{const k=String(x.date).slice(0,7);if(!g.has(k))g.set(k,[]);g.get(k).push(x)});if(!a.length){$('#daList').innerHTML='<div class="da-empty">Aucune date à afficher avec ce filtre.</div>';return}let out='';for(const v of g.values()){out+='<section class="da-month"><h2>'+esc(dobj(v[0].date).toLocaleDateString('fr-FR',{month:'long',year:'numeric'}))+'</h2><div>';for(const x of v){const sourceFocus=focus?focus.split(':').pop():'',foc=!!focus&&(x.id===focus||x.source_id===sourceFocus),sub=x.category==='intern'&&x.meta?.referent?'Référent : '+x.meta.referent:(x.location||x.title||'');out+='<button class="da-item '+(foc?'focus':'')+'" data-id="'+esc(x.id)+'"><span class="da-date"><small>'+esc(dobj(x.date).toLocaleDateString('fr-FR',{weekday:'short'}).replace('.',''))+'</small><b>'+String(dobj(x.date).getDate()).padStart(2,'0')+'</b><em>'+esc(dobj(x.date).toLocaleDateString('fr-FR',{month:'short'}).replace('.',''))+'</em></span><span class="da-icon '+esc(x.category)+'">'+icon(x.category)+'</span><span class="da-copy"><span class="da-top"><strong>'+esc(x.person_name)+'</strong><span class="da-tag '+esc(x.category)+'">'+esc(label(x.category))+'</span></span><p>'+esc(x.time||x.title||'')+'</p>'+(sub?'<small>'+esc(sub)+'</small>':'')+'</span><span class="da-chev">›</span></button>'}out+='</div></section>'}$('#daList').innerHTML=out;$$('[data-id]').forEach(b=>b.onclick=()=>openDetail(b.dataset.id));if(focus)requestAnimationFrame(()=>document.querySelector('.da-item.focus')?.scrollIntoView({behavior:'smooth',block:'center'}))}
function render(){counts();renderWeek();renderList();$$('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===active))}
function openDetail(id){const x=items.find(v=>v.id===id);if(!x)return;$('#daDetailType').textContent=label(x.category).toUpperCase();$('#daDetailName').textContent=x.person_name;let rows='<dt>Date</dt><dd>'+esc(dobj(x.date).toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long',year:'numeric'}))+(x.end_date&&x.end_date!==x.date?' → '+esc(dobj(x.end_date).toLocaleDateString('fr-FR',{day:'numeric',month:'long'})):'')+'</dd><dt>Type</dt><dd>'+esc(label(x.category))+'</dd><dt>Intitulé</dt><dd>'+esc(x.title||label(x.category))+'</dd>';if(x.time)rows+='<dt>Horaire</dt><dd>'+esc(x.time)+'</dd>';if(x.location)rows+='<dt>Lieu</dt><dd>'+esc(x.location)+'</dd>';if(x.meta?.referent)rows+='<dt>Référent</dt><dd>'+esc(x.meta.referent)+'</dd>';if(x.detail)rows+='<dt>Information</dt><dd>'+esc(x.detail)+'</dd>';$('#daDetailBody').innerHTML='<div class="da-detail"><dl>'+rows+'</dl></div>';$('#daSheet').classList.add('open');$('#daSheet').setAttribute('aria-hidden','false')}
function closeSheet(){const s=$('#daSheet');s.classList.remove('open');s.setAttribute('aria-hidden','true')}
async function load(){try{const r=await post(API,'list');items=r.items||[];render()}catch(e){$('#daList').innerHTML='<div class="da-empty">'+esc(e.message)+'</div>'}}
async function init(){if(!localStorage.getItem(STORE)){location.replace('index.html');return}try{const me=await post(ACCESS,'me');if(!me.permissions?.agent_dates){location.replace('index.html');return}}catch{location.replace('index.html');return}const p=new URLSearchParams(location.search),f=p.get('filter');if(['all','medical','intern','training'].includes(f))active=f;focus=p.get('focus')||'';$('#daBack').onclick=()=>history.length>1?history.back():location.replace('index.html');$('#daSearchBtn').onclick=()=>{const w=$('#daSearchWrap');w.hidden=!w.hidden;if(!w.hidden)setTimeout(()=>$('#daSearch').focus(),10)};$('#daSearch').oninput=e=>{query=e.target.value.trim();renderList()};$('#daClear').onclick=()=>{$('#daSearch').value='';query='';renderList()};$$('[data-filter]').forEach(b=>b.onclick=()=>{active=b.dataset.filter;selected='';focus='';render()});$('#daSheetClose').onclick=closeSheet;$('#daSheet').onclick=e=>{if(e.target.id==='daSheet')closeSheet()};load()}
init();})();