(() => {
'use strict';
const ACCESS_API='https://yzsrmuxghlengnkyphxj.supabase.co/functions/v1/stip-access',STORAGE='stip_session_v1',$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const loginView=$('#loginView'),appView=$('#appView'),loginForm=$('#loginForm'),accessCode=$('#accessCode'),loginMessage=$('#loginMessage'),logoutBtn=$('#logoutBtn'),welcomeText=$('#welcomeText'),moduleGrid=$('#moduleGrid'),emptyPermissions=$('#emptyPermissions');let session=null;
const modules=[{key:'planning',title:'Planning',route:'planning'},{key:'equipe_contacts',title:'Contacts',route:'contacts'},{key:'responsable',title:'Responsable',href:'responsable.html'},{key:'nouveaux_arrivants',title:'Nouvel agent',href:'https://esapin69.github.io/Ghe-interne/'},{key:'admin',title:'Admin',href:'https://admin-ghe.esapin.com/'}];
function token(){return localStorage.getItem(STORAGE)||''}function route(){return location.hash.replace(/^#\/?/,'')||'home'}function setRoute(next){const t='#/'+(next||'home');if(location.hash===t)restore();else location.hash=t}function showOnly(id){$$('.view').forEach(v=>v.classList.add('hidden'));document.getElementById(id)?.classList.remove('hidden');window.scrollTo({top:0,behavior:'auto'})}function msg(t='',kind=''){loginMessage.textContent=t;loginMessage.className=`message ${kind}`.trim()}
async function access(action,body={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),10000);try{const h={'Content-Type':'application/json'};if(token())h['X-STIP-Session']=token();const r=await fetch(ACCESS_API,{method:'POST',headers:h,body:JSON.stringify({action,...body}),signal:c.signal}),j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw Error(j.error||`Erreur ${r.status}`);return j}finally{clearTimeout(t)}}
function personName(a){return window.STIPName?.format?.(a)||String(a?.prenom||a?.nom||'Agent').trim()}
function showLogin(text=''){window.STIPSession=null;window.dispatchEvent(new CustomEvent('stip:session-ended'));appView.classList.add('hidden');loginView.classList.remove('hidden');msg(text,text?'error':'');setTimeout(()=>accessCode?.focus(),40)}
function restore(){if(!session)return;const r=route();if(r==='home'){showOnly('homeView');return}if(r==='planning'||r.startsWith('planning/')){showOnly('planningView');if(r!=='planning')history.replaceState(null,'',location.pathname+location.search+'#/planning');window.dispatchEvent(new HashChangeEvent('hashchange'));return}if(r==='contacts'){window.STIPHubs?.contacts?.();return}setRoute('home')}
function renderSession(d){session=d;window.STIPSession=d;loginView.classList.add('hidden');appView.classList.remove('hidden');welcomeText.textContent=personName(d.agent||{});moduleGrid.innerHTML='';const allowed=modules.filter(m=>d.permissions?.[m.key]);emptyPermissions.classList.toggle('hidden',allowed.length>0);for(const m of allowed){const b=document.createElement('button');b.className='module-card';b.innerHTML=`<strong>${m.title}</strong>`;b.onclick=()=>m.href?location.href=m.href:setRoute(m.route);moduleGrid.appendChild(b)}window.dispatchEvent(new CustomEvent('stip:session-ready',{detail:d}));restore()}
loginForm?.addEventListener('submit',async e=>{e.preventDefault();const code=String(accessCode.value||'').replace(/\D/g,'').slice(0,6);if(code.length!==6){msg('Entre les 6 chiffres.','error');return}const submit=loginForm.querySelector('button[type="submit"]');if(submit)submit.disabled=true;msg('Connexion…');try{const d=await access('login',{code});localStorage.setItem(STORAGE,d.session_token);renderSession(d);msg('')}catch(err){msg(err.message||'Connexion impossible.','error')}finally{if(submit)submit.disabled=false}});
logoutBtn?.addEventListener('click',async()=>{try{await access('logout')}catch{}localStorage.removeItem(STORAGE);session=null;history.replaceState(null,'',location.pathname+location.search+'#/home');showLogin()});$('#homeBtn')?.addEventListener('click',()=>setRoute('home'));window.addEventListener('hashchange',restore);window.STIPRouter={set:setRoute,restore,show:showOnly,get:route};if(!location.hash)history.replaceState(null,'',location.pathname+location.search+'#/home');
(async()=>{if(!token()){showLogin();return}try{renderSession(await access('me'))}catch{localStorage.removeItem(STORAGE);showLogin('Reconnecte-toi.')}})();
})();