(() => {
'use strict';
const ACCESS_API='https://yzsrmuxghlengnkyphxj.supabase.co/functions/v1/stip-access',STORAGE='stip_session_v1',SCROLL_STORE='stip_scroll_v2',$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const loginView=$('#loginView'),appView=$('#appView'),loginForm=$('#loginForm'),accessCode=$('#accessCode'),loginMessage=$('#loginMessage'),logoutBtn=$('#logoutBtn'),welcomeText=$('#welcomeText');let session=null,restoring=false,panelGuard=false;
try{history.scrollRestoration='manual'}catch{}
function token(){return localStorage.getItem(STORAGE)||''}
function route(){return location.hash.replace(/^#\/?/,'')||'home'}
function clean(next){return String(next||'home').replace(/^\/+|\/+$/g,'')||'home'}
function urlFor(next){return location.pathname+location.search+'#/'+clean(next)}
function readScrolls(){try{return JSON.parse(sessionStorage.getItem(SCROLL_STORE)||'{}')||{}}catch{return{}}}
function saveScroll(r=route()){const m=readScrolls();m[clean(r)]=Math.max(0,Math.round(window.scrollY||0));try{sessionStorage.setItem(SCROLL_STORE,JSON.stringify(m))}catch{}}
function setScroll(r,y){const m=readScrolls();m[clean(r)]=Math.max(0,Number(y)||0);try{sessionStorage.setItem(SCROLL_STORE,JSON.stringify(m))}catch{}}
function restoreScroll(r=route()){const y=Number(readScrolls()[clean(r)]||0);requestAnimationFrame(()=>requestAnimationFrame(()=>window.scrollTo({top:y,behavior:'auto'})))}
function setRoute(next,opt={}){const target=clean(next);if(route()===target){if(opt.force)restore();return}saveScroll();if(!opt.keepScroll)setScroll(target,0);const state={...(history.state||{}),stip:true,route:target,panel:false};if(opt.replace)history.replaceState(state,'',urlFor(target));else history.pushState(state,'',urlFor(target));restore()}
function back(fallback='home'){saveScroll();if(history.state?.panel){history.back();return}if(route()!=='home'&&history.length>1&&history.state?.stip){history.back();return}setRoute(fallback,{replace:true,keepScroll:true})}
function showOnly(id){$$('.view').forEach(v=>v.classList.add('hidden'));document.getElementById(id)?.classList.remove('hidden')}
function msg(t='',kind=''){loginMessage.textContent=t;loginMessage.className=`message ${kind}`.trim()}
function dockButton(action,icon,label){return`<button type="button" data-root-action="${action}" aria-label="${label}"><span>${icon}</span><small>${label}</small></button>`}
function dockActions(r){if(r==='home'||!r)return[];if(r==='planning/personal')return[['mail','✉','Envoyer PDF'],['calendar','▦','Calendrier']];if(r==='planning/team'||r==='planning/spirit')return[['mail','✉','Envoyer équipe'],['calendar','▦','Agenda équipe']];if(r==='planning/change')return[['received','↓','Reçues'],['history','✓','Mes demandes']];if(r==='planning/calendar')return[['personalcal','♙','Mon agenda'],['teamcal','♟','Équipe']];if(r==='contacts/directory')return[['focus-search','⌕','Rechercher'],['contact-share','↥','Exporter']];if(r==='contacts/services')return[['focus-services','☎','Services']];if(r==='contacts/chiefs')return[['focus-chiefs','♟','Encadrement']];if(r==='contacts/share')return[['contact-share','↥','Exporter']];return[]}
function ensureDock(){let d=$('#stipContextDock');if(d)return d;d=document.createElement('nav');d.id='stipContextDock';d.className='stip-context-dock hidden';d.setAttribute('aria-label','Actions rapides');document.body.appendChild(d);return d}
function renderDock(r=route()){const d=ensureDock(),actions=dockActions(r);d.innerHTML=actions.map(x=>dockButton(...x)).join('');d.classList.toggle('hidden',!actions.length);document.body.classList.toggle('stip-has-dock',!!actions.length)}
function emitRoute(r){renderDock(r);window.dispatchEvent(new CustomEvent('stip:route',{detail:{route:r}}))}
function scrollToNode(sel){document.querySelector(sel)?.scrollIntoView({behavior:'smooth',block:'start'})}
function runDockAction(action){const r=route();if(action==='calendar'){window.STIPCalendars?.open?.(r.includes('/team')?'team':'personal');return}if(action==='personalcal'){window.STIPCalendars?.open?.('personal');return}if(action==='teamcal'){window.STIPCalendars?.open?.('team');return}if(action==='mail'){const team=r.includes('/team');location.href=`mailto:?subject=${encodeURIComponent(team?'Planning équipe STIP':'Mon planning STIP')}`;return}if(action==='received'){scrollToNode('.cw-inbox');return}if(action==='history'){scrollToNode('.cw-history');return}if(action==='focus-search'){const i=$('#rhubSearch');i?.focus();i?.scrollIntoView({behavior:'smooth',block:'center'});return}if(action==='focus-services'||action==='focus-chiefs'){scrollToNode('#rhubContent');return}if(action==='contact-share'){if(r!=='contacts/share'){setRoute('contacts/share');setTimeout(()=>$('#rhubExport')?.click(),250)}else $('#rhubExport')?.click()}}
async function access(action,body={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),10000);try{const h={'Content-Type':'application/json'};if(token())h['X-STIP-Session']=token();const r=await fetch(ACCESS_API,{method:'POST',headers:h,body:JSON.stringify({action,...body}),signal:c.signal}),j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw Error(j.error||`Erreur ${r.status}`);return j}finally{clearTimeout(t)}}
function personName(a){return window.STIPName?.format?.(a)||String(a?.prenom||a?.nom||'Agent').trim()}
function showLogin(text=''){window.STIPSession=null;window.dispatchEvent(new CustomEvent('stip:session-ended'));appView.classList.add('hidden');loginView.classList.remove('hidden');renderDock('home');msg(text,text?'error':'');setTimeout(()=>accessCode?.focus(),40)}
function showPublicWithSession(d){session=d;window.STIPSession=d;loginView.classList.remove('hidden');appView.classList.add('hidden');welcomeText.textContent=personName(d.agent||{});renderDock('home');window.dispatchEvent(new CustomEvent('stip:session-ready',{detail:d}))}
function closePanel(){const p=$('#hsPanel');if(!p)return;p.classList.remove('open');p.setAttribute('aria-hidden','true')}
function syncPanelHistory(){const p=$('#hsPanel');if(!p)return;const open=p.classList.contains('open');if(open&&!panelGuard&&!history.state?.panel){history.pushState({...(history.state||{}),stip:true,route:route(),panel:true},'',location.href)}panelGuard=false}
function restore(){if(!session||restoring)return;restoring=true;try{if(!history.state?.panel)closePanel();const r=route();if(r==='home'){showOnly('homeView');emitRoute(r);restoreScroll(r);return}if(r==='planning'||r.startsWith('planning/')){showOnly('planningView');emitRoute(r);restoreScroll(r);return}if(r==='contacts'||r.startsWith('contacts/')){const hub=document.getElementById('rubricHubView');if(hub)showOnly('rubricHubView');else{showOnly('genericView');const g=$('#genericView');if(g)g.innerHTML='<div class="route-loading">Chargement de Contacts…</div>'}emitRoute(r);restoreScroll(r);return}setRoute('home',{replace:true,keepScroll:true})}finally{restoring=false}}
function isCadreFamily(d){return d?.role_key==='cadre'&&d?.permissions?.cadre_dashboard===true}
function renderSession(d){window.dispatchEvent(new CustomEvent('stip:login-success',{detail:d}));if(isCadreFamily(d)){window.STIPSession=d;location.replace('cadre.html');return}session=d;window.STIPSession=d;loginView.classList.add('hidden');appView.classList.remove('hidden');welcomeText.textContent=personName(d.agent||{});window.dispatchEvent(new CustomEvent('stip:session-ready',{detail:d}));if(!location.hash)history.replaceState({stip:true,route:'home',panel:false},'',urlFor('home'));restore()}
loginForm?.addEventListener('submit',async e=>{e.preventDefault();const code=String(accessCode.value||'').replace(/\D/g,'').slice(0,6);if(code.length!==6){msg('Entre les 6 chiffres.','error');return}const submit=loginForm.querySelector('button[type="submit"]');if(submit)submit.disabled=true;msg('Connexion…');try{const d=await access('login',{code});localStorage.setItem(STORAGE,d.session_token);setScroll('home',0);history.replaceState({stip:true,route:'home',panel:false},'',urlFor('home'));renderSession(d);msg('')}catch(err){msg(err.message||'Connexion impossible.','error')}finally{if(submit)submit.disabled=false}});
$('#toggleAccessCode')?.addEventListener('click',function(){const show=accessCode?.type==='password';if(!accessCode)return;accessCode.type=show?'text':'password';this.textContent=show?'Cacher':'Voir'});
logoutBtn?.addEventListener('click',async()=>{try{await access('logout')}catch{}localStorage.removeItem(STORAGE);session=null;try{sessionStorage.removeItem(SCROLL_STORE)}catch{}history.replaceState({stip:true,route:'home',panel:false},'',urlFor('home'));showLogin()});
$('#homeBtn')?.addEventListener('click',()=>setRoute('home'));document.addEventListener('click',e=>{const b=e.target.closest?.('#stipContextDock [data-root-action]');if(b)runDockAction(b.dataset.rootAction)});
window.addEventListener('popstate',e=>{panelGuard=true;restore();if(e.state?.panel)setTimeout(()=>{$('#hsPanel')?.classList.add('open');$('#hsPanel')?.setAttribute('aria-hidden','false')},0)});window.addEventListener('hashchange',restore);window.addEventListener('pagehide',()=>saveScroll(),{capture:true});document.addEventListener('visibilitychange',()=>{if(document.hidden)saveScroll()});
const panel=$('#hsPanel');if(panel)new MutationObserver(syncPanelHistory).observe(panel,{attributes:true,attributeFilter:['class']});
$('#hsPanelBack')?.addEventListener('click',e=>{if(history.state?.panel){e.preventDefault();e.stopImmediatePropagation();back()}},true);
window.STIPRouter={set:setRoute,back,restore,show:showOnly,get:route,saveScroll,restoreScroll};
if(!location.hash)history.replaceState({stip:true,route:'home',panel:false},'',urlFor('home'));
(async()=>{if(!token()){showLogin();return}try{const d=await access('me'),quick=new URLSearchParams(location.search).get('quick')||'';if(quick==='public'){showPublicWithSession(d);return}renderSession(d)}catch{localStorage.removeItem(STORAGE);showLogin('Reconnecte-toi.')}})();
})();