(()=>{'use strict';
const API='https://yzsrmuxghlengnkyphxj.supabase.co/functions/v1/stip-cadre',ACCESS='https://yzsrmuxghlengnkyphxj.supabase.co/functions/v1/stip-access',TOKEN='stip_session_v1',$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],token=()=>localStorage.getItem(TOKEN)||'';let team=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ymd=d=>new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',day:'2-digit',timeZone:'Europe/Paris'}).format(d),fmtDate=d=>new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:'Europe/Paris'}).format(new Date(d+'T12:00:00+02:00'));
async function post(url,body){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','X-STIP-Session':token()},body:JSON.stringify(body),cache:'no-store'}),j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw Error(j.error||`Erreur ${r.status}`);return j}
function dayTitle(date){const now=new Date(),t=ymd(now),tm=new Date(now);tm.setDate(tm.getDate()+1);return date===t?'Aujourd’hui':date===ymd(tm)?'Demain':'Journée sélectionnée'}
function renderDay(d){const e=d.effectif||{},forms=d.events?.formations||[],trainees=d.events?.stagiaires||[],alerts=d.alerts||[],events=[...forms.map(x=>({title:x.title||'Formation',body:[x.horaire,x.lieu].filter(Boolean).join(' · ')})),...trainees.map(x=>({title:`Stagiaire · ${x.name||'—'}`,body:[x.horaires,x.referent?`Référent : ${x.referent}`:''].filter(Boolean).join(' · ')}))];$('#dayEyebrow').textContent=dayTitle(d.date);$('#dayLabel').textContent=fmtDate(d.date);$('#dayBody').classList.remove('loading');const badge=$('#dayBadge');badge.textContent=alerts.length?`${alerts.length} point${alerts.length>1?'s':''} à voir`:'RAS';badge.className=`badge ${alerts.some(a=>Number(a.severity)>=3)?'alert':alerts.length?'warn':'ok'}`;$('#dayBody').innerHTML=`<div class="summary"><div class="stat"><strong>${Number(e.working||0)}</strong><span>agents prévus</span></div><div class="stat"><strong>${events.length}</strong><span>événements utiles</span></div><div class="stat"><strong>${alerts.length}</strong><span>points d’attention</span></div></div>${events.length?`<div class="section-label">À connaître</div><div class="event-list">${events.slice(0,10).map(x=>`<div class="event"><strong>${esc(x.title)}</strong><span>${esc(x.body||'')}</span></div>`).join('')}</div>`:''}${alerts.length?`<div class="section-label">À traiter</div><div class="alert-list">${alerts.slice(0,10).map(a=>`<div class="alert-item ${Number(a.severity)>=3?'high':''}"><strong>${esc(a.title||'Point d’attention')}</strong><span>${esc(a.body||'')}</span></div>`).join('')}</div>`:'<div class="clear">Aucun point particulier signalé pour cette journée.</div>'}`}
function renderWindows(w){const groups=[['admins','#adminWindows','#adminCount','Administration STIP','https://admin.esapin.com'],['responsables','#respWindows','#respCount','Responsable','responsable.html']];for(const [key,boxSel,countSel,label,target] of groups){const items=w?.[key]||[],box=$(boxSel);$(countSel).textContent=String(items.length);box.innerHTML=items.length?items.map(x=>`<a class="contact-card" href="${target}"><div><strong>${esc(x.name)}</strong><span>${esc(label)}</span></div><b>Ouvrir ›</b></a>`).join(''):`<div class="contact-empty">Aucun accès actif actuellement.</div>`}}
function kind(a){const r=String(a.role||'').toLowerCase(),e=String(a.equipe||'').toLowerCase();if(r.includes('chef'))return'chef';if(r.includes('cadre')||e.includes('encadrement'))return'encadrement';return'brancardier'}
function renderTeam(){const q=String($('#teamSearch').value||'').trim().toLowerCase(),f=$('#teamFilter').value;const items=team.filter(a=>{const hay=[a.name,a.ghe,a.equipe,a.role].filter(Boolean).join(' ').toLowerCase();return(!q||hay.includes(q))&&(f==='all'||kind(a)===f)});$('#teamCount').textContent=`${items.length}/${team.length}`;$('#teamList').classList.remove('loading');$('#teamList').innerHTML=items.length?items.map(a=>`<div class="team-row"><div><strong>${esc(a.name)}</strong><span>${esc([a.role,a.ghe].filter(Boolean).join(' · '))}</span></div></div>`).join(''):'<div class="team-empty">Aucun agent avec ce filtre. Choisissez « Tout afficher » pour réinitialiser.</div>'}
async function loadTeam(){const j=await post(API,{action:'team'});team=Array.isArray(j.items)?j.items:[];renderTeam()}
async function loadDate(date){$('#dayBody').className='day-body loading';$('#dayBody').textContent='Chargement des informations…';$('#dayBadge').textContent='Lecture…';$('#dayBadge').className='badge';const j=await post(API,{action:'dashboard',date});renderDay(j.day);renderWindows(j.windows)}
async function boot(){if(!token()){location.href='index.html';return}try{const me=await post(ACCESS,{action:'me'});if(!me.permissions?.cadre_dashboard){location.href='index.html';return}$('#hello').textContent=`Bonjour ${String(me.agent?.prenom||me.agent?.nom||'').toUpperCase()}`.trim();await Promise.all([loadDate(ymd(new Date())),loadTeam()])}catch(e){$('#error').textContent=e.message||'Impossible de charger l’espace Cadre.'}}
$$('[data-date-mode]').forEach(b=>b.onclick=()=>{const d=new Date();if(b.dataset.dateMode==='tomorrow')d.setDate(d.getDate()+1);$$('[data-date-mode]').forEach(x=>x.classList.toggle('active',x===b));$('#futureDate').value='';loadDate(ymd(d)).catch(e=>$('#error').textContent=e.message)});$('#futureDate').onchange=e=>{const v=e.target.value;if(!v)return;$$('[data-date-mode]').forEach(x=>x.classList.remove('active'));loadDate(v).catch(er=>$('#error').textContent=er.message)};$('#teamSearch').oninput=renderTeam;$('#teamFilter').onchange=renderTeam;$('#backBtn').onclick=()=>location.href='index.html';boot();})();