(()=>{'use strict';
const API='https://yzsrmuxghlengnkyphxj.supabase.co/functions/v1/stip-cadre',ACCESS='https://yzsrmuxghlengnkyphxj.supabase.co/functions/v1/stip-access',TOKEN='stip_session_v1',$=s=>document.querySelector(s),token=()=>localStorage.getItem(TOKEN)||'';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ymd=d=>new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',day:'2-digit',timeZone:'Europe/Paris'}).format(d),dateObj=s=>new Date(s+'T12:00:00'),fmtDate=s=>new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:'Europe/Paris'}).format(dateObj(s));
let selected=ymd(new Date()),weekStart=null;
async function post(url,body){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','X-STIP-Session':token()},body:JSON.stringify(body),cache:'no-store'}),j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw Error(j.error||`Erreur ${r.status}`);return j}
async function logout(){const btn=$('#logoutBtn');if(btn)btn.disabled=true;try{if(token())await post(ACCESS,{action:'logout'})}catch{}finally{localStorage.removeItem(TOKEN);location.replace('index.html')}}
function mondayOf(s){const d=typeof s==='string'?dateObj(s):new Date(s),dow=d.getDay()||7;d.setDate(d.getDate()-dow+1);d.setHours(12,0,0,0);return d}
function dayTitle(date){return date===ymd(new Date())?'Aujourd’hui':'Journée sélectionnée'}
function renderWeek(){if(!weekStart)weekStart=mondayOf(selected);const box=$('#weekDays');box.innerHTML=Array.from({length:7},(_,i)=>{const d=new Date(weekStart);d.setDate(d.getDate()+i);const iso=ymd(d),today=iso===ymd(new Date()),active=iso===selected;return `<button type="button" data-day="${iso}" class="week-day ${today?'today':''} ${active?'active':''}"><span>${d.toLocaleDateString('fr-FR',{weekday:'short'}).replace('.','').toUpperCase()}</span><strong>${d.getDate()}</strong><small>${d.toLocaleDateString('fr-FR',{month:'short'}).replace('.','')}</small></button>`}).join('');box.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>selectDate(b.dataset.day))}
function renderDay(d){const e=d.effectif||{},forms=d.events?.formations||[],trainees=d.events?.stagiaires||[],alerts=d.alerts||[],events=[...forms.map(x=>({title:x.title||'Formation',body:[x.horaire,x.lieu].filter(Boolean).join(' · ')})),...trainees.map(x=>({title:`Stagiaire · ${x.name||'—'}`,body:[x.horaires,x.referent?`Référent : ${x.referent}`:''].filter(Boolean).join(' · ')}))];$('#dayEyebrow').textContent=dayTitle(d.date);$('#dayLabel').textContent=fmtDate(d.date);$('#dayBody').classList.remove('loading');const badge=$('#dayBadge');badge.textContent=alerts.length?`${alerts.length} point${alerts.length>1?'s':''} à voir`:'RAS';badge.className=`badge ${alerts.some(a=>Number(a.severity)>=3)?'alert':alerts.length?'warn':'ok'}`;$('#dayBody').innerHTML=`<div class="summary"><div class="stat"><strong>${Number(e.working||0)}</strong><span>agents prévus</span></div><div class="stat"><strong>${events.length}</strong><span>événements utiles</span></div><div class="stat"><strong>${alerts.length}</strong><span>points d’attention</span></div></div>${events.length?`<div class="section-label">À connaître</div><div class="event-list">${events.slice(0,10).map(x=>`<div class="event"><strong>${esc(x.title)}</strong><span>${esc(x.body||'')}</span></div>`).join('')}</div>`:''}${alerts.length?`<div class="section-label">À traiter</div><div class="alert-list">${alerts.slice(0,10).map(a=>`<div class="alert-item ${Number(a.severity)>=3?'high':''}"><strong>${esc(a.title||'Point d’attention')}</strong><span>${esc(a.body||'')}</span></div>`).join('')}</div>`:'<div class="clear">Aucun point particulier signalé pour cette journée.</div>'}`}
async function loadDate(date){$('#error').textContent='';$('#dayBody').className='day-body loading';$('#dayBody').textContent='Chargement des informations…';$('#dayBadge').textContent='Lecture…';$('#dayBadge').className='badge';const j=await post(API,{action:'dashboard',date});renderDay(j.day)}
function selectDate(date){selected=date;if(!weekStart||date<mondayIso()||date>weekEndIso())weekStart=mondayOf(date);renderWeek();loadDate(date).catch(e=>$('#error').textContent=e.message)}
function mondayIso(){return ymd(weekStart||mondayOf(selected))}function weekEndIso(){const d=new Date(weekStart||mondayOf(selected));d.setDate(d.getDate()+6);return ymd(d)}
function moveWeek(delta){const d=new Date(weekStart||mondayOf(selected));d.setDate(d.getDate()+delta*7);weekStart=d;selected=ymd(d);renderWeek();loadDate(selected).catch(e=>$('#error').textContent=e.message)}
async function boot(){if(!token()){location.replace('index.html');return}try{const me=await post(ACCESS,{action:'me'});if(!me.permissions?.cadre_dashboard){location.replace('index.html');return}const first=String(me.agent?.prenom||'').trim().toUpperCase(),last=String(me.agent?.nom||'').trim().toLowerCase();$('#hello').textContent=[first,last].filter(Boolean).join(' ')||'Cadre';weekStart=mondayOf(selected);renderWeek();await loadDate(selected)}catch(e){if(String(e.message||'').toLowerCase().includes('session')){localStorage.removeItem(TOKEN);location.replace('index.html');return}$('#error').textContent=e.message||'Impossible de charger l’espace Cadre.'}}
$('#prevWeek').onclick=()=>moveWeek(-1);$('#nextWeek').onclick=()=>moveWeek(1);$('#logoutBtn').onclick=logout;boot();})();