(() => {
  'use strict';
  const API='https://yzsrmuxghlengnkyphxj.supabase.co/functions/v1/stip-data';
  const STORAGE='stip_session_v1';
  const state={loaded:false,people:[],services:[],filter:'all',query:''};
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
  const digits=v=>String(v||'').replace(/\D/g,'');
  const telHref=v=>{const d=digits(v);return d?`tel:${d.startsWith('33')?'+':d.startsWith('0')?'+33':''}${d.startsWith('0')?d.slice(1):d}`:''};
  function ensureView(){
    if(document.getElementById('contactsView'))return document.getElementById('contactsView');
    const view=document.createElement('section');
    view.id='contactsView';view.className='view hidden contacts-view';
    view.innerHTML=`<div class="view-head contacts-head"><button class="back-btn" id="contactsHome" type="button">←</button><div><p class="kicker">ANNUAIRE GHE</p><h2>Équipe & contacts</h2><p class="contacts-sub">Une recherche, un appel, un mail. Rien de plus.</p></div></div><div class="contacts-tools"><div class="contact-search-wrap"><span>⌕</span><input id="contactSearch" type="search" autocomplete="off" placeholder="Nom, GHE, rôle, numéro, service…"></div><div class="contact-filters" id="contactFilters"><button data-filter="all" class="active">Tous</button><button data-filter="personne">Équipe</button><button data-filter="chef">Chefs</button><button data-filter="administration">Administration</button><button data-filter="service">Services</button></div></div><div id="contactSummary" class="contact-summary"></div><div id="contactResults" class="contact-results"><div class="info-box">Chargement de l’annuaire…</div></div>`;
    document.getElementById('appView')?.appendChild(view);
    view.querySelector('#contactsHome').addEventListener('click',()=>{document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));document.getElementById('homeView')?.classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})});
    view.querySelector('#contactSearch').addEventListener('input',e=>{state.query=e.target.value;render()});
    view.querySelector('#contactFilters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;state.filter=b.dataset.filter;view.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));render()});
    return view;
  }
  async function fetchContacts(){const token=localStorage.getItem(STORAGE)||'';const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','X-STIP-Session':token},body:JSON.stringify({action:'contacts'})});const j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw new Error(j.error||`Erreur ${r.status}`);state.people=j.people||[];state.services=j.services||[];state.loaded=true;}
  function initials(p){return `${String(p.prenom||'').trim().charAt(0)}${String(p.nom||'').trim().charAt(0)}`.toUpperCase()||'GHE'}
  function categoryLabel(p){if(p.categorie==='chef')return'Chef d’équipe';if(p.categorie==='administration')return p.role_metier||'Administration';return p.role_metier||'Équipe'}
  function contactText(p){return [p.prenom,p.nom,p.alias,p.ghe,p.role_metier,p.telephone,p.email_pro].filter(Boolean).join(' ')}
  function serviceText(s){return [s.service,s.site,s.telephone_externe,s.poste_interne,s.email,s.remarque].filter(Boolean).join(' ')}
  function vcard(p){const name=[p.prenom,p.nom].filter(Boolean).join(' ').trim();return ['BEGIN:VCARD','VERSION:3.0',`N:${String(p.nom||'').replace(/;/g,'')};${String(p.prenom||'').replace(/;/g,'')};;;`,`FN:${name}`,p.role_metier?`TITLE:${p.role_metier}`:'',p.telephone?`TEL;TYPE=CELL:${digits(p.telephone)}`:'',p.email_pro?`EMAIL;TYPE=WORK:${p.email_pro}`:'',p.ghe?`ORG:GHE;${p.ghe}`:'','END:VCARD'].filter(Boolean).join('\r\n')}
  function saveVcard(key){const p=state.people.find(x=>x.source_key===key);if(!p)return;const blob=new Blob([vcard(p)],{type:'text/vcard;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${[p.prenom,p.nom].filter(Boolean).join('-')||'contact'}.vcf`;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},600)}
  async function sharePerson(key,button){const p=state.people.find(x=>x.source_key===key);if(!p)return;const name=[p.prenom,p.nom].filter(Boolean).join(' ');const text=[name,p.role_metier,p.ghe,p.telephone,p.email_pro].filter(Boolean).join('\n');try{if(navigator.share){await navigator.share({title:name,text});return}await navigator.clipboard.writeText(text);button.textContent='Copié';setTimeout(()=>button.textContent='Partager',1200)}catch{}}
  function personCard(p,i){const name=[p.prenom,p.nom].filter(Boolean).join(' ').trim()||p.nom;const phone=p.telephone?`<a class="contact-action call" href="${telHref(p.telephone)}">Appeler</a>`:'';const mail=p.email_pro?`<a class="contact-action mail" href="mailto:${esc(p.email_pro)}">Mail</a>`:'';return `<article class="contact-card person-card tilt-${(i%5)+1}" data-search="${esc(norm(contactText(p)))}"><div class="contact-avatar ${p.categorie==='chef'?'chef':''}">${esc(p.icone||'')}<strong>${esc(initials(p))}</strong></div><div class="contact-main"><div class="contact-name-line"><h3>${esc(name)}</h3>${p.ghe?`<span class="ghe-badge">${esc(p.ghe)}</span>`:''}</div><p class="contact-role">${esc(categoryLabel(p))}${p.alias?` · ${esc(p.alias)}`:''}</p>${p.telephone?`<a class="contact-value" href="${telHref(p.telephone)}">${esc(p.telephone)}</a>`:''}${p.email_pro?`<a class="contact-value email" href="mailto:${esc(p.email_pro)}">${esc(p.email_pro)}</a>`:''}<div class="contact-actions">${phone}${mail}<button class="contact-action subtle" data-vcard="${esc(p.source_key)}">Ajouter</button><button class="contact-action subtle" data-share="${esc(p.source_key)}">Partager</button></div></div></article>`}
  function serviceCard(s,i){const tel=s.telephone_externe?`<a class="contact-action call" href="${telHref(s.telephone_externe)}">Appeler</a>`:'';return `<article class="contact-card service-card tilt-${(i%5)+1}" data-search="${esc(norm(serviceText(s)))}"><div class="contact-avatar service">☎<strong>GHE</strong></div><div class="contact-main"><div class="contact-name-line"><h3>${esc(s.service)}</h3>${s.site?`<span class="ghe-badge">${esc(s.site)}</span>`:''}</div>${s.remarque?`<p class="contact-role">${esc(s.remarque)}</p>`:''}${s.telephone_externe?`<a class="contact-value" href="${telHref(s.telephone_externe)}">${esc(s.telephone_externe)}</a>`:''}${s.poste_interne?`<span class="contact-value muted">Poste / DECT : ${esc(s.poste_interne)}</span>`:''}${s.email?`<a class="contact-value email" href="mailto:${esc(s.email)}">${esc(s.email)}</a>`:''}<div class="contact-actions">${tel}${s.email?`<a class="contact-action mail" href="mailto:${esc(s.email)}">Mail</a>`:''}</div></div></article>`}
  function render(){const view=ensureView(),box=view.querySelector('#contactResults'),q=norm(state.query);let people=state.people.filter(p=>(state.filter==='all'||state.filter===p.categorie||(state.filter==='personne'&&p.categorie==='personne'))&&(!q||norm(contactText(p)).includes(q)));let services=state.services.filter(s=>(state.filter==='all'||state.filter==='service')&&(!q||norm(serviceText(s)).includes(q)));view.querySelector('#contactSummary').textContent=`${people.length+services.length} résultat${people.length+services.length>1?'s':''}`;const chef=people.filter(p=>p.categorie==='chef'),admin=people.filter(p=>p.categorie==='administration'),team=people.filter(p=>p.categorie==='personne');let html='';if(team.length)html+=`<section class="contact-section"><div class="contact-section-title"><span></span><h3>Équipe</h3><small>${team.length}</small></div>${team.map(personCard).join('')}</section>`;if(chef.length)html+=`<section class="contact-section"><div class="contact-section-title"><span></span><h3>Chefs d’équipe</h3><small>${chef.length}</small></div>${chef.map((p,i)=>personCard(p,i+team.length)).join('')}</section>`;if(admin.length)html+=`<section class="contact-section"><div class="contact-section-title"><span></span><h3>Administration</h3><small>${admin.length}</small></div>${admin.map((p,i)=>personCard(p,i+team.length+chef.length)).join('')}</section>`;if(services.length)html+=`<section class="contact-section"><div class="contact-section-title"><span></span><h3>Services utiles</h3><small>${services.length}</small></div>${services.map(serviceCard).join('')}</section>`;box.innerHTML=html||'<div class="empty contact-empty">Aucun contact ne correspond à ta recherche.</div>';box.querySelectorAll('[data-vcard]').forEach(b=>b.addEventListener('click',()=>saveVcard(b.dataset.vcard)));box.querySelectorAll('[data-share]').forEach(b=>b.addEventListener('click',()=>sharePerson(b.dataset.share,b)))}
  async function openContacts(){const view=ensureView();document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));view.classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'});if(!state.loaded){view.querySelector('#contactResults').innerHTML='<div class="info-box">Chargement de l’annuaire…</div>';try{await fetchContacts();render()}catch(e){view.querySelector('#contactResults').innerHTML=`<div class="error-text">${esc(e.message||'Annuaire indisponible.')}</div>`}}else render()}
  function bind(){const grid=document.getElementById('moduleGrid');if(!grid)return;grid.querySelectorAll('.module-card').forEach(b=>{const t=b.querySelector('strong')?.textContent?.trim();if(t==='Équipe & contacts'&&!b.dataset.contactsBound){b.dataset.contactsBound='1';b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();openContacts()},true)}})}
  new MutationObserver(bind).observe(document.documentElement,{subtree:true,childList:true});
  document.addEventListener('DOMContentLoaded',()=>{ensureView();bind()});
})();