(()=>{"use strict";
const API="https://yzsrmuxghlengnkyphxj.supabase.co/functions/v1/stip-cleanup-control",STORE="stip_session_v1",$=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let data=null,filter="decision",modifyCase=null;
const token=()=>localStorage.getItem(STORE)||"";
async function call(action,body={}){const r=await fetch(API,{method:"POST",cache:"no-store",headers:{"content-type":"application/json","x-stip-session":token()},body:JSON.stringify({action,...body})}),j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw Error(j.error||"Contrôle indisponible.");return j}
async function handoff(id){return call("gpt_handoff",{case_id:id})}
const arr=v=>Array.isArray(v)?v:v==null||v===""?[]:[v],num=v=>new Intl.NumberFormat("fr-FR").format(Number(v||0)),human=k=>String(k||"").replaceAll("_"," ").replace(/\b\w/g,m=>m.toUpperCase());
function dateTime(v){if(!v)return"Jamais";try{return new Date(v).toLocaleString("fr-FR",{dateStyle:"short",timeStyle:"short"})}catch{return String(v)}}
function pct(v){const n=Number(v||0);return Number.isFinite(n)?Math.max(0,Math.min(100,n)):0}
function val(k,v){const n=Number(v);if(/bytes|size/i.test(k)&&Number.isFinite(n)){const u=["o","Ko","Mo","Go","To"];let x=n,i=0;while(x>=1024&&i<u.length-1){x/=1024;i++}return(i&&x<10?x.toFixed(1):Math.round(x))+" "+u[i]}return Number.isFinite(n)&&typeof v!=="string"?num(v):String(v??"—")}
function status(v){return({open:"À analyser",validated:"Validé",modify_requested:"À modifier",refused:"Refusé",delete_approved:"Suppression validée",executing:"Exécution",done:"Terminé",execution_failed:"Échec",superseded:"Remplacé"})[v]||v}
function source(k){return data?.sources?.find(x=>x.source_key===k)?.label||k||"Source"}
function current(){const all=data?.cases||[];if(filter==="decision")return all.filter(x=>x.status==="open");if(filter==="execution")return all.filter(x=>["validated","modify_requested","delete_approved","executing","execution_failed"].includes(x.status));if(filter==="done")return all.filter(x=>["done","refused","superseded"].includes(x.status));return all}
function items(v){const list=arr(v);if(!list.length)return'<p class="ctrl-empty">Aucun élément supplémentaire.</p>';return'<ul class="ctrl-list">'+list.map(x=>typeof x==="string"?"<li>"+esc(x)+"</li>":"<li><b>"+esc(x.label||x.type||x.kind||"Preuve")+"</b> · "+esc(x.value||x.path||x.url||x.ref||x.name||JSON.stringify(x))+"</li>").join("")+"</ul>"}
function card(c){const metrics=Object.entries(c.metrics||{});return`<details class="ctrl-case" data-id="${esc(c.id)}"><summary><div><div class="ctrl-meta"><span>${esc(source(c.source_key))}</span><span>${esc(status(c.status))}</span><span>Preuve ${esc(c.evidence_score||0)}/100</span></div><h3>${esc(c.title)}</h3><p>${esc(c.question)}</p></div><i></i></summary><div class="ctrl-body"><div class="ctrl-core"><article><b>CONTEXTE</b><p>${esc(c.context_text||"Aucun contexte supplémentaire.")}</p></article><article><b>FACTUEL</b><p>${esc(arr(c.facts)[0]||"Voir les faits détaillés.")}</p></article><article><b>OBJECTIF</b><p>${esc(c.proposed_action||"Décider à partir des preuves.")}</p></article></div><section><h4>MESURABLE</h4><div class="ctrl-metrics">${metrics.length?metrics.map(([k,v])=>`<div><strong>${esc(val(k,v))}</strong><small>${esc(human(k))}</small></div>`).join(""):'<div><strong>—</strong><small>Aucune mesure</small></div>'}</div></section><section><h4>FAITS</h4>${items(c.facts)}</section><section><h4>PREUVES</h4>${items(c.evidence)}</section><section><h4>INCERTITUDES</h4>${items(c.uncertainties)}</section><section><h4>ACTION PROPOSÉE</h4><div class="ctrl-proposal">${esc(c.proposed_action||"Aucune action proposée.")}</div></section><section><h4>PLAN SI VALIDÉ</h4>${items(c.proposed_plan)}</section><div class="ctrl-gpt"><div><strong>Confier à GPT</strong><small>GPT contre-vérifie, tranche techniquement et exécute ce qui est sûr. Il ne te demande confirmation que pour une conséquence irréversible ou importante.</small></div><div class="ctrl-gpt-actions"><button type="button" data-gpt>Confier à GPT</button></div></div>${c.status==="open"?'<details class="ctrl-manual"><summary>Décision manuelle · avancé</summary><div class="ctrl-actions"><button type="button" data-decision="validate">Valider</button><button type="button" data-decision="modify">Modifier</button><button type="button" data-decision="refuse">Refuser</button><button type="button" class="danger" data-decision="delete">Supprimer</button></div></details>':""}<p class="ctrl-msg"></p></div></details>`}
function renderHealth(){const host=$("ctrlHealth"),h=data?.health||{},state=["ok","warning","critical"].includes(h.status)?h.status:"warning",labels={ok:"SOUS CONTRÔLE",warning:"À SURVEILLER",critical:"ACTION REQUISE"},org=h.organization_observation?.config||{},storagePct=pct(h.storage_percent),dbPct=pct(h.db_percent),edge24=Number(org.edge_invocations_24h||0),edgeQuota=Number(org.edge_quota_cycle||org.edge_function_quota_cycle||0),external=Number(h.external_sources_stale||0);host.className="ctrl-health "+state;host.innerHTML='<div class="ctrl-health-head"><div><span class="stip-kicker">COMMUNICATION TECHNIQUE</span><h3>État du système</h3><p>Une seule sortie pour les quotas, le stockage et les défauts d’infrastructure.</p></div><span class="ctrl-health-state">'+esc(labels[state])+'</span></div><div class="ctrl-health-grid"><article class="ctrl-health-card"><small>SUPABASE</small><strong>'+esc(String(h.plan_reference||org.plan||"inconnu").toUpperCase())+'</strong><span>Référence de plan surveillée</span></article><article class="ctrl-health-card"><small>STORAGE</small><strong>'+esc(val("bytes",h.storage_bytes))+' / '+esc(val("bytes",h.storage_quota_bytes))+'</strong><span>'+esc(String(h.storage_percent??0))+' % · '+esc(num(h.storage_objects||0))+' objets</span><div class="ctrl-health-meter"><i style="width:'+storagePct+'%"></i></div></article><article class="ctrl-health-card"><small>BASE</small><strong>'+esc(val("bytes",h.db_bytes))+' / '+esc(val("bytes",h.db_quota_bytes))+'</strong><span>'+esc(String(h.db_percent??0))+' % du quota de référence</span><div class="ctrl-health-meter"><i style="width:'+dbPct+'%"></i></div></article><article class="ctrl-health-card"><small>CONTRÔLE</small><strong>'+esc(dateTime(h.last_completed_scan))+'</strong><span>'+esc(external?external+" source(s) externe(s) à revoir":"Sources externes à jour")+'</span></article></div>'+(edge24?'<div class="ctrl-health-grid"><article class="ctrl-health-card"><small>EDGE FUNCTIONS · DERNIÈRE OBSERVATION</small><strong>'+esc(num(edge24))+' / 24 h</strong><span>Quota cycle : '+esc(edgeQuota?num(edgeQuota):"—")+' · observé '+esc(dateTime(h.organization_observation?.observed_at||org.observed_at))+'</span></article><article class="ctrl-health-card"><small>DERNIER 402</small><strong>'+esc(org.last_402_at?dateTime(org.last_402_at):"Aucun signal récent")+'</strong><span>'+esc(org.status_402_24h?num(org.status_402_24h)+" réponses 402 dans l’observation 24 h":"Aucune mesure 402 enregistrée")+'</span></article></div>':"")+'<ul class="ctrl-health-messages">'+arr(h.messages).map(m=>'<li>'+esc(m)+'</li>').join("")+'</ul>'}
function render(){renderHealth();const cases=data?.cases||[],decision=cases.filter(x=>x.status==="open").length,execution=cases.filter(x=>["validated","modify_requested","delete_approved","executing","execution_failed"].includes(x.status)).length,done=cases.filter(x=>["done","refused","superseded"].includes(x.status)).length;$("ctrlStats").innerHTML=[["À analyser",decision],["En cours",execution],["Traités",done],["Sources",data?.sources?.length||0]].map(([l,n])=>'<div class="ctrl-stat"><strong>'+num(n)+'</strong><span>'+l+'</span></div>').join("");$("ctrlDecisionCount").textContent=decision;$("ctrlExecutionCount").textContent=execution;$("ctrlDoneCount").textContent=done;$("ctrlAllCount").textContent=cases.length;$("ctrlUpdated").textContent="Lecture : "+new Date(data.generated_at).toLocaleString("fr-FR");const list=current();$("ctrlCaseCount").textContent=list.length;$("ctrlListTitle").textContent=filter==="decision"?"À analyser":filter==="execution"?"En cours":filter==="done"?"Traités":"Tous les dossiers";$("ctrlCases").innerHTML=list.length?list.map(card).join(""):'<p class="ctrl-empty">Aucun dossier dans cette vue.</p>';$("ctrlSources").innerHTML=(data.sources||[]).map(s=>'<div class="ctrl-source"><div><b>'+esc(s.label)+'</b><small>'+esc(s.source_type)+' · '+esc(s.locator||"—")+'</small></div><span>'+esc(s.last_status||s.mode||"prêt")+'</span></div>').join("");bind()}
function bind(){document.querySelectorAll(".ctrl-case").forEach(el=>{const c=data.cases.find(x=>x.id===el.dataset.id),msg=el.querySelector(".ctrl-msg");el.querySelector("[data-gpt]")?.addEventListener("click",()=>openGpt(c,msg));el.querySelectorAll("[data-decision]").forEach(b=>b.addEventListener("click",()=>decide(c,b.dataset.decision,msg)))})}
async function load(){try{data=await call("overview");render()}catch(e){$("ctrlCases").innerHTML='<p class="ctrl-empty">'+esc(e.message)+'</p>'}}
function openChatGptTarget(webUrl){
  const ua=navigator.userAgent||"";
  if(/Android/i.test(ua)){
    const target=webUrl.replace(/^https:\/\//,"");
    const intent="intent://"+target+"#Intent;scheme=https;package=com.openai.chatgpt;S.browser_fallback_url="+encodeURIComponent(webUrl)+";end";
    location.href=intent;
    return;
  }
  location.href=webUrl;
}
async function openGpt(c,msg){
  msg.textContent="Préparation du dossier…";
  msg.classList.remove("error");
  try{
    const h=await handoff(c.id);
    const instruction=[
      "Prends en charge ce dossier technique STIP de façon autonome jusqu’à sa clôture.",
      "Ouvre et lis intégralement le dossier temporaire ci-dessous.",
      "Contre-vérifie les faits avec mes connecteurs GitHub, Supabase, Vercel et Google Drive.",
      "Décide toi-même techniquement s’il faut corriger, modifier, refuser ou ne rien faire.",
      "Exécute toi-même les actions sûres, réversibles et testables, puis vérifie le résultat et mets STIP à jour.",
      "Ne me demande pas de choisir entre VALIDER / MODIFIER / REFUSER.",
      "Demande-moi uniquement une confirmation simple si l’action est irréversible ou a une conséquence importante (suppression définitive, coût, domaine critique, perte de données/historique).",
      "Ne me demande jamais de copier-coller une réponse dans STIP.",
      "",
      "DOSSIER TEMPORAIRE : "+h.handoff_url
    ].join("\n");
    const url="https://chatgpt.com/?q="+encodeURIComponent(instruction);
    msg.textContent="Ouverture de ChatGPT…";
    openChatGptTarget(url);
  }catch(e){
    msg.textContent=e.message||"Impossible d’ouvrir GPT.";
    msg.classList.add("error");
  }
}
async function decide(c,d,msg){if(d==="modify"){modifyCase=c;$("ctrlModifyText").value="";$("ctrlModifyDialog").showModal();return}if(d==="delete"&&!confirm("SUPPRESSION DEMANDÉE\n\n"+c.title+"\n\nConfirmer la décision du patron ?"))return;msg.textContent="Enregistrement…";try{await call("decision",{case_id:c.id,decision:d,note:""});await load()}catch(e){msg.textContent=e.message;msg.classList.add("error")}}
$("ctrlBack").onclick=()=>history.length>1?history.back():location.assign("access-manage.html");$("ctrlRefresh").onclick=load;$("ctrlScan").onclick=async()=>{const b=$("ctrlScan"),old=b.textContent;b.disabled=true;b.textContent="Contrôle…";try{const r=await call("request_scan",{scope:[]});await load();b.textContent=r?.run?.status==="completed"?"Contrôle à jour":"Contrôle effectué"}catch(e){b.textContent=e.message}finally{setTimeout(()=>{b.disabled=false;b.textContent=old},1800)}};$("ctrlFilters").onclick=e=>{const b=e.target.closest("[data-filter]");if(!b)return;filter=b.dataset.filter;document.querySelectorAll("[data-filter]").forEach(x=>x.classList.toggle("active",x===b));render()};$("ctrlModifyCancel").onclick=()=>$("ctrlModifyDialog").close();$("ctrlModifySend").onclick=async()=>{const note=$("ctrlModifyText").value.trim();if(!modifyCase||!note){$("ctrlModifyMsg").textContent="Ajoute une consigne.";return}try{await call("decision",{case_id:modifyCase.id,decision:"modify",note});$("ctrlModifyDialog").close();modifyCase=null;await load()}catch(e){$("ctrlModifyMsg").textContent=e.message}};
load();
})();