(()=>{'use strict';
const ROOT='https://yzsrmuxghlengnkyphxj.supabase.co/functions/v1/',STORE='stip_session_v1',$=s=>document.querySelector(s);let day=iso(new Date()),tab=['team','activity','assistant'].includes(new URLSearchParams(location.search).get('tab'))?new URLSearchParams(location.search).get('tab'):'overview',access=null,state={staff:null,activity:null,assistant:null};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function iso(d){return new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',day:'2-digit',timeZone:'Europe/Paris'}).format(d)}function date(v){return new Date(`${v}T12:00:00`)}function fmt(v){return new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(date(v)).replace(/^./,c=>c.toUpperCase())}function token(){return localStorage.getItem(STORE)||''}
async function post(fn,body){const r=await fetch(ROOT+fn,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json','X-STIP-Session':token()},body:JSON.stringify(body)}),j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw Error(j.error||`Erreur ${r.status}`);return j}
function allowed(key){return !!access?.permissions?.[key]}function endOfWeek(){const d=date(day),dow=d.getDay()||7;d.setDate(d.getDate()+7-dow);return iso(d)}function startOfWeek(){const d=date(day),dow=d.getDay()||7;d.setDate(d.getDate()-dow+1);return iso(d)}
function coverageRows(){return(state.staff?.rows||[]).filter(x=>x.metric==='shift').map(x=>`<div class="team-row ${Number(x.gap)<0?'is-low':''}"><span><strong>${esc(x.shift_code||'Créneau')}</strong><small>Planifiés / référence HCL</small></span><b>${esc(x.planned_count)} / ${esc(x.target_count)} · ${Number(x.gap)>0?'+':''}${esc(x.gap)}</b></div>`).join('')}
function activityRows(){const d=state.activity?.day||{},rows=[...(d.alerts||[]),...(d.events?.formations||[]),...(d.events?.stagiaires||[])];return rows.map(x=>`<div class="team-row"><span><strong>${esc(x.title||x.label||x.type||'Information')}</strong><p>${esc(x.body||x.note||x.description||'')}</p></span></div>`).join('')}
function assistantRows(){return(state.assistant?.items||[]).filter(x=>x.date===day).map(x=>`<div class="team-row ${Number(x.severity)>=3?'is-low':''}"><span><strong>${esc(x.title||'Information')}</strong><p>${esc(x.body||x.recommendation_text||'')}</p></span><time>${Number(x.severity)>=3?'À décider':Number(x.severity)>=2?'À anticiper':'Information'}</time></div>`).join('')}
function links(){return`<div class="team-links">${allowed('planning_team')?'<a href="index.html?quick=team">Planning équipe détaillé</a>':''}${allowed('activity')?'<a href="cadre-activite.html">Activité détaillée</a>':''}${allowed('assistant_enabled')?'<a href="assistant.html">Assistant détaillé</a>':''}</div>`}
function overview(){const s=state.staff?.summary||{},sums=state.assistant?.summary||{},events=activityRows()?((state.activity?.day?.alerts||[]).length+(state.activity?.day?.events?.formations||[]).length+(state.activity?.day?.events?.stagiaires||[]).length):0;return`<div class="team-grid"><article class="team-card ${Number(s.gap)<0?'danger':''}"><small>ÉQUIPE DU JOUR</small><strong>${esc(s.planned??'—')}</strong><span>${s.target!=null?`référence ${esc(s.target)} · écart ${Number(s.gap)>0?'+':''}${esc(s.gap)}`:'personnes planifiées'}</span></article><article class="team-card ${events?'warn':''}"><small>ACTIVITÉ</small><strong>${events}</strong><span>événement${events>1?'s':''} ou alerte${events>1?'s':''}</span></article><article class="team-card ${Number(sums.critical_count)>0?'danger':''}"><small>ASSISTANT</small><strong>${Number(sums.critical_count||0)+Number(sums.attention_count||0)}</strong><span>point${Number(sums.critical_count||0)+Number(sums.attention_count||0)>1?'s':''} à suivre</span></article><article class="team-card team-summary"><small>LECTURE GLOBALE</small><p>${esc(sums.headline||'Les moteurs STIP ne signalent pas de point prioritaire pour cette journée.')}</p>${links()}</article></div>`}
function pane(kind){const cfg={team:['ÉQUIPE','Couverture du jour',coverageRows(),'index.html?quick=team','Ouvrir le planning complet'],activity:['ACTIVITÉ','Événements et alertes',activityRows(),'cadre-activite.html','Ouvrir l’analyse complète'],assistant:['ASSISTANT','Aide à la décision',assistantRows(),'assistant.html','Ouvrir l’assistant complet']}[kind],can={team:allowed('planning_team'),activity:allowed('activity'),assistant:allowed('assistant_enabled')}[kind];if(!can)return'<div class="team-empty">Ce volet n’est pas inclus dans votre accès.</div>';return`<section class="team-section"><header><div><small>${cfg[0]}</small><h2>${cfg[1]}</h2></div><a href="${cfg[3]}">${cfg[4]} →</a></header><div class="team-list">${cfg[2]||'<div class="team-empty">Rien à signaler pour cette journée.</div>'}</div></section>`}
function render(){document.querySelectorAll('[data-team-tab]').forEach(b=>b.classList.toggle('active',b.dataset.teamTab===tab));$('#teamDateLabel').textContent=fmt(day);$('#teamContent').innerHTML=tab==='overview'?overview():pane(tab)}
async function load(){if(!token())return location.replace('index.html');$('#teamError').textContent='';$('#teamContent').innerHTML='<div class="team-loading">Actualisation des moteurs STIP…</div>';try{if(!access)access=await post('stip-access',{action:'me'});if(!['planning_team','activity','assistant_enabled'].some(allowed))return location.replace('index.html');const jobs=[allowed('planning_team')?post('stip-staffing',{action:'day',date:day}):null,allowed('activity')?post('stip-cadre',{action:'dashboard',date:day}):null,allowed('assistant_enabled')?post('stip-assistant',{action:'feed',start_date:startOfWeek(),end_date:endOfWeek()}):null],res=await Promise.allSettled(jobs.map(x=>x||Promise.resolve(null)));state.staff=res[0].status==='fulfilled'?res[0].value:null;state.activity=res[1].status==='fulfilled'?res[1].value:null;state.assistant=res[2].status==='fulfilled'?res[2].value:null;const rejected=res.find(x=>x.status==='rejected');if(rejected)$('#teamError').textContent='Certaines données n’ont pas pu être actualisées.';render()}catch(e){$('#teamError').textContent=e.message||String(e);render()}}
function move(n){const d=date(day);d.setDate(d.getDate()+n);day=iso(d);load()}document.querySelectorAll('[data-team-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.teamTab;render()});$('#teamPrev').onclick=()=>move(-1);$('#teamNext').onclick=()=>move(1);$('#teamToday').onclick=()=>{day=iso(new Date());load()};$('#teamRefresh').onclick=load;load();
})();
