(()=>{'use strict';
const DATA_API='https://yzsrmuxghlengnkyphxj.supabase.co/functions/v1/stip-data',ACTION_API='https://yzsrmuxghlengnkyphxj.supabase.co/functions/v1/stip-actions',STORAGE='stip_session_v1',$=s=>document.querySelector(s);
const state={boot:null,home:{actions:[],notifications:[]},session:null,canvas:null,ctx:null,drawing:false,dirty:false,refreshing:null,ready:false,agendaExpanded:false};
const REST=new Set(['RH','RTT','RC','AA','MA','CA','RF','RTA','RTTA','SYR','OFF','REPOS','-','']);
const ICONS={planning:'<svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="16" rx="3"/><path d="M8 3v4M16 3v4M3 10h18"/></svg>',contacts:'<svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"/><path d="M3 20c0-4 2.4-7 6-7s6 3 6 7M16 6.5a2.5 2.5 0 0 1 0 5M17 14c2.5.6 4 2.7 4 5"/></svg>',responsable:'<svg viewBox="0 0 24 24"><path d="M12 3 4 7v5c0 5 3.4 8 8 9 4.6-1 8-4 8-9V7z"/><path d="m9 12 2 2 4-4"/></svg>',newagent:'<svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"/><path d="M3 20c0-4 2.4-7 6-7s6 3 6 7M18 8v6M15 11h6"/></svg>',admin:'<svg viewBox="0 0 24 24"><path d="M12 3 4 7v10l8 4 8-4V7z"/><path d="M9 12h6M12 9v6"/></svg>'};
const DOORS=[['planning','Planning','Mon planning et mon équipe','planning'],['equipe_contacts','Contacts','Annuaire et numéros utiles','contacts'],['responsable','Responsable','Suivi et outils responsables','responsable'],['nouveaux_arrivants','Nouvel agent','Parcours nouvel arrivant','newagent'],['admin','Admin','Accès, imports et administration','admin']];
function token(){return localStorage.getItem(STORAGE)||''}function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]))}function cap(v){v=String(v||'').trim().toLowerCase();return v?v[0].toUpperCase()+v.slice(1):v}function localDate(d=new Date()){const z=new Date(d.getTime()-d.getTimezoneOffset()*60000);return z.toISOString().slice(0,10)}function dateObj(s){return new Date(s+'T12:00:00')}function fmtLong(d=new Date()){return cap(d.toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'}))}function firstName(){const a=state.boot?.agent||state.session?.agent||{};if(a.prenom)return cap(a.prenom);const key=String(a.source_key||'').split('_').filter(Boolean);if(key.length>1)return cap(key[key.length-1]);const parts=String(a.nom||'').trim().split(/\s+/).filter(Boolean);return cap(parts.length>1?parts[parts.length-1]:parts[0]||'STIP')}
async function call(url,action,body={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),10000);try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','X-STIP-Session':token()},body:JSON.stringify({action,...body}),signal:c.signal}),j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw Error(j.error||`Erreur ${r.status}`);return j}finally{clearTimeout(t)}}
function permissions(){return state.boot?.permissions||state.session?.permissions||{}}function has(k){return !!permissions()?.[k]}
function publishBoot(d){state.boot=d;window.STIPBootCache=d;window.dispatchEvent(new CustomEvent('stip:boot-updated',{detail:d}))}
function saveContacts(d){window.STIPContactsCache=d;try{sessionStorage.setItem('stip_contacts_cache_v1',JSON.stringify({at:Date.now(),data:d}))}catch{}window.dispatchEvent(new CustomEvent('stip:contacts-updated',{detail:d}));return d}
function prefetchContacts(){if(!has('equipe_contacts')||window.STIPContactsCache||window.STIPContactsPromise)return;try{const raw=sessionStorage.getItem('stip_contacts_cache_v1');if(raw){const c=JSON.parse(raw);if(c?.data&&Date.now()-Number(c.at||0)<900000){saveContacts(c.data);return}}}catch{}window.STIPContactsPromise=call(DATA_API,'contacts').then(saveContacts).catch(e=>{console.warn(e);return null}).finally(()=>{window.STIPContactsPromise=null})}
function openActions(){const actions=state.home?.actions||[];return actions.filter(a=>a.status==='pending'&&!a.completed_at&&!a.cancelled_at)}
function visibleNotifications(){const pending=new Set(openActions().map(a=>String(a.id)));return(state.home?.notifications||[]).filter(n=>!n.action_id||pending.has(String(n.action_id)))}
function agendaItems(days=7){const items=state.boot?.personal||[],today=dateObj(localDate()),day=today.getDay()||7,start=new Date(today);start.setDate(today.getDate()-day+1);return Array.from({length:days},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);const iso=localDate(d),row=items.find(x=>x.date===iso);return{d,iso,code:String(row?.code||row?.source_value||'').trim(),today:iso===localDate(),dow:d.getDay()||7}})}
function weekItems(){return agendaItems(7)}
function shiftAsset(code){const s=state.boot?.media?.shifts||{},k=String(code||'').trim().toUpperCase();return s[k]||s[`${k}.PNG`]||s[`${k}.JPG`]||s[`${k}.JPEG`]||''}
function todayItem(){return weekItems().find(x=>x.today)||null}
function greeting(){const h=new Date().getHours();return h<11?'Bonjour':h<18?'Bon après-midi':'Bonsoir'}
function dayPhase(){const h=new Date().getHours();return h<10?'Ta journée en un coup d’œil':h<18?'Ce qui compte maintenant':'La suite en un coup d’œil'}
function isoWeek(d){const x=new Date(d);x.setHours(12,0,0,0);x.setDate(x.getDate()+3-((x.getDay()+6)%7));const w1=new Date(x.getFullYear(),0,4);return 1+Math.round(((x-w1)/86400000-3+((w1.getDay()+6)%7))/7)}
function monthTitle(d){return d.toLocaleDateString('fr-FR',{month:'long'}).toUpperCase()}
function agentCard(a={},media={},label='MA FICHE'){const avatar=media?.avatars?.[a.source_key]||a.avatar_url||'',name=window.STIPName?.format?.(a)||[a.prenom,a.nom].filter(Boolean).join(' ')||'Agent',team=String(a.type_planning||a.equipe||'').trim(),role=String(a.role||a.role_metier||'').trim(),ghe=String(a.ghe||'').trim(),tel=String(a.telephone||'').trim(),email=String(a.email||a.email_pro||'').trim(),meta=[team?`Équipe ${cap(team)}`:'',role?cap(role):''].filter(Boolean),initials=((a.prenom?.[0]||'')+(a.nom?.[0]||'')).toUpperCase();return`<section class="cp-profile"><div class="cp-profile-avatar">${avatar?`<img src="${esc(avatar)}" alt="" onerror="this.remove();this.parentElement.textContent='${esc(initials)}'">`:`<span>${esc(initials)}</span>`}</div><div class="cp-profile-main"><span class="cp-eyebrow">${esc(label)}</span><strong>${esc(name)}</strong><small>${esc(meta.join(' · ')||'Informations agent')}</small></div><div class="cp-profile-details">${ghe?`<span><b>GHE</b>${esc(ghe)}</span>`:''}${tel?`<span><b>Téléphone</b>${esc(tel)}</span>`:''}${email?`<span class="cp-profile-email"><b>E-mail</b>${esc(email)}</span>`:''}</div></section>`}
function profileCard(){return agentCard(state.boot?.agent||{},state.boot?.media||{},'MA FICHE')}
window.STIPAgentCard=(agent,media,label)=>agentCard(agent||{},media||window.STIPBootCache?.media||{},label||'AGENT');
function renderAgendaDay(x){const code=(x.code||'—').toUpperCase(),img=shiftAsset(code),codeClass=code.replace(/[^A-Z0-9]/g,'').toLowerCase()||'none';return`<span class="cp-day cp-shift cp-dow-${x.dow} code-${codeClass} ${x.today?'today':''} ${REST.has(code)?'rest':'work'}"><i>${x.d.toLocaleDateString('fr-FR',{weekday:'long'}).replace('.','')}</i><b>${x.d.getDate()}</b><span class="cp-shift-visual">${img?`<img src="${esc(img)}" alt="${esc(code)}">`:`<span>${esc(code)}</span>`}</span>${x.today?'<small>AUJ.</small>':''}</span>`}
function agendaMarkup(w){let out='',lastMonth=-1;w.forEach((x,i)=>{if(i%7===0)out+=`<div class="cp-week-sep" style="grid-column:1/-1;display:flex;align-items:center;gap:7px;margin:${i?8:0}px 1px 0;color:#667f89;font-size:.52rem;font-weight:950;letter-spacing:.08em"><span style="height:1px;flex:1;background:#d9e5e8"></span><b style="white-space:nowrap;color:#315866">SEMAINE ${isoWeek(x.d)}</b><span style="height:1px;flex:1;background:#d9e5e8"></span></div>`;const m=x.d.getMonth();if(m!==lastMonth){out+=`<div class="cp-month-sep" style="grid-column:1/-1;text-align:center;margin:${i?7:0}px 0 1px;font-family:Georgia,serif;font-size:.78rem;font-weight:700;letter-spacing:.11em;color:#153a4a">${monthTitle(x.d)} ${x.d.getFullYear()}</div>`;lastMonth=m}out+=renderAgendaDay(x)});return out}
function planningWidget(){const w=agendaItems(state.agendaExpanded?21:7);return`<section class="cp-card cp-week"><div class="cp-card-head"><h2>À venir</h2></div><div class="cp-days">${agendaMarkup(w)}</div><button class="cp-agenda-more" id="cpAgendaMore" type="button">${state.agendaExpanded?'Réduire':'Voir la suite'}</button></section>`}
function todayWidget(){const x=todayItem(),code=(x?.code||'—').toUpperCase(),img=shiftAsset(code),label=REST.has(code)?'Repos / absence':code==='—'?'Aucune donnée':'Shift du jour';return`<section class="cp-today cp-info-card"${img?` style="--today-image:url('${esc(img)}')"`:''}><div><span class="cp-eyebrow">AUJOURD’HUI</span><strong>${esc(code)}</strong><small>${esc(label)}</small></div>${openActions().length?`<div class="cp-pending"><b>${openActions().length}</b><small>à traiter</small></div>`:''}</section>`}
function doors(){const rows=DOORS.filter(([k])=>has(k));if(!rows.length)return'<div class="cp-empty">Aucun espace n’est activé pour ton accès.</div>';return`<section class="cp-tools"><div class="cp-tools-grid cp-door-grid">${rows.map(([k,t,s,icon])=>`<button class="cp-tool cp-door cp-${k}" data-cp-module="${k}"><span class="cp-tool-icon">${ICONS[icon]}</span><span class="cp-tool-copy"><strong>${esc(t)}</strong><small>${esc(s)}</small></span><b>›</b></button>`).join('')}</div></section>`}
function openModule(k){if(k==='planning'){window.STIPHubs?.planning?.('personal');return}if(k==='equipe_contacts'){window.STIPHubs?.contacts?.();return}if(k==='responsable'){location.href='responsable.html';return}if(k==='nouveaux_arrivants'){location.href='https://esapin69.github.io/Ghe-interne/';return}if(k==='admin'){location.href='https://admin-ghe.esapin.com/';return}}
function render(){const root=$('#homeView .hs-home');if(!root||!state.boot)return;const count=visibleNotifications().length;root.innerHTML=`<header class="cp-head"><div><span class="cp-date">${esc(fmtLong())}</span><h1>${greeting()}, <strong>${esc(firstName())}</strong></h1><p>${dayPhase()}</p></div><button class="cp-bell" id="cpBell" type="button" aria-label="Notifications" style="font-size:1.72rem">🔔${count?`<span>${count>99?'99+':count}</span>`:''}</button></header>${profileCard()}<main class="cp-flow">${planningWidget()}${todayWidget()}${doors()}</main>`;root.querySelectorAll('[data-cp-module]').forEach(b=>b.onclick=()=>openModule(b.dataset.cpModule));$('#cpBell')?.addEventListener('click',openNotifications);$('#cpAgendaMore')?.addEventListener('click',()=>{state.agendaExpanded=!state.agendaExpanded;render()})}
function panel(v){$('#hsPanel')?.classList.toggle('open',!!v);$('#hsPanel')?.setAttribute('aria-hidden',v?'false':'true')}
function renderNotifications(){const l=$('#hsNotifList');if(!l)return;const ns=visibleNotifications();l.innerHTML=ns.length?ns.map(n=>`<button class="hs-note" data-action="${esc(n.action_id||'')}"><strong>${esc(n.title)}</strong>${n.body?`<p>${esc(n.body)}</p>`:''}</button>`).join(''):'<div class="cp-empty">Rien à traiter.</div>';l.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>b.dataset.action&&openAction(b.dataset.action))}
function openNotifications(){panel(true);$('#hsPanelTitle').textContent='À traiter';$('#hsPanelBody').innerHTML='<div id="hsNotifList"></div>';renderNotifications()}
async function openAction(id){panel(true);$('#hsPanelTitle').textContent='À traiter';const b=$('#hsPanelBody');b.innerHTML='';try{const r=await call(ACTION_API,'get',{action_id:id}),a=r.action;if(a.kind==='signature'&&a.evaluation)return renderSignature(a);const url=a?.metadata?.url||a?.metadata?.target_url||'';b.innerHTML=`<div class="hs-sign-card"><h3>${esc(a.title)}</h3><p>${esc(a.body||'')}</p>${url?`<a class="hs-primary hs-link" href="${esc(url)}">Ouvrir le formulaire</a>`:'<p class="hs-sign-meta">Cette demande doit être traitée dans son formulaire d’origine.</p>'}</div>`}catch(e){b.innerHTML=`<div class="hs-note"><strong>Demande indisponible</strong><p>${esc(e.message)}</p></div>`}}
function renderSignature(a){const e=a.evaluation||{};$('#hsPanelBody').innerHTML=`<div class="hs-sign-card"><h3>${esc(a.title)}</h3><p class="hs-sign-meta">${esc(a.body||'')}</p><div class="hs-sign-summary">Évaluation du ${esc(e.evaluation_date||'—')} · Responsable : ${esc(e.evaluator_name||'—')}</div><p class="hs-sign-meta">En signant, tu confirmes avoir pris connaissance de cette version.</p><div class="hs-canvas-wrap"><label>Signature au doigt</label><canvas id="hsSignatureCanvas" width="700" height="360"></canvas></div><div class="hs-sign-actions"><button class="hs-secondary" id="hsClearSig">Effacer</button><button class="hs-primary" id="hsSendSig">Signer et valider</button></div><div id="hsSigStatus"></div></div>`;setupCanvas();$('#hsClearSig').onclick=clearCanvas;$('#hsSendSig').onclick=async()=>{const s=$('#hsSigStatus');if(!state.dirty)return s.textContent='Signe d’abord dans la zone.';try{await call(ACTION_API,'submit_signature',{action_id:a.id,signature:state.canvas.toDataURL('image/png')});s.textContent='Signature enregistrée.';await refresh();setTimeout(()=>panel(false),350)}catch(e){s.textContent=e.message}}}
function setupCanvas(){const c=$('#hsSignatureCanvas'),x=c.getContext('2d');state.canvas=c;state.ctx=x;state.dirty=false;x.lineWidth=5;x.lineCap='round';x.strokeStyle='#153a4a';const p=e=>{const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}};c.onpointerdown=e=>{state.drawing=true;const q=p(e);x.beginPath();x.moveTo(q.x,q.y);c.setPointerCapture(e.pointerId)};c.onpointermove=e=>{if(!state.drawing)return;const q=p(e);x.lineTo(q.x,q.y);x.stroke();state.dirty=true};c.onpointerup=c.onpointercancel=()=>state.drawing=false}
function clearCanvas(){state.ctx?.clearRect(0,0,state.canvas.width,state.canvas.height);state.dirty=false}
async function refresh(){if(!token()||!state.ready)return;if(state.refreshing)return state.refreshing;state.refreshing=(async()=>{try{const [boot,home]=await Promise.allSettled([call(DATA_API,'bootstrap'),call(ACTION_API,'home')]);if(boot.status==='fulfilled'){publishBoot(boot.value);render();prefetchContacts()}else console.warn(boot.reason);if(home.status==='fulfilled'){state.home=home.value;render()}else{console.warn(home.reason);state.home={actions:[],notifications:[]};render()}}finally{state.refreshing=null}})();return state.refreshing}
function ready(e){state.ready=true;state.session=e?.detail||window.STIPSession||state.session;const s=state.session||{},a=s.agent||{};state.boot={agent:a,permissions:s.permissions||{},team:a.type_planning||a.equipe||'',personal:[],media:{avatars:{},shifts:{}}};state.agendaExpanded=false;render();refresh().catch(()=>{})}function ended(){state.ready=false;state.session=null;state.boot=null;state.home={actions:[],notifications:[]};state.agendaExpanded=false;window.STIPBootCache=null;window.STIPContactsCache=null;window.STIPContactsPromise=null;try{sessionStorage.removeItem('stip_contacts_cache_v1')}catch{}}
function init(){window.addEventListener('stip:session-ready',ready);window.addEventListener('stip:session-ended',ended);$('#hsPanelBack')?.addEventListener('click',()=>panel(false));setInterval(()=>{if(state.ready&&!$('#hsPanel')?.classList.contains('open'))refresh().catch(()=>{})},60000);if(window.STIPSession)ready({detail:window.STIPSession})}
init();
})();