(()=>{'use strict';
const DATA_API='https://yzsrmuxghlengnkyphxj.supabase.co/functions/v1/stip-data';
const ACTION_API='https://yzsrmuxghlengnkyphxj.supabase.co/functions/v1/stip-actions';
const STORAGE='stip_session_v1';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={boot:null,home:null,selected:'notifications',canvas:null,ctx:null,drawing:false,dirty:false};
function token(){return localStorage.getItem(STORAGE)||''}
async function call(url,action,body={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','X-STIP-Session':token()},body:JSON.stringify({action,...body}),signal:controller.signal});const j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw new Error(j.error||`Erreur ${r.status}`);return j}catch(e){if(e?.name==='AbortError')throw new Error('Le serveur ne répond pas.');throw e}finally{clearTimeout(timer)}}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function today(){return new Date().toISOString().slice(0,10)}
function fmt(v){return v?new Date(v.slice(0,10)+'T12:00:00').toLocaleDateString('fr-FR',{weekday:'short',day:'numeric',month:'short'}):'—'}
function moduleButton(title){return [...document.querySelectorAll('#moduleGrid .module-card')].find(b=>b.querySelector('strong')?.textContent.trim()===title)}
function openModule(kind){if(kind==='calendar'){document.querySelector('[data-planning="personal"]')?.click();return}if(kind==='team'){document.querySelector('[data-planning="spirit"]')?.click();return}if(kind==='swap'){document.querySelector('[data-planning="change"]')?.click();return}if(kind==='print'){document.querySelector('[data-planning="print"]')?.click();return}if(kind==='contacts'){moduleButton('Équipe & contacts')?.click();return}if(kind==='plans'){moduleButton('Repères')?.click();return}if(kind==='files'){moduleButton('Procédures')?.click();return}if(kind==='tools'){moduleButton('Outils équipe')?.click();return}if(kind==='responsable'){location.href='responsable.html'}}
function syncPermissions(){const resp=moduleButton('Responsable');document.querySelectorAll('[data-hs-app="responsable"]').forEach(x=>x.classList.toggle('hidden',!resp));const map={calendar:'Planning',team:'Planning',swap:'Planning',print:'Planning',contacts:'Équipe & contacts',plans:'Repères',files:'Procédures',tools:'Outils équipe'};for(const[k,t]of Object.entries(map))document.querySelectorAll(`[data-hs-app="${k}"]`).forEach(x=>x.classList.toggle('hidden',!moduleButton(t)))}
function unread(){return(state.home?.notifications||[]).filter(n=>!n.read_at)}
function latestNotification(){return unread()[0]||(state.home?.notifications||[])[0]||null}
function actionPriority(){return state.home?.actions?.[0]||null}
function widgetHTML(kind){const b=state.boot||{},p=(b.personal||[]).filter(x=>x.date>=today()),td=p.find(x=>x.date===today()),nx=p.find(x=>x.date>today()),u=unread(),a=actionPriority(),n=latestNotification();if(kind==='notifications'){if(a)return`<span class="eyebrow">ACTION À FAIRE</span><h3>${esc(a.title)}</h3><p>${esc(a.body||'Une action t’attend dans STIP.')}</p><div class="hs-action-row"><button class="hs-primary" data-widget-action="action" data-id="${esc(a.id)}">Ouvrir</button><button class="hs-secondary" data-widget-action="notifications">${u.length||0} notification${u.length>1?'s':''}</button></div>`;if(n)return`<span class="eyebrow">NOTIFICATIONS</span><h3>${esc(n.title)}</h3><p>${esc(n.body||'')}</p><div class="hs-action-row"><button class="hs-primary" data-widget-action="notifications">Voir les notifications</button></div>`;return'<span class="eyebrow">NOTIFICATIONS</span><h3>Rien à signaler</h3><p>Quand une signature, une validation ou une demande te concerne, elle apparaît ici en priorité.</p>'}
if(kind==='calendar')return`<span class="eyebrow">CALENDRIER</span><h3>${esc(td?.code||'Repos')} aujourd’hui</h3><p>${td?esc(td.observation||'Ton service du jour.'):'Aucun service prévu aujourd’hui.'}${nx?` Prochain service : ${esc(nx.code)} · ${esc(fmt(nx.date))}.`:''}</p><div class="hs-action-row"><button class="hs-primary" data-widget-open="calendar">Ouvrir mon calendrier</button></div>`;
if(kind==='team')return`<span class="eyebrow">ÉQUIPE</span><h3>Qui travaille ?</h3><p>Affiche directement les agents présents, les formations et les informations d’équipe du jour.</p><div class="hs-action-row"><button class="hs-primary" data-widget-open="team">Voir l’équipe</button></div>`;
if(kind==='contacts')return`<span class="eyebrow">CONTACTS</span><h3>Annuaire GHE</h3><p>Agents, services, téléphones et contacts utiles depuis le répertoire STIP.</p><div class="hs-action-row"><button class="hs-primary" data-widget-open="contacts">Ouvrir Contacts</button></div>`;
if(kind==='plans')return`<span class="eyebrow">PLANS</span><h3>Repères terrain</h3><p>Accède aux sites, secteurs et repères utiles sans chercher ailleurs.</p><div class="hs-action-row"><button class="hs-primary" data-widget-open="plans">Ouvrir Plans</button></div>`;
if(kind==='files')return`<span class="eyebrow">FICHIERS</span><h3>Procédures & documents</h3><p>Retrouve les fiches pratiques et documents utiles de l’équipe.</p><div class="hs-action-row"><button class="hs-primary" data-widget-open="files">Ouvrir Fichiers</button></div>`;
if(kind==='swap')return`<span class="eyebrow">ÉCHANGES</span><h3>Changer un horaire</h3><p>Recherche un horaire, un agent compatible ou prépare une demande de changement.</p><div class="hs-action-row"><button class="hs-primary" data-widget-open="swap">Ouvrir Échanges</button></div>`;
if(kind==='print')return`<span class="eyebrow">IMPRIMER</span><h3>Planning papier / PDF</h3><p>Crée la version imprimable de ton planning personnel.</p><div class="hs-action-row"><button class="hs-primary" data-widget-open="print">Ouvrir Imprimer</button></div>`;
if(kind==='responsable'){const rn=(state.home?.notifications||[]).find(x=>/signature|évaluation|responsable/i.test(`${x.title||''} ${x.body||''}`));return`<span class="eyebrow">RESPONSABLE</span><h3>${esc(rn?.title||'Suivi responsable')}</h3><p>${esc(rn?.body||'Évaluations, signatures et demandes en attente apparaissent ici lorsqu’elles nécessitent ton attention.')}</p><div class="hs-action-row"><button class="hs-primary" data-widget-open="responsable">Ouvrir Responsable</button></div>`}
return`<span class="eyebrow">OUTILS</span><h3>Outils d’équipe</h3><p>Accès aux services et ressources utiles de STIP.</p><div class="hs-action-row"><button class="hs-primary" data-widget-open="tools">Ouvrir Outils</button></div>`}
function renderWidget(){const holder=$('#hsActionWidget');if(!holder)return;holder.innerHTML=widgetHTML(state.selected);holder.querySelectorAll('[data-widget-open]').forEach(b=>b.onclick=()=>openModule(b.dataset.widgetOpen));holder.querySelectorAll('[data-widget-action="notifications"]').forEach(b=>b.onclick=()=>openNotifications());holder.querySelectorAll('[data-widget-action="action"]').forEach(b=>b.onclick=()=>openAction(b.dataset.id));$$('[data-hs-app]').forEach(b=>b.classList.toggle('selected',b.dataset.hsApp===state.selected))}
function selectApp(kind){state.selected=kind;renderWidget();document.getElementById('hsActionWidget')?.scrollIntoView({behavior:'smooth',block:'nearest'})}
function renderNotifBadge(){const b=$('#hsNotifBadge'),c=unread().length;if(!b)return;b.hidden=!c;b.textContent=c>9?'9+':String(c)}
function renderNotifications(){const list=$('#hsNotifList');if(!list)return;const ns=state.home?.notifications||[];list.innerHTML=ns.length?ns.map(n=>`<button class="hs-note ${n.read_at?'':'unread'}" data-note="${esc(n.id)}" data-action="${esc(n.action_id||'')}"><strong>${esc(n.title)}</strong><p>${esc(n.body||'')}</p></button>`).join(''):'<div class="hs-note"><strong>Aucune notification</strong><p>Les nouvelles demandes et confirmations apparaîtront ici.</p></div>';list.querySelectorAll('[data-note]').forEach(b=>b.onclick=async()=>{try{await call(ACTION_API,'mark_read',{ids:[b.dataset.note]});if(b.dataset.action)await openAction(b.dataset.action);await refreshHome()}catch(e){console.error(e)}})}
async function refreshHome(){if(!token())return;try{const[b,h]=await Promise.all([call(DATA_API,'bootstrap'),call(ACTION_API,'home')]);state.boot=b;state.home=h;$('#hsMiniName')&&($('#hsMiniName').textContent=h.agent?.prenom||h.agent?.nom||'Mon espace');renderWidget();renderNotifBadge();renderNotifications();syncPermissions()}catch(e){console.error('home-shell',e);const w=$('#hsActionWidget');if(w)w.innerHTML='<span class="eyebrow">STIP</span><h3>Connexion en cours</h3><p>Les notifications se rechargeront automatiquement.</p>'}}
function panel(open){$('#hsPanel')?.classList.toggle('open',!!open);$('#hsPanel')?.setAttribute('aria-hidden',open?'false':'true')}
function panelTitle(t){$('#hsPanelTitle').textContent=t}
function openNotifications(){panel(true);panelTitle('Notifications');const body=$('#hsPanelBody');body.innerHTML='<div id="hsNotifList"></div>';renderNotifications()}
async function openAction(id){panel(true);panelTitle('Demande');const body=$('#hsPanelBody');body.innerHTML='<div class="hs-note">Chargement…</div>';try{const r=await call(ACTION_API,'get',{action_id:id}),a=r.action;if(a.kind==='signature'&&a.evaluation){renderSignature(a);return}body.innerHTML=`<div class="hs-sign-card"><h3>${esc(a.title)}</h3><p class="hs-sign-meta">${esc(a.body||'')}</p><div class="hs-sign-actions"><button class="hs-primary" id="hsComplete">Marquer comme fait</button><button class="hs-secondary" id="hsCloseAction">Fermer</button></div><div class="hs-sign-status" id="hsActionStatus"></div></div>`;$('#hsCloseAction').onclick=()=>panel(false);$('#hsComplete').onclick=async()=>{const s=$('#hsActionStatus');s.textContent='Enregistrement…';try{await call(ACTION_API,'complete',{action_id:a.id});s.textContent='Terminé.';await refreshHome();setTimeout(()=>panel(false),500)}catch(e){s.textContent=e.message}}}catch(e){body.innerHTML=`<div class="hs-note"><strong>Impossible d’ouvrir</strong><p>${esc(e.message)}</p></div>`}}
function renderSignature(a){const e=a.evaluation||{},criteria=e.criteria||{},observed=Object.entries(criteria).filter(([,v])=>v&&v!=='Éléments insuffisants pour évaluer').slice(0,4).map(([k,v])=>`${k} : ${v}`),summary=[`Évaluation du ${fmt(e.evaluation_date)}`,`Responsable : ${e.evaluator_name||'—'}`,e.decision?`Décision : ${e.decision}`:'',...observed].filter(Boolean).join(' · ');$('#hsPanelBody').innerHTML=`<div class="hs-sign-card"><h3>${esc(a.title)}</h3><p class="hs-sign-meta">${esc(a.body||'')}</p><div class="hs-sign-summary">${esc(summary)}</div><p class="hs-sign-meta">En signant, tu confirmes avoir pris connaissance de cette version précise.</p><div class="hs-canvas-wrap"><label>Signature au doigt</label><canvas id="hsSignatureCanvas" width="700" height="360"></canvas></div><div class="hs-sign-actions"><button class="hs-secondary" id="hsClearSig">Effacer</button><button class="hs-primary" id="hsSendSig">Signer et valider</button></div><div class="hs-sign-status" id="hsSigStatus"></div></div>`;setupCanvas();$('#hsClearSig').onclick=clearCanvas;$('#hsSendSig').onclick=async()=>{const s=$('#hsSigStatus');if(!state.dirty){s.textContent='Signe d’abord dans la zone.';return}s.textContent='Enregistrement…';$('#hsSendSig').disabled=true;try{await call(ACTION_API,'submit_signature',{action_id:a.id,signature:state.canvas.toDataURL('image/png')});s.textContent='Signature enregistrée. Le responsable a été notifié.';await refreshHome();setTimeout(()=>panel(false),800)}catch(e){s.textContent=e.message;$('#hsSendSig').disabled=false}}}
function setupCanvas(){const c=$('#hsSignatureCanvas');state.canvas=c;state.ctx=c.getContext('2d');state.ctx.lineWidth=5;state.ctx.lineCap='round';state.ctx.strokeStyle='#123444';state.dirty=false;const pos=e=>{const r=c.getBoundingClientRect(),p=e.touches?.[0]||e;return{x:(p.clientX-r.left)*(c.width/r.width),y:(p.clientY-r.top)*(c.height/r.height)}};const start=e=>{e.preventDefault();state.drawing=true;const p=pos(e);state.ctx.beginPath();state.ctx.moveTo(p.x,p.y)};const move=e=>{if(!state.drawing)return;e.preventDefault();const p=pos(e);state.ctx.lineTo(p.x,p.y);state.ctx.stroke();state.dirty=true};const end=e=>{if(state.drawing)e.preventDefault();state.drawing=false};c.addEventListener('pointerdown',start);c.addEventListener('pointermove',move);c.addEventListener('pointerup',end);c.addEventListener('pointercancel',end)}
function clearCanvas(){if(state.ctx&&state.canvas){state.ctx.clearRect(0,0,state.canvas.width,state.canvas.height);state.dirty=false}}
function init(){const grid=$('#moduleGrid');if(grid)new MutationObserver(()=>{syncPermissions();setTimeout(refreshHome,80)}).observe(grid,{childList:true});$$('[data-hs-app]').forEach(b=>b.onclick=()=>selectApp(b.dataset.hsApp));$$('[data-hs-quick]').forEach(b=>b.onclick=()=>openModule(b.dataset.hsQuick));$('#hsBell')?.addEventListener('click',openNotifications);$('#hsPanelBack')?.addEventListener('click',()=>panel(false));setInterval(()=>{if(!document.getElementById('appView')?.classList.contains('hidden'))refreshHome()},45000);setTimeout(refreshHome,220)}
init();
})();