(()=>{'use strict';
const DATA_API='https://yzsrmuxghlengnkyphxj.supabase.co/functions/v1/stip-data',ACTION_API='https://yzsrmuxghlengnkyphxj.supabase.co/functions/v1/stip-actions',STORE='stip_session_v1',$=s=>document.querySelector(s);
const state={boot:null,home:{actions:[],notifications:[]},session:null,ready:false,refreshing:null,renderSig:'',future:new Map(),exchanges:new Map(),widgets:new Map()};
const REST=new Set(['RH','RTT','RC','AA','MA','CA','RF','RTA','RTTA','SYR','OFF','REPOS','-','']);
const ICON={personal:'<svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="16" rx="3"/><path d="M8 3v4M16 3v4M3 10h18"/></svg>',team:'<svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"/><path d="M3 20c0-4 2.4-7 6-7s6 3 6 7M16 6.5a2.5 2.5 0 0 1 0 5M17 14c2.5.6 4 2.7 4 5"/></svg>',change:'<svg viewBox="0 0 24 24"><path d="M7 7h11l-3-3M17 17H6l3 3"/></svg>',calendar:'<svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="16" rx="3"/><path d="M8 3v4M16 3v4M3 10h18"/></svg>',contacts:'<svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"/><path d="M3 20c0-4 2.4-7 6-7s6 3 6 7M16 6.5a2.5 2.5 0 0 1 0 5M17 14c2.5.6 4 2.7 4 5"/></svg>',responsable:'<svg viewBox="0 0 24 24"><path d="M12 3 4 7v5c0 5 3.4 8 8 9 4.6-1 8-4 8-9V7z"/><path d="m9 12 2 2 4-4"/></svg>',newagent:'<svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"/><path d="M3 20c0-4 2.4-7 6-7s6 3 6 7M18 8v6M15 11h6"/></svg>',upload:'<svg viewBox="0 0 24 24"><path d="M12 3v12M7 8l5-5 5 5"/><path d="M5 14v5h14v-5"/></svg>',admin:'<svg viewBox="0 0 24 24"><path d="M12 3 4 7v10l8 4 8-4V7z"/><path d="M9 12h6M12 9v6"/></svg>'};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]))}function cap(v){v=String(v||'').trim().toLowerCase();return v?v[0].toUpperCase()+v.slice(1):v}function token(){return localStorage.getItem(STORE)||''}
function parisIso(d=new Date()){const p=new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',day:'2-digit',timeZone:'Europe/Paris'}).formatToParts(d),g=t=>p.find(x=>x.type===t)?.value||'';return`${g('year')}-${g('month')}-${g('day')}`}function fmtToday(){return new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'numeric',month:'long',timeZone:'Europe/Paris'}).format(new Date()).replace(/^./,c=>c.toUpperCase())}function dateObj(s){return new Date(String(s).slice(0,10)+'T12:00:00')}function weekNo(d){const x=new Date(d);x.setHours(12,0,0,0);x.setDate(x.getDate()+3-((x.getDay()+6)%7));const w1=new Date(x.getFullYear(),0,4);return 1+Math.round(((x-w1)/86400000-3+((w1.getDay()+6)%7))/7)}
async function call(url,action,body={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),10000);try{const r=await fetch(url,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json','X-STIP-Session':token()},body:JSON.stringify({action,...body}),signal:c.signal}),j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw Error(j.error||`Erreur ${r.status}`);return j}finally{clearTimeout(t)}}
function perms(){return state.boot?.permissions||state.session?.permissions||{}}function has(k){return !!perms()[k]}function publishBoot(d){state.boot=d;window.STIPBootCache=d;window.dispatchEvent(new CustomEvent('stip:boot-updated',{detail:d}))}
function pending(){return(state.home.actions||[]).filter(a=>a.status==='pending'&&!a.completed_at&&!a.cancelled_at)}function notifications(){const p=new Set(pending().map(a=>String(a.id)));return(state.home.notifications||[]).filter(n=>!n.action_id||p.has(String(n.action_id)))}function agentName(a={}){return window.STIPName?.format?.(a)||[a.prenom,a.nom].filter(Boolean).join(' ')||'Agent'}
function done(x){const s=String(x?.status||x?.statut||'').toLowerCase();return !!(x?.completed_at||x?.cancelled_at||x?.resolved_at||['done','termine','terminé','cancelled','annule','annulé','resolved','traite','traité','refused','refuse','refusé','rejected'].includes(s))}
function shiftAsset(code){const s=state.boot?.media?.shifts||{},k=String(code||'').trim().toUpperCase();return s[k]||s[`${k}.PNG`]||s[`${k}.JPG`]||s[`${k}.JPEG`]||''}
function agendaFromToday(days){const rows=state.boot?.personal||[],today=parisIso();return Array.from({length:days},(_,i)=>{const d=dateObj(today);d.setDate(d.getDate()+i);const iso=parisIso(d),r=rows.find(x=>x.date===iso);return{d,iso,dow:d.getDay()||7,today:i===0,code:String(r?.code||r?.source_value||'').trim().toUpperCase()||'—'}})}
function currentWeek(){const today=dateObj(parisIso()),left=7-(today.getDay()||7)+1;return agendaFromToday(Math.max(1,left))}
function dayCard(x,cls='hc-day'){const img=shiftAsset(x.code),code=x.code.replace(/[^A-Z0-9]/g,'').toLowerCase()||'none';return`<span class="${cls} ${x.today?'today':''} ${REST.has(x.code)?'rest':'work'} code-${code}"><i>${esc(x.d.toLocaleDateString('fr-FR',{weekday:'long'}).replace('.','').toUpperCase())}</i><b>${x.d.getDate()}</b><span>${img?`<img src="${esc(img)}" alt="${esc(x.code)}">`:`<strong>${esc(x.code)}</strong>`}</span>${x.today?'<small>AUJ.</small>':''}</span>`}
function weekWidget(){const w=currentWeek(),months=[...new Map(w.map(x=>[`${x.d.getFullYear()}-${x.d.getMonth()}`,x.d])).values()];return`<section class="hc-widget hc-widget-planning" data-widget="planning"><header class="hc-widget-head"><div><small>PLANNING</small><h2>Semaine en cours</h2></div><b>SEMAINE ${weekNo(w[0].d)}</b></header><div class="hc-monthline">${months.map(d=>`<span><strong>${d.toLocaleDateString('fr-FR',{month:'long'}).toUpperCase()}</strong> ${d.getFullYear()}</span>`).join('<i>→</i>')}</div><div class="hc-days" style="--day-count:${w.length}">${w.map(x=>dayCard(x)).join('')}</div><button type="button" class="hc-widget-action" data-widget-open="planning">Voir la suite <b>›</b></button></section>`}
function nativeFuture(){const b=state.boot||{},o=[];(b.agenda_items||[]).filter(x=>!done(x)&&String(x.event_date||'')>=parisIso()).forEach(x=>o.push({id:`agenda:${x.id||x.event_date}`,date:String(x.event_date||'').slice(0,10),endDate:String(x.event_date||'').slice(0,10),icon:x.importance==='urgent'?'⚠️':x.importance==='important'?'❗':'📌',type:x.kind||'Rappel',title:x.title||'Événement',sub:x.all_day?'Toute la journée':[String(x.start_time||'').slice(0,5),String(x.end_time||'').slice(0,5)].filter(Boolean).join('–')}));(b.personal_formations||[]).filter(x=>!done(x)&&String(x.date_fin||x.date_debut||'')>=parisIso()).forEach(x=>o.push({id:`formation:${x.id||x.source_key||x.date_debut}`,date:String(x.date_debut||'').slice(0,10),endDate:String(x.date_fin||x.date_debut||'').slice(0,10),icon:'🎓',type:'Formation',title:x.intitule||'Formation',sub:[x.horaire,x.lieu].filter(Boolean).join(' · ')}));(b.personal_stagiaires||[]).filter(x=>!done(x)&&String(x.date_fin||x.date_debut||'')>=parisIso()).forEach(x=>o.push({id:`stagiaire:${x.id||x.source_key||x.date_debut}`,date:String(x.date_debut||'').slice(0,10),endDate:String(x.date_fin||x.date_debut||'').slice(0,10),icon:'👶',type:'Stagiaire',title:[x.prenom,x.nom].filter(Boolean).join(' ')||'Stagiaire',sub:x.horaires||''}));return o}
function futureItems(){const all=[...nativeFuture(),...state.future.values()].filter(x=>!done(x)&&String(x.endDate||x.end_date||x.date||'')>=parisIso()),m=new Map();all.forEach(x=>{const id=String(x.id||`${x.type}:${x.date}:${x.title}`),old=m.get(id);if(!old||Number(x.priority||0)>Number(old.priority||0))m.set(id,{...x,id,endDate:x.endDate||x.end_date||x.date})});return [...m.values()].sort((a,b)=>String(a.date).localeCompare(String(b.date))||String(a.title).localeCompare(String(b.title),'fr'))}
function fmtDateRange(x){const a=dateObj(x.date),z=dateObj(x.endDate||x.date),f=d=>d.toLocaleDateString('fr-FR',{weekday:'short',day:'numeric',month:'short'}).replace(/\./g,'');return x.endDate&&x.endDate!==x.date?`${f(a)} → ${f(z)}`:f(a)}
function futureWidget(){const items=futureItems(),show=items.slice(0,2);return`<section class="hc-widget hc-widget-future" data-widget="future"><header class="hc-widget-head hc-widget-head-compact"><div><small>PLANNING · FUTUR</small><h2>À venir</h2></div>${items.length>2?`<button type="button" data-widget-open="future">${items.length} dates ›</button>`:''}</header><div class="hc-widget-list">${show.length?show.map(x=>`<button type="button" class="hc-live-row" data-widget-open="future"><i>${x.icon||'•'}</i><span><small>${esc((x.type||'À venir').toUpperCase())} · ${esc(fmtDateRange(x))}</small><strong>${esc(x.title)}</strong>${x.sub?`<em>${esc(x.sub)}</em>`:''}</span><b>›</b></button>`).join(''):'<p class="hc-widget-empty">Aucune date importante à venir.</p>'}</div></section>`}
function nativeExchanges(){const b=state.boot||{},src=[...(b.change_requests||[]),...(b.home?.change_requests||[]),...(b.exchanges||[])];return src.filter(x=>!done(x)).map(x=>({id:`exchange:${x.id||x.request_id||x.date||x.shift_date||'pending'}`,icon:'⇄',title:x.title||x.label||'Changement de planning',sub:x.summary||x.description||([x.from_shift,x.to_shift].filter(Boolean).join(' → ')||'Demande en cours'),date:x.date||x.shift_date||'',priority:50}))}
function exchangeItems(){const m=new Map();[...nativeExchanges(),...state.exchanges.values()].filter(x=>!done(x)).forEach(x=>{const id=String(x.id||`${x.date}:${x.title}`),old=m.get(id);if(!old||Number(x.priority||0)>Number(old.priority||0))m.set(id,{...x,id})});return [...m.values()].sort((a,b)=>Number(b.priority||0)-Number(a.priority||0))}
function exchangeWidget(){const a=exchangeItems();if(!a.length)return'';const x=a[0];return`<section class="hc-widget hc-widget-alert" data-widget="exchange"><header class="hc-widget-head hc-widget-head-compact"><div><small>PLANNING</small><h2>Échanges & changements</h2></div><button type="button" data-widget-open="exchange">${a.length} ›</button></header><button class="hc-live-row" type="button" data-widget-open="exchange"><i>⇄</i><span><strong>${esc(x.title)}</strong><em>${esc(x.sub||'À consulter')}</em></span><b>›</b></button></section>`}
function genericWidgets(){return [...state.widgets.values()].sort((a,b)=>Number(b.priority||0)-Number(a.priority||0)).map(x=>`<section class="hc-widget hc-widget-generic"><header class="hc-widget-head hc-widget-head-compact"><div><small>${esc(x.kicker||'INFO')}</small><h2>${esc(x.title||'À retenir')}</h2></div>${x.count!=null?`<b>${esc(x.count)}</b>`:''}</header>${x.body?`<p class="hc-widget-text">${esc(x.body)}</p>`:''}</section>`).join('')}
function profile(){const a=state.boot?.agent||state.session?.agent||{},media=state.boot?.media||{},avatar=media.avatars?.[a.source_key]||a.avatar_url||'',ghe=String(a.ghe||'').trim(),tel=String(a.telephone||'').trim(),mail=String(a.email||a.email_pro||'').trim(),ini=((a.prenom?.[0]||'')+(a.nom?.[0]||'')).toUpperCase();return`<section class="hc-profile"><div class="hc-avatar">${avatar?`<img src="${esc(avatar)}" alt="">`:`<span>${esc(ini)}</span>`}</div><div class="hc-profile-copy">${ghe?`<strong>${esc(ghe.toUpperCase().startsWith('GHE')?ghe:`GHE ${ghe}`)}</strong>`:''}<div>${tel?`<button data-copy="${esc(tel)}" data-label="Numéro">${esc(tel)}</button>`:''}${mail?`<button data-copy="${esc(mail)}" data-label="E-mail">${esc(mail)}</button>`:''}</div></div></section>`}
function app(kind,title,cls,action){return`<button class="hc-app ${cls}" data-app="${action}"><span>${ICON[kind]}</span><strong>${esc(title)}</strong></button>`}function apps(){let s='';if(has('planning_personal'))s+=app('personal','Planning perso','personal','personal');if(has('planning_team'))s+=app('team','Planning équipe','team','team');if(has('change_app'))s+=app('change','Changement','change','change');if(has('calendar_subscribe'))s+=app('calendar','Mon agenda','calendar','calendar');if(has('contacts'))s+=app('contacts','Contacts','contacts','contacts');if(has('responsable'))s+=app('responsable','Responsable','responsable','responsable');if(has('nouveaux_arrivants'))s+=app('newagent','Nouvel agent','newagent','newagent');if(has('file_upload'))s+=app('upload','Importer','upload','upload');if(has('admin'))s+=app('admin','Admin','admin','admin');return s||'<p class="hc-empty">Aucune application autorisée.</p>'}
function render(){const root=$('#homeView .hs-home');if(!root||!state.boot)return;const a=state.boot.agent||state.session?.agent||{},name=agentName(a),team=String(a.type_planning||a.equipe||'').trim(),count=notifications().length,markup=`<header class="hc-head"><div><h1>${esc(name)}</h1><p>${team?`Équipe ${esc(cap(team))}`:'Mon espace personnel'}</p></div><div class="hc-actions"><button id="cpBell" class="hc-bell" aria-label="Notifications">🔔${count?`<span>${count}</span>`:''}</button><button class="hc-logout" id="hcLogout">Déconnexion <b>→</b></button></div></header>${profile()}<div class="hc-date">${esc(fmtToday())}</div><main class="hc-widget-zone"><section class="hc-planning-group">${weekWidget()}${futureWidget()}</section>${exchangeWidget()}${genericWidgets()}</main><div class="hc-app-divider"><span>APPLICATIONS</span></div><section class="hc-apps">${apps()}</section>`;if(state.renderSig===markup&&root.childElementCount)return;const onHome=(window.STIPRouter?.get?.()||'home')==='home',y=onHome?Math.max(0,window.scrollY||0):0;state.renderSig=markup;root.innerHTML=markup;root.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>copyText(b.dataset.copy,b.dataset.label));$('#hcLogout')?.addEventListener('click',()=>document.getElementById('logoutBtn')?.click());$('#cpBell')?.addEventListener('click',openNotifications);root.querySelectorAll('[data-app]').forEach(b=>b.onclick=()=>openApp(b.dataset.app));root.querySelectorAll('[data-widget-open]').forEach(b=>b.onclick=()=>openWidget(b.dataset.widgetOpen));window.dispatchEvent(new CustomEvent('stip:home-rendered'));if(onHome&&y>0)requestAnimationFrame(()=>requestAnimationFrame(()=>{if((window.STIPRouter?.get?.()||'home')==='home'&&Math.abs((window.scrollY||0)-y)>2)window.scrollTo({top:y,behavior:'auto'})}))}
async function copyText(v,l){try{await navigator.clipboard.writeText(v)}catch{}let t=$('.hc-toast');if(!t){t=document.createElement('div');t.className='hc-toast';document.body.appendChild(t)}t.textContent=`${l} copié`;t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),1300)}
function openApp(k){if(k==='personal')return window.STIPHubs?.planning?.('personal');if(k==='team')return window.STIPHubs?.planning?.('spirit');if(k==='change')return window.STIPHubs?.planning?.('change');if(k==='calendar'){window.STIPHubs?.planning?.('personal');setTimeout(()=>window.dispatchEvent(new CustomEvent('stip:planning-quick-action',{detail:{action:'calendar',scope:'personal'}})),80);return}if(k==='contacts')return window.STIPHubs?.contacts?.();if(k==='responsable')return location.href='responsable.html';if(k==='newagent')return location.href='https://esapin69.github.io/Ghe-interne/';if(k==='upload')return location.href='https://admin-ghe.esapin.com/depot.html';if(k==='admin')return location.href='https://admin-ghe.esapin.com/'}
function panel(v,title=''){const p=$('#hsPanel');p?.classList.toggle('open',!!v);p?.setAttribute('aria-hidden',v?'false':'true');if(title&&$('#hsPanelTitle'))$('#hsPanelTitle').textContent=title}
function panelDays(){const w=agendaFromToday(21);let out='',lastW=null,lastM=null;w.forEach(x=>{const wn=weekNo(x.d),mk=`${x.d.getFullYear()}-${x.d.getMonth()}`;if(wn!==lastW){out+=`<div class="hc-panel-sep"><span></span><b>SEMAINE ${wn}</b><span></span></div>`;lastW=wn}if(mk!==lastM){out+=`<div class="hc-panel-month">${x.d.toLocaleDateString('fr-FR',{month:'long'}).toUpperCase()} ${x.d.getFullYear()}</div>`;lastM=mk}out+=dayCard(x,'hc-panel-day')});return out}
function openWidget(kind){const body=$('#hsPanelBody');if(!body)return;if(kind==='planning'){panel(true,'Planning · prochaines semaines');body.innerHTML=`<section class="hc-panel-widget"><div class="hc-panel-days">${panelDays()}</div><button class="hc-panel-primary" id="hcOpenPersonal">Ouvrir mon planning complet</button></section>`;$('#hcOpenPersonal')?.addEventListener('click',()=>{panel(false);openApp('personal')});return}if(kind==='future'){const a=futureItems();panel(true,'À venir');body.innerHTML=`<section class="hc-panel-widget"><div class="hc-panel-list">${a.length?a.map(x=>`<article><i>${x.icon||'•'}</i><div><small>${esc((x.type||'À venir').toUpperCase())} · ${esc(fmtDateRange(x))}</small><strong>${esc(x.title)}</strong>${x.sub?`<p>${esc(x.sub)}</p>`:''}</div></article>`).join(''):'<p class="hc-empty">Aucune date importante à venir.</p>'}</div></section>`;return}if(kind==='exchange'){const a=exchangeItems();panel(true,'Échanges & changements');body.innerHTML=`<section class="hc-panel-widget"><div class="hc-panel-list">${a.map(x=>`<article><i>⇄</i><div><strong>${esc(x.title)}</strong><p>${esc(x.sub||'À consulter')}</p></div></article>`).join('')}</div><button class="hc-panel-primary" id="hcOpenChange">Ouvrir Changement</button></section>`;$('#hcOpenChange')?.addEventListener('click',()=>{panel(false);openApp('change')});return}}
function openNotifications(){panel(true,'À traiter');const body=$('#hsPanelBody'),ns=notifications();if(!body)return;body.innerHTML=ns.length?`<div class="hc-panel-list">${ns.map(n=>`<button class="hs-note" data-action="${esc(n.action_id||'')}"><strong>${esc(n.title)}</strong>${n.body?`<p>${esc(n.body)}</p>`:''}</button>`).join('')}</div>`:'<div class="hc-empty">Rien à traiter.</div>';body.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>b.dataset.action&&openAction(b.dataset.action))}
async function openAction(id){const body=$('#hsPanelBody');try{const r=await call(ACTION_API,'get',{action_id:id}),a=r.action,url=a?.metadata?.url||a?.metadata?.target_url||'';body.innerHTML=`<div class="hs-sign-card"><h3>${esc(a.title||'À traiter')}</h3><p>${esc(a.body||'')}</p>${url?`<a class="hc-panel-primary" href="${esc(url)}">Ouvrir</a>`:'<p class="hs-sign-meta">Ouvre la demande depuis son écran d’origine.</p>'}</div>`}catch(e){body.innerHTML=`<div class="hs-note"><strong>Demande indisponible</strong><p>${esc(e.message)}</p></div>`}}
function saveContacts(d){window.STIPContactsCache=d;try{sessionStorage.setItem('stip_contacts_cache_v1',JSON.stringify({at:Date.now(),data:d}))}catch{}window.dispatchEvent(new CustomEvent('stip:contacts-updated',{detail:d}));return d}function prefetchContacts(){if(!has('contacts')||window.STIPContactsCache||window.STIPContactsPromise)return;window.STIPContactsPromise=call(DATA_API,'contacts').then(saveContacts).catch(()=>null).finally(()=>window.STIPContactsPromise=null)}
async function refresh(){if(!token()||!state.ready)return;if(state.refreshing)return state.refreshing;state.refreshing=(async()=>{try{const [boot,home]=await Promise.allSettled([call(DATA_API,'bootstrap'),call(ACTION_API,'home')]);if(boot.status==='fulfilled'){publishBoot(boot.value);prefetchContacts()}if(home.status==='fulfilled')state.home=home.value;render()}finally{state.refreshing=null}})();return state.refreshing}
function ready(e){state.ready=true;state.session=e?.detail||window.STIPSession||state.session;state.renderSig='';const a=state.session?.agent||{};publishBoot({agent:a,permissions:state.session?.permissions||{},team:a.type_planning||a.equipe||'',personal:[],media:{avatars:{},shifts:{}}});render();refresh().catch(()=>{})}function ended(){state.ready=false;state.session=null;state.boot=null;state.home={actions:[],notifications:[]};state.renderSig='';window.STIPBootCache=null;panel(false)}
function publishMap(map,x){if(!x?.title)return;const id=String(x.id||`${x.type||'item'}:${x.date||''}:${x.title}`);map.set(id,{...x,id});state.renderSig='';render()}function removeMap(map,id){map.delete(String(id||''));state.renderSig='';render()}
window.STIPTimeline={publish:x=>publishMap(state.future,x),remove:id=>removeMap(state.future,id)};window.STIPExchange={publish:x=>publishMap(state.exchanges,x),remove:id=>removeMap(state.exchanges,id)};window.STIPWidgets={publish:x=>publishMap(state.widgets,x),remove:id=>removeMap(state.widgets,id)};
window.STIPAgentCard=(agent,media,label='AGENT')=>{const a=agent||{},av=media?.avatars?.[a.source_key]||a.avatar_url||'';return`<section class="hc-profile"><div class="hc-avatar">${av?`<img src="${esc(av)}" alt="">`:''}</div><div class="hc-profile-copy"><small>${esc(label)}</small><strong>${esc(agentName(a))}</strong></div></section>`};
window.addEventListener('stip:session-ready',ready);window.addEventListener('stip:session-ended',ended);$('#hsPanelBack')?.addEventListener('click',()=>panel(false));setInterval(()=>{if(state.ready&&!document.hidden&&(window.STIPRouter?.get?.()||'home')==='home')refresh().catch(()=>{})},60000);if(window.STIPSession)ready({detail:window.STIPSession});
})();