(()=>{"use strict";
const ACCESS="https://yzsrmuxghlengnkyphxj.supabase.co/functions/v1/stip-access",
DATA="https://yzsrmuxghlengnkyphxj.supabase.co/functions/v1/stip-data",
STORE="stip_session_v1",
app=document.getElementById("accountApp"),
input=document.getElementById("accountPhotoInput"),
toastNode=document.getElementById("accountToast");
let state={session:null,boot:null,agent:null,busy:false};

const token=()=>localStorage.getItem(STORE)||"";
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const cap=v=>{v=String(v||"").trim();return v?v[0].toUpperCase()+v.slice(1):""};
const route=()=>location.hash.replace(/^#/,"")||"home";
const personalPhotoUrl=()=>String(state.agent?.profile_photo_url||"");
const photoUrl=()=>personalPhotoUrl()||String(state.agent?.avatar_url||"");
const canPhoto=()=>state.session?.permissions?.profile_photo===true;
const ghe=()=>{const v=String(state.agent?.ghe||"").trim();return !v?"":v.toUpperCase().startsWith("GHE")?v.toUpperCase():("GHE "+v.toUpperCase())};
const name=()=>[state.agent?.prenom,state.agent?.nom].filter(Boolean).join(" ")||"Mon compte";
const initials=()=>((state.agent?.prenom?.[0]||"")+(state.agent?.nom?.[0]||"")).toUpperCase()||"ST";
function toast(t,err=false){toastNode.textContent=t;toastNode.className="account-toast "+(err?"error ":"")+"show";clearTimeout(toastNode._t);toastNode._t=setTimeout(()=>toastNode.className="account-toast",2200)}
async function call(url,action,body={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),20000);try{const r=await fetch(url,{method:"POST",cache:"no-store",headers:{"Content-Type":"application/json","X-STIP-Session":token()},body:JSON.stringify({action,...body}),signal:c.signal}),j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw Error(j.error||("Erreur "+r.status));return j}catch(e){if(e?.name==="AbortError")throw Error("Le serveur met trop de temps à répondre.");throw e}finally{clearTimeout(t)}}
async function load(){if(!token()){location.replace("index.html");return}try{const [s,b]=await Promise.all([call(ACCESS,"me"),call(DATA,"bootstrap").catch(()=>null)]);state.session=s;state.boot=b;state.agent={...(s.agent||{}),...(b?.agent||{})};applyPrefs();render()}catch(e){localStorage.removeItem(STORE);location.replace("index.html")}}
function applyPrefs(){document.body.classList.toggle("account-compact",localStorage.getItem("stip_pref_compact_v1")==="1");document.body.classList.toggle("account-reduce-motion",localStorage.getItem("stip_pref_reduce_motion_v1")==="1")}
function header(title,subtitle,back=false){return '<section class="account-hero"><div class="account-top">'+(back?'<button class="back-btn" data-back aria-label="Retour à Mon compte">‹</button>':'<div class="account-brand">STIP</div>')+'<div class="account-top-actions"><button class="icon-btn" data-home aria-label="Accueil STIP">⌂</button><button class="icon-btn" data-notifications aria-label="Notifications">🔔</button></div></div><div class="account-heading"><h1>'+esc(title)+'</h1><p>'+esc(subtitle)+'</p></div></section>'}
function avatar(){const u=photoUrl();return u?'<img src="'+esc(u)+'" alt="Photo de profil">':'<div class="fallback">'+esc(initials())+'</div>'}
function profileSummary(){const a=state.agent||{},role=String(a.role||state.session?.role_label||"").trim();return '<div class="profile-grid"><button class="profile-photo" data-go="photo" aria-label="Gérer la photo de profil">'+avatar()+'</button><div class="profile-copy"><h2>'+esc(name())+'</h2><div class="profile-ghe">'+esc(ghe())+'</div>'+(role?'<div class="profile-role">● '+esc(cap(role))+'</div>':'')+'<div class="profile-lines">'+(a.telephone?'<button data-copy="'+esc(a.telephone)+'">'+esc(a.telephone)+'</button>':'')+(a.email?'<button data-copy="'+esc(a.email)+'">'+esc(a.email)+'</button>':'')+'</div><button class="profile-edit" data-go="infos">Voir mes informations</button></div></div>'}
function actions(){const visible=!!photoUrl(),personal=!!personalPhotoUrl();return '<div class="photo-actions"><button class="photo-action primary" data-save-photo '+(!visible?'disabled':'')+'>↓ Enregistrer</button><button class="photo-action" data-change-photo '+(!canPhoto()?'disabled':'')+'>✎ Changer</button><button class="photo-action danger" data-delete-photo '+(!(canPhoto()&&personal)?'disabled':'')+'>⌫ Supprimer</button><button class="photo-action logout" data-logout>↪ Se déconnecter</button></div>'}
function home(){return header("Mon compte","Mes informations, ma photo et mon espace STIP")+ '<div class="account-wrap"><section class="account-card profile-card">'+profileSummary()+actions()+'</section><nav class="account-nav"><button data-go="infos"><span class="nav-icon">👤</span><span><strong>Informations personnelles</strong><small>Coordonnées, établissement et profil</small></span><span class="chev">›</span></button><button data-go="security"><span class="nav-icon">🔐</span><span><strong>Accès et sécurité</strong><small>Session, rôle et autorisations</small></span><span class="chev">›</span></button><button data-go="preferences"><span class="nav-icon">⚙️</span><span><strong>Préférences</strong><small>Affichage et comportement du compte</small></span><span class="chev">›</span></button></nav><footer class="account-footer"><strong>STIP</strong><br>Mon espace personnel</footer></div>'}
function infoRow(label,val,copy=false){if(!val)return"";return '<div class="info-row"><div><small>'+esc(label)+'</small><strong>'+esc(val)+'</strong></div>'+(copy?'<button class="copy-btn" data-copy="'+esc(val)+'">Copier</button>':'')+'</div>'}
function infos(){const a=state.agent||{};return header("Informations personnelles","Les données actuellement utilisées par STIP",true)+'<div class="account-wrap subpage"><div class="subhead"><div><h2>Mon identité</h2><p>Les données professionnelles de référence restent protégées.</p></div></div><section class="info-list">'+infoRow("Nom",a.nom)+infoRow("Prénom",a.prenom)+infoRow("Téléphone",a.telephone,true)+infoRow("E-mail",a.email,true)+infoRow("Établissement",ghe())+infoRow("Équipe",a.type_planning||a.equipe)+infoRow("Métier / rôle",a.role||state.session?.role_label)+'</section><footer class="account-footer"><strong>STIP</strong></footer></div>'}
function security(){const p=state.session?.permissions||{},allowed=Object.keys(p).filter(k=>p[k]===true&&!k.startsWith("__"));return header("Accès et sécurité","Ce qui protège et autorise votre compte",true)+'<div class="account-wrap subpage"><section class="security-list"><div class="security-row"><small>SESSION ACTUELLE</small><strong>Connectée sur cet appareil</strong><p>Votre session STIP est active. Vous pouvez la fermer immédiatement ci-dessous.</p></div><div class="security-row"><small>PROFIL D’ACCÈS</small><strong>'+esc(state.session?.role_label||state.session?.role_key||"STIP")+'</strong><p>'+allowed.length+' autorisation'+(allowed.length>1?'s':'')+' active'+(allowed.length>1?'s':'')+'.</p><div class="permission-chips">'+allowed.slice(0,12).map(k=>'<span>'+esc(k.replaceAll("_"," "))+'</span>').join("")+'</div></div></section><button class="photo-action logout" data-logout style="width:100%;margin-top:2px">↪ Se déconnecter de cet appareil</button><footer class="account-footer"><strong>STIP</strong></footer></div>'}
function prefRow(key,title,desc){const on=localStorage.getItem(key)==="1";return '<div class="pref-row"><div><small>PRÉFÉRENCE</small><strong>'+esc(title)+'</strong><p>'+esc(desc)+'</p></div><button class="switch '+(on?'on':'')+'" data-pref="'+esc(key)+'" aria-pressed="'+on+'"><i></i></button></div>'}
function preferences(){return header("Préférences","Des réglages simples qui ont un effet réel",true)+'<div class="account-wrap subpage"><section class="pref-list">'+prefRow("stip_pref_compact_v1","Affichage compact","Réduit les espaces de cette zone compte.")+prefRow("stip_pref_reduce_motion_v1","Animations réduites","Désactive les transitions et animations du compte.")+'</section><button class="photo-action" data-reset-prefs style="width:100%">Réinitialiser mes préférences</button><footer class="account-footer"><strong>STIP</strong></footer></div>'}
function photo(){return header("Gérer la photo","Voir, enregistrer, changer ou supprimer votre photo",true)+'<div class="account-wrap subpage"><section class="account-card photo-page-card"><div class="photo-page-image">'+avatar()+'</div>'+actions()+'</section><footer class="account-footer"><strong>STIP</strong></footer></div>'}
function render(){const r=route();app.innerHTML=r==="infos"?infos():r==="security"?security():r==="preferences"?preferences():r==="photo"?photo():home();bind()}
function bind(){
  app.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>{location.hash=b.dataset.go});
  app.querySelectorAll("[data-back]").forEach(b=>b.onclick=()=>{location.hash=""});
  app.querySelectorAll("[data-home]").forEach(b=>b.onclick=()=>{location.href="index.html"});
  app.querySelectorAll("[data-notifications]").forEach(b=>b.onclick=()=>{try{sessionStorage.setItem("stip_home_mode_once","notifications")}catch{}location.href="index.html"});
  app.querySelectorAll("[data-copy]").forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(b.dataset.copy||"");toast("Copié")}catch{toast("Copie impossible",true)}});
  app.querySelectorAll("[data-save-photo]").forEach(b=>b.onclick=savePhoto);
  app.querySelectorAll("[data-change-photo]").forEach(b=>b.onclick=()=>input.click());
  app.querySelectorAll("[data-delete-photo]").forEach(b=>b.onclick=deletePhoto);
  app.querySelectorAll("[data-logout]").forEach(b=>b.onclick=logout);
  app.querySelectorAll("[data-pref]").forEach(b=>b.onclick=()=>{const k=b.dataset.pref,on=localStorage.getItem(k)!=="1";localStorage.setItem(k,on?"1":"0");applyPrefs();render();toast("Préférence enregistrée")});
  app.querySelectorAll("[data-reset-prefs]").forEach(b=>b.onclick=()=>{localStorage.removeItem("stip_pref_compact_v1");localStorage.removeItem("stip_pref_reduce_motion_v1");applyPrefs();render();toast("Préférences réinitialisées")});
}
async function loadImage(file){if("createImageBitmap"in window){const bmp=await createImageBitmap(file);return{source:bmp,width:bmp.width,height:bmp.height,close:()=>bmp.close?.()}}return await new Promise((res,rej)=>{const u=URL.createObjectURL(file),im=new Image();im.onload=()=>res({source:im,width:im.naturalWidth,height:im.naturalHeight,close:()=>URL.revokeObjectURL(u)});im.onerror=()=>{URL.revokeObjectURL(u);rej(Error("Lecture impossible."))};im.src=u})}
async function compress(file){if(!file.type.startsWith("image/"))throw Error("Choisis une image.");const d=await loadImage(file);try{const side=Math.min(d.width,d.height),sx=(d.width-side)/2,sy=(d.height-side)/2,cv=document.createElement("canvas");cv.width=cv.height=720;const x=cv.getContext("2d",{alpha:false});x.drawImage(d.source,sx,sy,side,side,0,0,720,720);let blob=null;for(const q of [.84,.74,.64,.54]){blob=await new Promise((res,rej)=>cv.toBlob(b=>b?res(b):rej(Error("Conversion impossible.")),"image/webp",q));if(blob.size<=350000)break}if(!blob||blob.size>350000)throw Error("Photo trop volumineuse.");return await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result).split(",")[1]||"");r.onerror=()=>rej(Error("Lecture impossible."));r.readAsDataURL(blob)})}finally{d.close?.()}}
input.addEventListener("change",async()=>{const f=input.files?.[0];input.value="";if(!f||state.busy)return;state.busy=true;try{const base64=await compress(f),r=await call(ACCESS,"profile_photo_set",{base64});state.agent.profile_photo_url=r.profile_photo_url||"";toast("Photo mise à jour");render()}catch(e){toast(e.message||"Impossible de modifier la photo",true)}finally{state.busy=false}});
async function savePhoto(){const u=photoUrl();if(!u)return;try{const r=await fetch(u,{cache:"no-store",mode:"cors"});if(!r.ok)throw Error();const blob=await r.blob(),ext=(blob.type.split("/")[1]||"webp").replace("jpeg","jpg"),a=document.createElement("a"),o=URL.createObjectURL(blob);a.href=o;a.download="photo-profil-"+name().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-")+"."+ext;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(o),4000);toast("Photo enregistrée")}catch{toast("Téléchargement impossible",true)}}
async function deletePhoto(){if(!canPhoto()||!personalPhotoUrl()||state.busy)return;if(!confirm("Supprimer la photo de profil ?"))return;state.busy=true;try{await call(ACCESS,"profile_photo_delete");state.agent.profile_photo_url="";toast("Photo supprimée");render()}catch(e){toast(e.message||"Suppression impossible",true)}finally{state.busy=false}}
async function logout(){if(state.busy)return;if(!confirm("Se déconnecter du compte ?"))return;state.busy=true;try{await call(ACCESS,"logout")}catch{}try{localStorage.removeItem(STORE)}catch{}location.replace("index.html")}
window.addEventListener("hashchange",render);
load();
})();