(()=>{'use strict';
const API='https://yzsrmuxghlengnkyphxj.supabase.co/functions/v1/stip-data',STORE='stip_session_v1',$=s=>document.querySelector(s),MONTHS=['JANVIER','FÉVRIER','MARS','AVRIL','MAI','JUIN','JUILLET','AOÛT','SEPTEMBRE','OCTOBRE','NOVEMBRE','DÉCEMBRE'],DAYS=['LUNDI','MARDI','MERCREDI','JEUDI','VENDREDI','SAMEDI','DIMANCHE'],FALLBACK={M:'#1688d3',J:'#20a765',J4:'#f2763e',S:'#dea72d',N:'#6e55d8',RH:'#748594',RTT:'#748594',RTTA:'#748594',RC:'#748594',CA:'#748594',RF:'#748594',AA:'#748594',MA:'#748594',RTA:'#748594',SYR:'#748594'};
let items=[],monthKey='',shiftAssets={},availableMonths=[],currentKind='personal',loadingData=null;
async function call(action){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','X-STIP-Session':localStorage.getItem(STORE)||''},body:JSON.stringify({action})}),j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw Error(j.error||`Erreur ${r.status}`);return j}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function todayMonth(){const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function validItem(x){return /^\d{4}-\d{2}-\d{2}$/.test(String(x?.date||''))&&!!String(x?.code||x?.source_value||'').trim()}
function buildAvailable(){availableMonths=[...new Set(items.filter(validItem).map(x=>String(x.date).slice(0,7)))].sort()}
function chooseMonth(){const cur=todayMonth();if(!monthKey||!availableMonths.includes(monthKey))monthKey=availableMonths.includes(cur)?cur:(availableMonths.find(k=>k>cur)||availableMonths.at(-1)||cur)}
function asset(code){const k=String(code||'').trim().toUpperCase();return shiftAssets[k]||shiftAssets[`${k}.PNG`]||shiftAssets[`${k}.JPG`]||shiftAssets[`${k}.JPEG`]||''}
function shiftVisual(code){if(!code)return'';const url=asset(code);if(url)return`<img class="ph-shift-img" src="${esc(url)}" alt="${esc(code)}">`;return`<span class="ph-shift-fallback" style="--shift:${FALLBACK[code]||'#277b86'}">${esc(code)}</span>`}
function monthPanel(k){const[y,m]=k.split('-').map(Number),by=new Map(items.filter(x=>String(x.date||'').startsWith(k)).map(x=>[x.date,x])),first=new Date(y,m-1,1),days=new Date(y,m,0).getDate(),pad=(first.getDay()+6)%7,today=new Date().toISOString().slice(0,10),idx=availableMonths.indexOf(k);let cells=DAYS.map((d,i)=>`<span class="ph-day-head ${i>4?'weekend':''}">${d}</span>`).join('')+'<span class="ph-empty"></span>'.repeat(pad);for(let i=1;i<=days;i++){const dk=`${k}-${String(i).padStart(2,'0')}`,it=by.get(dk),code=String(it?.code||it?.source_value||'').trim().toUpperCase(),dow=new Date(`${dk}T12:00:00`).getDay(),weekend=dow===0||dow===6;cells+=`<div class="ph-day-cell ${dk===today?'today':''} ${weekend?'weekend':''}"><b>${i}</b><div class="ph-shift-slot">${shiftVisual(code)}</div></div>`}return`<div class="ph-month-card"><header><button type="button" data-month-nav="-1" aria-label="Mois précédent" ${idx<=0?'disabled':''}>‹</button><div class="ph-month-title"><span><strong>${MONTHS[m-1]}</strong><small>${y}</small></span></div><button type="button" data-month-nav="1" aria-label="Mois suivant" ${idx<0||idx>=availableMonths.length-1?'disabled':''}>›</button></header><div class="ph-month-grid">${cells}</div></div>`}
function announceMonth(){window.dispatchEvent(new CustomEvent('stip:month-changed',{detail:{monthKey,months:[...availableMonths]}}))}
function renderPersonal(){const c=$('#phContent');if(!c)return;chooseMonth();c.innerHTML=monthPanel(monthKey);announceMonth();window.dispatchEvent(new CustomEvent('stip:planning-select',{detail:{kind:'personal'}}))}
function renderCalendar(){const c=$('#phContent');if(!c)return;c.innerHTML=`<div class="ph-dedicated-intro"><span>CALENDRIER NATIF</span><h2>Mon agenda</h2><p>Garde ton planning STIP synchronisé avec le calendrier de ton téléphone. Les abonnements restent à jour lorsque le planning change.</p></div><div class="ph-calendar-cards"><button type="button" data-open-calendar><b>▦</b><span><strong>Choisir mes calendriers</strong><small>Planning perso, équipe, formations ou stagiaires</small></span><em>›</em></button><div class="ph-info-card"><strong>Mise à jour automatique</strong><small>Pas besoin de retélécharger le calendrier après une modification du planning.</small></div></div>`;c.querySelector('[data-open-calendar]')?.addEventListener('click',()=>window.STIPCalendars?.open?.());window.dispatchEvent(new CustomEvent('stip:planning-select',{detail:{kind:'calendar'}}))}
function pageMeta(kind){if(kind==='team')return['PLANNING','Planning équipe','Qui travaille aujourd’hui et sur les prochains jours'];if(kind==='change')return['PLANNING','Changement','Échange ou demande de modification'];if(kind==='calendar')return['MON STIP','Mon agenda','Synchronisation calendrier'];return['MON STIP','Planning perso','Mes horaires et mes repères']}
function shell(){const root=$('#planningView');if(!root)return;const [eyebrow,title,sub]=pageMeta(currentKind);root.innerHTML=`<div class="ph-shell"><div class="ph-head"><button class="ph-back" type="button" aria-label="Retour">‹</button><div><span>${eyebrow}</span><h1>${title}</h1><small>${sub}</small></div></div><section class="ph-context" id="phContext"></section><section class="ph-content" id="phContent"><div class="ph-page-load">Chargement…</div></section></div>`;root.querySelector('.ph-back')?.addEventListener('click',()=>window.STIPRouter?.back?.('home'))}
function routeKind(r){if(r==='planning/team'||r==='planning/spirit')return'team';if(r==='planning/change')return'change';if(r==='planning/calendar')return'calendar';return'personal'}
async function ensureData(){if(items.length)return true;const cached=window.STIPBootCache;if(cached?.personal?.length){applyData(cached,false);return true}if(!loadingData)loadingData=call('bootstrap').finally(()=>loadingData=null);try{const d=await loadingData;window.STIPBootCache=d;applyData(d,false);return true}catch(e){const c=$('#phContent');if(c)c.innerHTML=`<div class="ph-error">${esc(e.message)}</div>`;return false}}
function applyData(d,rerender=true){if(!d)return false;items=d.personal||d.items||[];shiftAssets=d.media?.shifts||shiftAssets||{};buildAvailable();chooseMonth();if(rerender&&currentKind==='personal')renderPersonal();return true}
async function openRoute(r){currentKind=routeKind(r);shell();window.dispatchEvent(new CustomEvent('stip:planning-page',{detail:{kind:currentKind}}));if(currentKind==='personal'){if(await ensureData())renderPersonal();return}if(currentKind==='team'){const c=$('#phContent');if(c)c.innerHTML='<div class="ph-page-load">Chargement de l’équipe…</div>';requestAnimationFrame(()=>window.dispatchEvent(new CustomEvent('stip:planning-select',{detail:{kind:'spirit'}})));return}if(currentKind==='change'){const c=$('#phContent');if(c)c.innerHTML='<div class="ph-page-load">Chargement des changements…</div>';requestAnimationFrame(()=>window.dispatchEvent(new CustomEvent('stip:planning-select',{detail:{kind:'change'}})));return}renderCalendar()}
function moveMonth(step){const i=availableMonths.indexOf(monthKey),n=i+Number(step);if(i<0||n<0||n>=availableMonths.length)return;monthKey=availableMonths[n];renderPersonal()}
window.addEventListener('stip:route',e=>{const r=e.detail?.route||'';if(r==='planning'||r.startsWith('planning/'))openRoute(r)});
window.addEventListener('stip:boot-updated',e=>applyData(e.detail||window.STIPBootCache,currentKind==='personal'));
document.addEventListener('click',e=>{const b=e.target.closest?.('[data-month-nav]');if(!b||b.disabled)return;moveMonth(Number(b.dataset.monthNav))});
setTimeout(()=>{const r=window.STIPRouter?.get?.()||'';if(r==='planning'||r.startsWith('planning/'))openRoute(r)},30);
window.STIPPlanningMonth={get key(){return monthKey},get months(){return[...availableMonths]},move:moveMonth};
})();