(()=>{'use strict';
const API='https://yzsrmuxghlengnkyphxj.supabase.co/functions/v1/stip-access',STORE='stip_session_v1';
let input=null,dialog=null,busy=false,pending=null;
const allowed=()=>window.STIPSession?.permissions?.profile_photo===true;
const current=()=>window.STIPSession?.agent?.profile_photo_url||window.STIPBootCache?.agent?.profile_photo_url||'';
async function call(action,body={}){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','X-STIP-Session':localStorage.getItem(STORE)||''},body:JSON.stringify({action,...body})}),j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw Error(j.error||`Erreur ${r.status}`);return j}
function syncProfileUrl(url=''){if(window.STIPSession?.agent)window.STIPSession.agent.profile_photo_url=url;if(window.STIPBootCache?.agent)window.STIPBootCache.agent.profile_photo_url=url}
function ensureInput(){if(input)return input;input=document.createElement('input');input.type='file';input.accept='image/*';input.hidden=true;input.addEventListener('change',async()=>{const file=input.files?.[0];input.value='';if(!file||busy)return;busy=true;try{pending=await prepare(file);showPreview()}catch(e){toast(e.message||'Impossible de préparer la photo',true);showMenu()}finally{busy=false}});document.body.appendChild(input);return input}
function ensureDialog(){if(dialog)return dialog;dialog=document.createElement('div');dialog.id='profilePhotoDialog';dialog.hidden=true;dialog.setAttribute('role','dialog');dialog.setAttribute('aria-modal','true');dialog.addEventListener('click',e=>{if(e.target===dialog)closeDialog()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!dialog.hidden)closeDialog()});document.body.appendChild(dialog);return dialog}
function shell(title,text,body){const d=ensureDialog();d.innerHTML=`<section class="profile-photo-sheet"><div class="profile-photo-handle"></div><h2>${title}</h2><p>${text}</p>${body}</section>`;d.hidden=false}
function closeDialog(){if(dialog)dialog.hidden=true;pending=null}
function showMenu(){if(!allowed()||busy)return;const del=current()?'<button type="button" class="danger" data-photo-delete>Supprimer ma photo</button>':'';shell('Photo de profil','Que veux-tu faire ?',`<div class="profile-photo-actions"><button type="button" class="primary" data-photo-choose>Choisir une photo</button>${del}<button type="button" data-photo-cancel>Annuler</button></div>`);dialog.querySelector('[data-photo-choose]').onclick=()=>{dialog.hidden=true;ensureInput().click()};dialog.querySelector('[data-photo-delete]')?.addEventListener('click',showDeleteConfirm);dialog.querySelector('[data-photo-cancel]').onclick=closeDialog}
function showPreview(){if(!pending)return;const src=`data:image/webp;base64,${pending.base64}`;shell('Aperçu','La photo est recadrée automatiquement au format portrait. Vérifie le cadrage avant de l’enregistrer.',`<div class="profile-photo-preview"><img src="${src}" alt="Aperçu de la photo"></div><div class="profile-photo-actions"><button type="button" class="primary" data-photo-save>Utiliser cette photo</button><button type="button" data-photo-other>Choisir une autre</button><button type="button" data-photo-cancel>Annuler</button></div>`);dialog.querySelector('[data-photo-save]').onclick=savePending;dialog.querySelector('[data-photo-other]').onclick=()=>{dialog.hidden=true;ensureInput().click()};dialog.querySelector('[data-photo-cancel]').onclick=closeDialog}
function showDeleteConfirm(){shell('Supprimer la photo ?','La photo personnalisée sera retirée. L’avatar par défaut sera réutilisé.',`<div class="profile-photo-actions"><button type="button" class="danger" data-photo-delete-confirm>Supprimer la photo</button><button type="button" data-photo-back>Retour</button></div>`);dialog.querySelector('[data-photo-delete-confirm]').onclick=deletePhoto;dialog.querySelector('[data-photo-back]').onclick=showMenu}
async function savePending(){if(!pending||busy)return;busy=true;const base64=pending.base64;try{const r=await call('profile_photo_set',{base64});syncProfileUrl(r.profile_photo_url||'');paint();closeDialog();toast('Photo mise à jour')}catch(e){toast(e.message||'Impossible de modifier la photo',true)}finally{busy=false}}
async function deletePhoto(){if(busy)return;busy=true;try{await call('profile_photo_delete');syncProfileUrl('');paint();closeDialog();toast('Photo supprimée')}catch(e){toast(e.message||'Impossible de supprimer la photo',true)}finally{busy=false}}
async function prepare(file){if(!file.type.startsWith('image/'))throw Error('Choisis une image.');const bmp=await createImageBitmap(file),targetRatio=4/5,srcRatio=bmp.width/bmp.height;let sx=0,sy=0,sw=bmp.width,sh=bmp.height;if(srcRatio>targetRatio){sw=bmp.height*targetRatio;sx=(bmp.width-sw)/2}else{sh=bmp.width/targetRatio;sy=(bmp.height-sh)/2}const canvas=document.createElement('canvas');canvas.width=320;canvas.height=400;const ctx=canvas.getContext('2d');ctx.fillStyle='#eef5f7';ctx.fillRect(0,0,320,400);ctx.drawImage(bmp,sx,sy,sw,sh,0,0,320,400);bmp.close?.();const blob=await new Promise((res,rej)=>canvas.toBlob(b=>b?res(b):rej(Error('Conversion impossible.')),'image/webp',.82));if(blob.size>350000)throw Error('Photo trop volumineuse.');const base64=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result).split(',')[1]||'');r.onerror=()=>rej(Error('Lecture impossible.'));r.readAsDataURL(blob)});return{base64}}
function paint(){const custom=current();document.querySelectorAll('.hc-avatar').forEach(a=>{const fallback=a.dataset.defaultAvatar||'',initials=a.dataset.initials||'',url=custom||fallback;a.classList.toggle('profile-photo-enabled',allowed());a.setAttribute('aria-label',allowed()?'Modifier ma photo de profil':'Avatar');a.setAttribute('role',allowed()?'button':'img');a.tabIndex=allowed()?0:-1;if(url){let img=a.querySelector('img');if(!img){a.innerHTML='<img alt="">';img=a.querySelector('img')}if(img&&img.src!==url)img.src=url}else if(!a.querySelector('span')||a.textContent!==initials){a.innerHTML=`<span>${initials}</span>`}a.title=allowed()?'Modifier ma photo':''})}
function toast(t,err=false){let x=document.querySelector('#profilePhotoToast');if(!x){x=document.createElement('div');x.id='profilePhotoToast';document.body.appendChild(x)}x.textContent=t;x.className=err?'error show':'show';clearTimeout(x._t);x._t=setTimeout(()=>x.className='',1800)}
document.addEventListener('click',e=>{const a=e.target.closest?.('.hc-avatar');if(a&&allowed()){e.preventDefault();showMenu()}},true);
document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target?.matches?.('.hc-avatar')&&allowed()){e.preventDefault();showMenu()}});
let raf=0;function schedule(){if(raf)return;raf=requestAnimationFrame(()=>{raf=0;paint()})}
['stip:session-ready','stip:boot-updated','stip:route','stip:home-rendered'].forEach(e=>window.addEventListener(e,schedule));window.addEventListener('pageshow',schedule);schedule();
window.STIPProfilePhoto={open:showMenu,refresh:paint};
})();