(()=>{'use strict';
const API='https://yzsrmuxghlengnkyphxj.supabase.co/functions/v1/stip-access',STORE='stip_session_v1';let input=null,busy=false;
const allowed=()=>window.STIPSession?.permissions?.profile_photo===true;
const current=()=>window.STIPSession?.agent?.profile_photo_url||'';
async function call(action,body={}){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','X-STIP-Session':localStorage.getItem(STORE)||''},body:JSON.stringify({action,...body})}),j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw Error(j.error||`Erreur ${r.status}`);return j}
function ensureInput(){if(input)return input;input=document.createElement('input');input.type='file';input.accept='image/*';input.hidden=true;input.addEventListener('change',async()=>{const f=input.files?.[0];input.value='';if(!f||busy)return;busy=true;try{const base64=await compress(f),r=await call('profile_photo_set',{base64});if(window.STIPSession?.agent)window.STIPSession.agent.profile_photo_url=r.profile_photo_url||'';paint();toast('Photo mise à jour')}catch(e){toast(e.message||'Impossible de modifier la photo',true)}finally{busy=false}});document.body.appendChild(input);return input}
async function compress(file){if(!file.type.startsWith('image/'))throw Error('Choisis une image.');const bmp=await createImageBitmap(file),side=Math.min(bmp.width,bmp.height),sx=(bmp.width-side)/2,sy=(bmp.height-side)/2,c=document.createElement('canvas');c.width=c.height=320;const x=c.getContext('2d');x.drawImage(bmp,sx,sy,side,side,0,0,320,320);bmp.close?.();const blob=await new Promise((res,rej)=>c.toBlob(b=>b?res(b):rej(Error('Conversion impossible.')),'image/webp',.78));if(blob.size>350000)throw Error('Photo trop volumineuse.');return await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result).split(',')[1]||'');r.onerror=()=>rej(Error('Lecture impossible.'));r.readAsDataURL(blob)})}
function paint(){const url=current();document.querySelectorAll('.hc-avatar').forEach(a=>{a.classList.toggle('profile-photo-enabled',allowed());a.setAttribute('aria-label',allowed()?'Modifier ma photo de profil':'Avatar');a.setAttribute('role',allowed()?'button':'img');a.tabIndex=allowed()?0:-1;if(url){let img=a.querySelector('img');if(!img){a.innerHTML='<img alt="">';img=a.querySelector('img')}if(img&&img.src!==url)img.src=url}a.title=allowed()?'Modifier ma photo':''})}
function choose(){if(!allowed()||busy)return;ensureInput().click()}
function toast(t,err=false){let x=document.querySelector('#profilePhotoToast');if(!x){x=document.createElement('div');x.id='profilePhotoToast';document.body.appendChild(x)}x.textContent=t;x.className=err?'error show':'show';clearTimeout(x._t);x._t=setTimeout(()=>x.className='',1800)}
document.addEventListener('click',e=>{const a=e.target.closest?.('.hc-avatar');if(a&&allowed()){e.preventDefault();choose()}},true);document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target?.matches?.('.hc-avatar')&&allowed()){e.preventDefault();choose()}});
let raf=0;function schedule(){if(raf)return;raf=requestAnimationFrame(()=>{raf=0;paint()})}['stip:session-ready','stip:boot-updated','stip:route'].forEach(e=>window.addEventListener(e,schedule));window.addEventListener('pageshow',schedule);
const st=document.createElement('style');st.textContent=`.hc-avatar.profile-photo-enabled{cursor:pointer;position:relative}.hc-avatar.profile-photo-enabled:after{content:'✎';position:absolute;right:-2px;bottom:-2px;width:22px;height:22px;border-radius:50%;display:grid;place-items:center;background:#fff;border:1px solid #d7e5e8;color:#176075;font-size:12px;font-weight:900;box-shadow:0 2px 8px rgba(0,0,0,.12)}#profilePhotoToast{position:fixed;left:50%;bottom:calc(24px + env(safe-area-inset-bottom));transform:translateX(-50%) translateY(10px);z-index:2200;max-width:86vw;padding:10px 13px;border-radius:12px;background:#153f4e;color:#fff;font-size:.74rem;font-weight:800;opacity:0;pointer-events:none;transition:.18s}#profilePhotoToast.show{opacity:1;transform:translateX(-50%) translateY(0)}#profilePhotoToast.error{background:#7a2e35}`;document.head.appendChild(st);schedule()})();