(()=>{'use strict';
const CODE_STORE='stip_access_code_v1',USAGE_STORE='stip_app_usage_v1',FAV_STORE='stip_app_favorites_v1',PENDING_STORE='stip_pending_app_v1',$=s=>document.querySelector(s);
const I={home:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3.5 10.5 12 3l8.5 7.5"/><path d="M5.5 9.5V21h13V9.5M9.5 21v-6h5v6"/></svg>',profile:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="4" width="18" height="16" rx="3"/><circle cx="9" cy="10" r="2.5"/><path d="M5.8 17c.6-2.3 1.8-3.5 3.2-3.5s2.7 1.2 3.2 3.5M15 9h3M15 13h3"/></svg>',fav:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m12 3 2.7 5.5 6.1.9-4.4 4.3 1 6.1-5.4-2.9-5.4 2.9 1-6.1-4.4-4.3 6.1-.9z"/></svg>'};
const META={personal:{label:'Planning perso',open:()=>window.STIPHubs?.planning?.('personal')},team:{label:'Planning équipe',open:()=>window.STIPHubs?.planning?.('spirit')},compare:{label:'Comparer les plannings',open:()=>location.href='planning-compare-app.html'},change:{label:'Changement',open:()=>window.STIPHubs?.planning?.('change')},calendar:{label:'Mon agenda',open:()=>{window.STIPHubs?.planning?.('personal');setTimeout(()=>window.dispatchEvent(new CustomEvent('stip:planning-quick-action',{detail:{action:'calendar',scope:'personal'}})),80)}},contacts:{label:'Contacts',open:()=>window.STIPHubs?.contacts?.()},places:{label:'Visiter les lieux',open:()=>location.href='places-app.html'},responsable:{label:'Responsable',open:()=>location.href='responsable.html'},assistant:{label:'Assistant STIP',open:()=>location.href='assistant.html'},activity:{label:'Activité',open:()=>location.href='cadre-activite.html'},access:{label:'Accès',open:()=>location.href='access-manage.html'},newagent:{label:'Nouvel agent',open:()=>location.href='https://esapin69.github.io/Ghe-interne/'},upload:{label:'Importer',open:()=>location.href='https://admin-ghe.esapin.com/depot.html'},admin:{label:'Admin',open:()=>location.href='https://admin-ghe.esapin.com/'}};
let publicPreview=false,lastTouch={key:'',at:0};
function allowed(k){if(!META[k])return false;if(window.STIPAccess?.app)return !!window.STIPAccess.app(k);const p=window.STIPSession?.permissions||{},map={personal:'planning_personal',team:'planning_team',compare:'planning_team',change:'change_app',calendar:'calendar_subscribe',contacts:'contacts',places:'places',responsable:'responsable',assistant:'assistant_enabled',activity:'activity',access:'access_manage',newagent:'nouveaux_arrivants',upload:'file_upload',admin:'admin'};return !!p[map[k]]}
function readUsage(){try{return JSON.parse(localStorage.getItem(USAGE_STORE)||'{}')||{}}catch{return{}}}function writeUsage(v){try{localStorage.setItem(USAGE_STORE,JSON.stringify(v))}catch{}}
function readFav(){try{const x=JSON.parse(localStorage.getItem(FAV_STORE)||'[]');return Array.isArray(x)?x.filter(k=>META[k]):[]}catch{return[]}}function writeFav(v){try{localStorage.setItem(FAV_STORE,JSON.stringify([...new Set(v)].filter(k=>META[k])))}catch{}}
function touch(key){if(!allowed(key))return;const now=Date.now();if(lastTouch.key===key&&now-lastTouch.at<1800)return;lastTouch={key,at:now};const u=readUsage(),apps=u.apps||{},prev=Number(u.at||now),days=Math.max(0,(now-prev)/86400000),decay=Math.pow(.985,days);Object.keys(apps).forEach(k=>apps[k]=Math.max(0,Number(apps[k]||0)*decay));apps[key]=Number(apps[key]||0)+1;writeUsage({at:now,last:key,apps})}
function suggestions(){const pinned=new Set(readFav().filter(allowed)),scores=readUsage().apps||{};return Object.keys(META).filter(k=>allowed(k)&&!pinned.has(k)).sort((a,b)=>Number(scores[b]||0)-Number(scores[a]||0)||META[a].label.localeCompare(META[b].label,'fr')).slice(0,3)}
function routeKey(route){route=String(route||'');if(route.startsWith('planning/personal'))return'personal';if(route.startsWith('planning/team')||route.startsWith('planning/spirit'))return'team';if(route.startsWith('planning/change'))return'change';if(route.startsWith('planning/calendar'))return'calendar';if(route.startsWith('contacts'))return'contacts';return''}
function formatCode(v){const d=String(v||'').replace(/\D/g,'').slice(0,6);return d.length>3?`${d.slice(0,3)} • ${d.slice(3)}`:d}function prepareCode(){const i=$('#accessCode');if(!i)return;const saved=String(localStorage.getItem(CODE_STORE)||'').replace(/\D/g,'').slice(0,6);i.removeAttribute('pattern');i.maxLength=9;i.classList.add('stip-code-visible');if(saved&&!String(i.value||'').replace(/\D/g,'')){i.value=formatCode(saved);i.type='text';if($('#toggleAccessCode'))$('#toggleAccessCode').textContent='Masquer'}i.addEventListener('input',()=>{const d=String(i.value||'').replace(/\D/g,'').slice(0,6);i.value=formatCode(d)},{passive:true})}function saveCode(){const i=$('#accessCode'),d=String(i?.value||'').replace(/\D/g,'').slice(0,6);if(d.length===6)try{localStorage.setItem(CODE_STORE,d)}catch{}}
function nav(){let n=$('#stipQuickSwitch');if(n)return n;n=document.createElement('nav');n.id='stipQuickSwitch';n.className='stip-quick-switch';n.setAttribute('aria-label','Navigation STIP');n.innerHTML=`<button type="button" data-qs="public" aria-label="Accueil STIP"><span class="qs-icon">${I.home}</span></button><button type="button" data-qs="profile" aria-label="Mon espace"><span class="qs-icon">${I.profile}</span></button><button type="button" data-qs="favorites" aria-label="Applications favorites"><span class="qs-icon">${I.fav}</span></button>`;n.addEventListener('click',e=>{const b=e.target.closest?.('[data-qs]');if(!b)return;const a=b.dataset.qs;if(a==='public')return showPublic();if(a==='profile')return showProfile();if(a==='favorites')return toggleFavorites()});return n}
function closeFavorites(){document.getElementById('stipFavoritesPanel')?.remove();document.body.classList.remove('stip-favorites-open')}
function favRow(k,pinned){return `<div class="stip-fav-row"><button type="button" class="stip-fav-open" data-fav-open="${k}"><span>${META[k].label}</span><b>›</b></button><button type="button" class="stip-fav-pin ${pinned?'is-pinned':''}" data-fav-pin="${k}" aria-label="${pinned?'Retirer des favoris':'Épingler'}">${pinned?'★':'☆'}</button></div>`}
function toggleFavorites(){if(document.getElementById('stipFavoritesPanel'))return closeFavorites();const pinned=readFav().filter(allowed),suggest=suggestions(),all=Object.keys(META).filter(allowed),p=document.createElement('section');p.id='stipFavoritesPanel';p.className='stip-favorites-panel';p.innerHTML=`<button type="button" class="stip-fav-backdrop" aria-label="Fermer"></button><div class="stip-fav-sheet"><header><div><small>ACCÈS RAPIDE</small><h2>Applications favorites</h2></div><button type="button" class="stip-fav-close" aria-label="Fermer">×</button></header>${pinned.length?`<section><h3>Épinglées</h3><div>${pinned.map(k=>favRow(k,true)).join('')}</div></section>`:''}<section><h3>${pinned.length?'Suggestions':'Suggestions selon votre usage'}</h3><div>${suggest.length?suggest.map(k=>favRow(k,false)).join(''):'<p class="stip-fav-empty">Utilisez vos applications : vos raccourcis apparaîtront ici.</p>'}</div></section><details><summary>Choisir une autre application</summary><div class="stip-fav-all">${all.map(k=>favRow(k,pinned.includes(k))).join('')}</div></details></div>`;document.body.appendChild(p);document.body.classList.add('stip-favorites-open');p.querySelector('.stip-fav-backdrop').onclick=closeFavorites;p.querySelector('.stip-fav-close').onclick=closeFavorites;p.addEventListener('click',e=>{const o=e.target.closest('[data-fav-open]'),pin=e.target.closest('[data-fav-pin]');if(o){const k=o.dataset.favOpen;closeFavorites();openKey(k);return}if(pin){const k=pin.dataset.favPin,a=readFav();writeFav(a.includes(k)?a.filter(x=>x!==k):[...a,k]);closeFavorites();toggleFavorites()}})}
function syncMode(){const connected=!!window.STIPSession;document.body.classList.toggle('stip-quick-in-app',connected&&!publicPreview);document.body.classList.toggle('stip-public-preview',connected&&publicPreview);document.body.classList.toggle('stip-quick-connected',connected)}function mount(){const existing=$('#stipQuickSwitch');if(!window.STIPSession){existing?.remove();closeFavorites();syncMode();return}const n=nav();if(n.parentElement!==document.body)document.body.appendChild(n);syncMode();refreshState()}
function refreshState(){const n=$('#stipQuickSwitch');if(!n)return;const session=!!window.STIPSession;n.querySelector('[data-qs="profile"]').classList.toggle('is-current',session&&!publicPreview&&(window.STIPRouter?.get?.()||'home')==='home');n.querySelector('[data-qs="public"]').classList.toggle('is-current',publicPreview);n.querySelector('[data-qs="favorites"]').classList.toggle('is-current',!!document.getElementById('stipFavoritesPanel'))}
function requireSession(key=''){if(window.STIPSession)return true;if(key)try{sessionStorage.setItem(PENDING_STORE,key)}catch{}return false}function showPublic(){if(!window.STIPSession)return;closeFavorites();publicPreview=true;$('#appView')?.classList.add('hidden');$('#loginView')?.classList.remove('hidden');mount();window.scrollTo({top:0,behavior:'auto'})}function showProfile(){if(!requireSession())return;closeFavorites();publicPreview=false;$('#loginView')?.classList.add('hidden');$('#appView')?.classList.remove('hidden');window.STIPRouter?.set?.('home');mount();window.scrollTo({top:0,behavior:'auto'})}
function openKey(key){if(!key||!allowed(key)||!requireSession(key))return;closeFavorites();publicPreview=false;$('#loginView')?.classList.add('hidden');$('#appView')?.classList.remove('hidden');touch(key);mount();META[key].open()}
document.addEventListener('click',e=>{const b=e.target.closest?.('.hc-app[data-app]');if(b&&allowed(b.dataset.app))touch(b.dataset.app)},true);window.addEventListener('stip:route',e=>{const k=routeKey(e.detail?.route);if(k)touch(k);if(window.STIPSession&&!publicPreview)mount()});window.addEventListener('stip:login-success',()=>saveCode());window.addEventListener('stip:session-ready',()=>{const q=new URLSearchParams(location.search).get('quick')||'';publicPreview=q==='public';mount();if(q){history.replaceState(null,'',location.pathname+location.hash);setTimeout(()=>{if(q==='public')showPublic();else if(q==='profile')showProfile();else if(allowed(q))openKey(q)},40);return}let k='';try{k=sessionStorage.getItem(PENDING_STORE)||'';sessionStorage.removeItem(PENDING_STORE)}catch{}if(k&&allowed(k))setTimeout(()=>openKey(k),60)});window.addEventListener('stip:session-ended',()=>{publicPreview=false;mount()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeFavorites()});prepareCode();mount();
})();