(()=>{'use strict';
const CODE_STORE='stip_access_code_v1',USAGE_STORE='stip_app_usage_v1',PENDING_STORE='stip_pending_app_v1',$=s=>document.querySelector(s);
const META={personal:{label:'Planning perso',open:()=>window.STIPHubs?.planning?.('personal')},team:{label:'Planning équipe',open:()=>window.STIPHubs?.planning?.('spirit')},change:{label:'Changement',open:()=>window.STIPHubs?.planning?.('change')},calendar:{label:'Mon agenda',open:()=>{window.STIPHubs?.planning?.('personal');setTimeout(()=>window.dispatchEvent(new CustomEvent('stip:planning-quick-action',{detail:{action:'calendar',scope:'personal'}})),80)}},contacts:{label:'Contacts',open:()=>window.STIPHubs?.contacts?.()},responsable:{label:'Responsable',open:()=>location.href='responsable.html'},newagent:{label:'Nouvel agent',open:()=>location.href='https://esapin69.github.io/Ghe-interne/'},upload:{label:'Importer',open:()=>location.href='https://admin-ghe.esapin.com/depot.html'},admin:{label:'Admin',open:()=>location.href='https://admin-ghe.esapin.com/'}};
let publicPreview=false,lastTouch={key:'',at:0};
function readUsage(){try{return JSON.parse(localStorage.getItem(USAGE_STORE)||'{}')||{}}catch{return{}}}
function writeUsage(v){try{localStorage.setItem(USAGE_STORE,JSON.stringify(v))}catch{}}
function touch(key){if(!META[key])return;const now=Date.now();if(lastTouch.key===key&&now-lastTouch.at<1800)return;lastTouch={key,at:now};const u=readUsage(),apps=u.apps||{},prev=Number(u.at||now),days=Math.max(0,(now-prev)/86400000),decay=Math.pow(.985,days);Object.keys(apps).forEach(k=>apps[k]=Math.max(0,Number(apps[k]||0)*decay));apps[key]=(Number(apps[key]||0)+1);writeUsage({at:now,last:key,apps});refreshLabels()}
function favoriteKey(){const u=readUsage(),apps=u.apps||{};return Object.keys(apps).filter(k=>META[k]).sort((a,b)=>Number(apps[b]||0)-Number(apps[a]||0))[0]||''}
function lastKey(){const k=readUsage().last||'';return META[k]?k:''}
function routeKey(route){route=String(route||'');if(route.startsWith('planning/personal'))return'personal';if(route.startsWith('planning/team')||route.startsWith('planning/spirit'))return'team';if(route.startsWith('planning/change'))return'change';if(route.startsWith('planning/calendar'))return'calendar';if(route.startsWith('contacts'))return'contacts';return''}
function appShortcutKey(){const current=routeKey(window.STIPRouter?.get?.()||'');return current||lastKey()}
function formatCode(v){const d=String(v||'').replace(/\D/g,'').slice(0,6);return d.length>3?`${d.slice(0,3)} • ${d.slice(3)}`:d}
function prepareCode(){const i=$('#accessCode');if(!i)return;const saved=String(localStorage.getItem(CODE_STORE)||'').replace(/\D/g,'').slice(0,6);i.removeAttribute('pattern');i.maxLength=9;i.classList.add('stip-code-visible');if(saved&&!String(i.value||'').replace(/\D/g,'')){i.value=formatCode(saved);i.type='text';if($('#toggleAccessCode'))$('#toggleAccessCode').textContent='Masquer'}i.addEventListener('input',()=>{const d=String(i.value||'').replace(/\D/g,'').slice(0,6);i.value=formatCode(d)},{passive:true})}
function saveCode(){const i=$('#accessCode'),d=String(i?.value||'').replace(/\D/g,'').slice(0,6);if(d.length===6)try{localStorage.setItem(CODE_STORE,d)}catch{}}
function nav(){let n=$('#stipQuickSwitch');if(n)return n;n=document.createElement('nav');n.id='stipQuickSwitch';n.className='stip-quick-switch';n.setAttribute('aria-label','Accès rapides STIP');n.innerHTML='<button type="button" data-qs="public" aria-label="Accueil STIP"><span class="qs-icon">⌂</span><small>PH1</small><strong>Accueil</strong></button><button type="button" data-qs="profile" aria-label="Ma fiche"><span class="qs-icon">◉</span><small>PH2</small><strong>Ma fiche</strong></button><button type="button" data-qs="favorite" aria-label="Application favorite"><span class="qs-icon">★</span><small>Favori</small><strong>À apprendre</strong></button><button type="button" data-qs="last" aria-label="Dernière application"><span class="qs-icon">↶</span><small>Dernière app</small><strong>Aucune</strong></button>';n.addEventListener('click',e=>{const b=e.target.closest?.('[data-qs]');if(!b||b.disabled)return;const a=b.dataset.qs;if(a==='public')return showPublic();if(a==='profile')return showProfile();if(a==='favorite')return openKey(favoriteKey());if(a==='last')return openKey(appShortcutKey())});return n}
function syncMode(){const connected=!!window.STIPSession;document.body.classList.toggle('stip-quick-in-app',connected&&!publicPreview);document.body.classList.toggle('stip-public-preview',connected&&publicPreview);document.body.classList.toggle('stip-quick-connected',connected)}
function mount(){const existing=$('#stipQuickSwitch');if(!window.STIPSession){existing?.remove();syncMode();return}const n=nav(),app=$('#appView');if(publicPreview){const h=$('.public-home h1');if(h&&n.parentElement!==document.body)document.body.appendChild(n)}else if(app&&n.parentElement!==document.body){document.body.appendChild(n)}syncMode();refreshLabels()}
function refreshLabels(){const n=$('#stipQuickSwitch');if(!n)return;const f=favoriteKey(),l=appShortcutKey(),current=routeKey(window.STIPRouter?.get?.()||''),session=!!window.STIPSession;n.querySelector('[data-qs="favorite"] strong').textContent=f?META[f].label:'À apprendre';n.querySelector('[data-qs="last"] strong').textContent=l?META[l].label:'Aucune';n.querySelector('[data-qs="favorite"]').disabled=!f;n.querySelector('[data-qs="last"]').disabled=!l;n.querySelector('[data-qs="last"]').classList.toggle('is-current',!!current&&current===l&&!publicPreview);n.querySelector('[data-qs="profile"]').classList.toggle('is-current',session&&!publicPreview&&(window.STIPRouter?.get?.()||'home')==='home');n.querySelector('[data-qs="public"]').classList.toggle('is-current',publicPreview)}
function requireSession(key=''){if(window.STIPSession)return true;if(key)try{sessionStorage.setItem(PENDING_STORE,key)}catch{}return false}
function showPublic(){if(!window.STIPSession)return;publicPreview=true;$('#appView')?.classList.add('hidden');$('#loginView')?.classList.remove('hidden');mount();window.scrollTo({top:0,behavior:'auto'})}
function showProfile(){if(!requireSession())return;publicPreview=false;$('#loginView')?.classList.add('hidden');$('#appView')?.classList.remove('hidden');window.STIPRouter?.set?.('home');mount();window.scrollTo({top:0,behavior:'auto'})}
function openKey(key){if(!key||!META[key]||!requireSession(key))return;publicPreview=false;$('#loginView')?.classList.add('hidden');$('#appView')?.classList.remove('hidden');touch(key);mount();META[key].open()}
document.addEventListener('click',e=>{const b=e.target.closest?.('.hc-app[data-app]');if(b)touch(b.dataset.app)},true);
window.addEventListener('stip:route',e=>{const k=routeKey(e.detail?.route);if(k)touch(k);if(window.STIPSession&&!publicPreview)mount()});
window.addEventListener('stip:login-success',()=>saveCode());
window.addEventListener('stip:session-ready',()=>{publicPreview=false;mount();let k='';try{k=sessionStorage.getItem(PENDING_STORE)||'';sessionStorage.removeItem(PENDING_STORE)}catch{}if(k&&META[k])setTimeout(()=>openKey(k),100)});
window.addEventListener('stip:session-ended',()=>{publicPreview=false;mount()});
prepareCode();mount();
})();