(()=>{
'use strict';
const ROOT='https://yzsrmuxghlengnkyphxj.supabase.co/functions/v1';
const ONB=ROOT+'/stip-onboarding',EVAL=ROOT+'/stip-evaluations',STORE='stip_session_v1';
const params=new URLSearchParams(location.search);let currentCase=params.get('case')||'',currentAgent=params.get('agent')||'',caseDetail=null,bootCache=null;
const authState={user:null};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));}
function q(name){return document.querySelector(name)}
function setStatus(el,type,message){if(!el)return;el.className='status show '+type;el.textContent=String(message||'')}
function formObject(form){return Object.fromEntries(new FormData(form).entries())}
function displayDate(iso){if(!iso)return'—';const m=String(iso).match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[3]}/${m[2]}/${m[1]}`:String(iso)}
function token(){return localStorage.getItem(STORE)||''}
function displayName(a){if(!a)return'';if(a.prenom&&a.nom)return `${a.prenom} ${a.nom}`.trim();const key=String(a.source_key||'').trim();if(key.includes('_'))return key.split('_').filter(Boolean).reverse().map(x=>x.toUpperCase()).join(' ');return String(a.nom||a.prenom||'Agent').trim()}
function readableError(raw,status){if(!raw)return`Service indisponible (${status||'erreur'}).`;if(typeof raw==='string')return raw==='[object Object]'?'Le service a renvoyé une réponse invalide. Réessayez.':raw;if(typeof raw.message==='string')return raw.message;if(typeof raw.error==='string')return raw.error;try{return JSON.stringify(raw)}catch{return'Service momentanément indisponible.'}}
async function call(url,action,body={}){const t=token();if(!t)throw Object.assign(new Error('Session STIP requise.'),{status:401});let r;try{r=await fetch(url,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json','X-STIP-Session':t},body:JSON.stringify({action,...body})})}catch(_){throw new Error('Connexion au service impossible. Vérifiez le réseau puis réessayez.')}const raw=await r.text();let j={};try{j=raw?JSON.parse(raw):{}}catch{throw Object.assign(new Error(`Réponse serveur invalide (${r.status}).`),{status:r.status})}if(!r.ok||j.error){const e=Object.assign(new Error(readableError(j.error||j,r.status)),{status:r.status,code:j.error});throw e}return j}
const onb=(a,b={})=>call(ONB,a,b),eva=(a,b={})=>call(EVAL,a,b);
async function bootstrap(force=false){if(bootCache&&!force)return bootCache;bootCache=await onb('bootstrap');if(!bootCache.permissions?.responsable||!bootCache.manager?.can_evaluate)throw Object.assign(new Error('Accès Responsable requis pour les évaluations.'),{status:403});authState.user={...bootCache.agent,display_name:displayName(bootCache.agent)};return bootCache}
function renderAuthControls(){if(document.body.classList.contains('responsable-home-page'))return;const header=document.querySelector('.top');if(!header||header.querySelector('.auth-controls')||!authState.user)return;const box=document.createElement('div');box.className='auth-controls';box.innerHTML=`<span class="auth-identity">${esc(authState.user.display_name)}</span><a class="auth-logout" href="index.html" style="text-decoration:none">Accueil STIP</a>`;header.appendChild(box)}
const GHE_AUTH_READY=(async()=>{try{await bootstrap();document.documentElement.classList.remove('auth-pending');document.documentElement.classList.add('auth-ready');renderAuthControls();return authState.user}catch(e){document.documentElement.classList.remove('auth-pending');document.documentElement.classList.add('auth-error');if(e?.status===401)location.replace('index.html');throw e}})();
async function caseInfo(){if(caseDetail)return caseDetail;if(currentCase){try{const r=await onb('case_detail',{case_id:currentCase});caseDetail=r.case;currentAgent=caseDetail.agent?.id||currentAgent;return caseDetail}catch(e){if(!currentAgent)currentAgent=currentCase}}if(currentAgent){const r=await eva('state',{agent_id:currentAgent});caseDetail={id:null,agent:r.agent||{id:currentAgent},profile_data:{},arrival_date:null,verification_status:null,experience_text:null};return caseDetail}throw new Error('Agent non sélectionné.')}
const AgentContext={get id(){return currentAgent||caseDetail?.agent?.id||''},async load(){await GHE_AUTH_READY;const c=await caseInfo(),a={...(c.agent||{})};const p=c.profile_data&&typeof c.profile_data==='object'?c.profile_data:{};a.telephone=p.telephone??p.legacy_phone??a.telephone??'';a.matricule=p.matricule??p.legacy_matricule??'';a.experiences=c.experience_text??p.experiences??'';a.date_arrivee=c.arrival_date||'';a.verification=c.verification_status||'';document.querySelectorAll('[data-agent-name]').forEach(x=>x.textContent=window.STIPName?.format?.(a)||displayName(a));document.querySelectorAll('[data-agent-meta]').forEach(x=>x.textContent=a.matricule?`Matricule ${a.matricule}`:'');document.querySelectorAll('[data-agent-link]').forEach(x=>x.href='responsable.html?open=evaluation');const s=q('#contextStatus');if(s)s.className='status';return a},preserveLinks(){document.querySelectorAll('[data-agent-link]').forEach(x=>x.href='responsable.html?open=evaluation')}};
function target(){return currentAgent?{agent_id:currentAgent}:currentCase?{case_id:currentCase}:{} }
async function apiGet(action,p={}){await GHE_AUTH_READY;if(action==='listEvaluations'){const r=await eva('state',target());return{evaluations:[r.live,r.previous].filter(Boolean),...r}}if(action==='getEvaluation')return eva('state',target());if(action==='getAgent'){await caseInfo();return{agent:await AgentContext.load()}}if(action==='listDirectory'){const r=await eva('search_agents',{query:''});return{agents:(r.items||[]).map(a=>({...a,poste:a.role||''}))}}throw new Error('Action non disponible.')}
async function apiPost(action,p={}){await GHE_AUTH_READY;if(action==='saveEvaluationDraft')return eva('save_live',{...p,...target()});if(action==='finalizeEvaluation')return eva('finalize',{...p,...target()});throw new Error('Action non disponible.')}
async function searchAgents(query=''){await GHE_AUTH_READY;const r=await eva('search_agents',{query});return r.items||[]}
async function ensureCase(agentId){return agentId}
function openAgentEvaluation(agentId){location.href=`responsable-evaluations.html?agent=${encodeURIComponent(agentId)}`;return Promise.resolve(agentId)}
window.GHEAuth={ready:GHE_AUTH_READY,get user(){return authState.user},hasAccess:key=>Boolean(bootCache?.permissions?.[key])};window.AgentContext=AgentContext;window.apiGet=apiGet;window.apiPost=apiPost;window.esc=esc;window.q=q;window.setStatus=setStatus;window.formObject=formObject;window.displayDate=displayDate;window.GHEBase={bootstrap,searchAgents,ensureCase,openAgentEvaluation,displayName,onb,eva};
})();