(()=>{'use strict';
const API='https://yzsrmuxghlengnkyphxj.supabase.co/functions/v1/stip-actions',STORE='stip_session_v1',$=s=>document.querySelector(s);let mode='direct',agents=[],items=[],proposals=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function call(action,body={}){const r=await fetch(API,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json','X-STIP-Session':localStorage.getItem(STORE)||''},body:JSON.stringify({action,...body})}),j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw Object.assign(Error(j.error||`Erreur ${r.status}`),{status:r.status});return j}
function person(a){if(!a)return'Agent';if(a.prenom)return`${String(a.prenom).toLocaleUpperCase('fr-FR')} ${String(a.nom||'').toLocaleLowerCase('fr-FR')}`.trim();const p=String(a.source_key||'').split('_').filter(Boolean);if(p.length>1)return`${p.at(-1).toLocaleUpperCase('fr-FR')} ${p.slice(0,-1).join(' ').toLocaleLowerCase('fr-FR')}`;const w=String(a.nom||'').trim().split(/\s+/).filter(Boolean);return w.length>1?`${w.at(-1).toLocaleUpperCase('fr-FR')} ${w.slice(0,-1).join(' ').toLocaleLowerCase('fr-FR')}`:String(a.nom||'Agent')}
function fmtDate(d){return d?new Date(d+'T12:00:00').toLocaleDateString('fr-FR',{weekday:'short',day:'numeric',month:'short'}).replace('.',''):'—'}
function setMode(v){mode=v;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===v));document.querySelectorAll('.ag-schedule').forEach(x=>x.classList.toggle('hidden',v==='notify'));const submit=$('#agSubmit');submit.classList.toggle('notify',v==='notify');submit.textContent=v==='direct'?'Ajouter à son agenda':v==='proposal'?'Envoyer la proposition':'Envoyer la notification';syncPlacement()}
function syncPlacement(){if(mode==='notify')return;const note=$('#agDisplay').value==='day_note',all=note||$('#agAllDay').checked;$('#agAllDayWrap').classList.toggle('hidden',note);$('#agStartWrap').classList.toggle('hidden',all);$('#agEndWrap').classList.toggle('hidden',all)}
function renderAgents(){const sel=$('#agAgent'),sorted=agents.slice().sort((a,b)=>person(a).localeCompare(person(b),'fr'));sel.innerHTML='<option value="">Choisir un agent…</option>'+sorted.map(a=>`<option value="${esc(a.id)}">${esc(person(a))}${a.ghe?` · ${esc(a.ghe)}`:''}</option>`).join('')}
function itemCard(x,proposal=false){const a=x.agent||x.target||agents.find(z=>z.id===(x.agent_id||x.target_agent_id)),g=proposal?x.metadata?.agenda:x,all=g?.all_day,note=g?.display_mode==='day_note',time=note?'Description du jour':all?'Toute la journée':[String(g?.start_time||'').slice(0,5),String(g?.end_time||'').slice(0,5)].filter(Boolean).join('–');return`<article class="ag-item"><div class="ag-item-icon">${proposal?'➕':note?'📝':all?'📅':'⏱️'}</div><div><strong>${esc(g?.title||String(x.title||'').replace(/^📅\s*/,''))}</strong><small>${esc(person(a))} · ${esc(fmtDate(g?.event_date))}${time?` · ${esc(time)}`:''}${g?.location?` · ${esc(g.location)}`:''}${proposal?' · En attente':''}</small></div>${proposal?'':`<button type="button" data-cancel="${esc(x.id)}" aria-label="Retirer">×</button>`}</article>`}
function renderList(){const all=[...proposals.map(x=>({x,proposal:true})),...items.map(x=>({x,proposal:false}))].sort((a,b)=>String((a.proposal?a.x.metadata?.agenda?.event_date:a.x.event_date)||'').localeCompare(String((b.proposal?b.x.metadata?.agenda?.event_date:b.x.event_date)||'')));$('#agCount').textContent=all.length?`${all.length} élément${all.length>1?'s':''}`:'';$('#agList').innerHTML=all.length?all.map(z=>itemCard(z.x,z.proposal)).join(''):'<div class="ag-empty">Aucun élément manuel à venir.</div>';document.querySelectorAll('[data-cancel]').forEach(b=>b.addEventListener('click',()=>cancelItem(b.dataset.cancel)))}
async function load(){try{const [ar,ir,pr]=await Promise.all([call('manager_agents'),call('manager_agenda_list'),call('manager_list')]);agents=ar.agents||[];items=ir.items||[];proposals=(pr.actions||[]).filter(x=>x.kind==='agenda_proposal');renderAgents();renderList()}catch(e){if(e.status===401||e.status===403){location.replace('index.html');return}$('#agFeedback').textContent=e.message;$('#agList').innerHTML=`<div class="ag-empty">${esc(e.message)}</div>`}}
function payload(){const p={target_agent_id:$('#agAgent').value,title:$('#agTitle').value.trim(),body:$('#agBody').value.trim()};if(mode==='notify')return p;const note=$('#agDisplay').value==='day_note';return{...p,event_date:$('#agDate').value,display_mode:note?'day_note':'event',all_day:note?true:$('#agAllDay').checked,start_time:note||$('#agAllDay').checked?null:$('#agStart').value,end_time:note||$('#agAllDay').checked?null:$('#agEnd').value,location:$('#agLocation').value.trim(),importance:$('#agImportance').value}}
async function submit(e){e.preventDefault();const f=$('#agFeedback'),b=$('#agSubmit'),p=payload();if(!p.target_agent_id||!p.title){f.textContent='Choisis un agent et renseigne un titre.';return}if(mode!=='notify'&&!p.event_date){f.textContent='Choisis une date.';return}if(mode!=='notify'&&!p.all_day&&p.display_mode==='event'&&(!p.start_time||!p.end_time)){f.textContent='Renseigne l’heure de début et de fin.';return}b.disabled=true;f.textContent=mode==='notify'?'Envoi…':mode==='proposal'?'Proposition…':'Ajout…';try{if(mode==='notify')await call('send_notification',p);else if(mode==='proposal')await call('agenda_propose',p);else await call('agenda_direct',p);f.textContent=mode==='notify'?'✓ Notification envoyée. Elle disparaîtra quand l’agent appuiera sur OK.':mode==='proposal'?'✓ Proposition envoyée à l’agent.':'✓ Ajouté au planning personnel.';$('#agTitle').value='';$('#agBody').value='';$('#agLocation').value='';await load()}catch(e){f.textContent=e.message}finally{b.disabled=false}}
async function cancelItem(id){if(!confirm('Retirer cet élément du planning ?'))return;try{await call('manager_agenda_cancel',{id});await load()}catch(e){alert(e.message)}}
function init(){if(!localStorage.getItem(STORE)){location.replace('index.html');return}$('#agBack').onclick=()=>location.href='responsable.html';document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('#agDisplay').onchange=syncPlacement;$('#agAllDay').onchange=syncPlacement;$('#agForm').onsubmit=submit;const d=new Date(Date.now()+86400000),local=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);$('#agDate').value=local;setMode('direct');load()}
init();
})();