(()=>{'use strict';
const API='https://yzsrmuxghlengnkyphxj.supabase.co/functions/v1/stip-agent-readonly',STORE='stip_session_v1';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const SHIFT={M:{label:'Matin',time:'06h50 – 14h40',c:'#1688d3'},J:{label:'Journée',time:'08h30 – 16h20',c:'#20a765'},J4:{label:'J4',time:'10h10 – 18h00',c:'#f2763e'},S:{label:'Soir',time:'13h30 – 21h00',c:'#dea72d'},N:{label:'Nuit',time:'21h00 – 06h50',c:'#6e55d8'}};
const ABS_ORDER=['AR','AT','MA','CA','RH','RTT','RTa','RTTA','RC','AA','RF','SYR'];
const btn=$('[data-resp-agents]');if(!btn)return;
let directory=null,query='';
async function call(action,body={}){const r=await fetch(API,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json','X-STIP-Session':localStorage.getItem(STORE)||''},body:JSON.stringify({action,...body})}),j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw Error(j.error||`Erreur ${r.status}`);return j}
function displayName(a){return window.GHEBase?.displayName?.(a)||[a?.prenom,a?.nom].filter(Boolean).join(' ')||'Agent'}
function initials(a){const parts=displayName(a).trim().split(/\s+/).filter(Boolean);return((parts[0]?.[0]||'')+(parts.at(-1)?.[0]||'')).toUpperCase()||'ST'}
function norm(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('fr-FR')}
function baseShift(code){const c=String(code||'').toUpperCase();return SHIFT[c]?c:(c.endsWith('*')&&SHIFT[c.slice(0,-1)]?c.slice(0,-1):null)}
function isWorking(a){return !!baseShift(a.today_code)}
function isBrancardier(a){return !/^chef/i.test(String(a.type_planning||a.equipe||''))&&!/chef|cadre/i.test(String(a.role||''))}
function avatar(a){const u=String(a.avatar_url||'');return`<span class="ra-avatar">${/^https?:/i.test(u)?`<img src="${esc(u)}" alt="">`:esc(initials(a))}</span>`}
function row(a){const code=String(a.today_code||'').toUpperCase(),base=baseShift(code),m=base&&SHIFT[base];const status=m?`${code} · ${m.time}`:(code?`Absent · ${code}`:'Absent · motif non renseigné');const meta=[status,a.ghe?`GHE ${a.ghe}`:''].filter(Boolean).join(' · ');return`<button class="ra-person" type="button" data-agent="${esc(a.id)}">${avatar(a)}<span class="ra-person-copy"><b>${esc(displayName(a))}</b><small>${esc(meta)}</small></span>${m?`<i class="ra-dot" style="--dot:${m.c}"></i>`:`<span class="ra-code">${esc(code||'—')}</span>`}<em>›</em></button>`}
function sectionShift(code,items){if(!items.length)return'';const m=SHIFT[code];return`<section class="ra-group ra-work-group" style="--group:${m.c}"><header><div><b>${code}</b><span>${m.label}<small>${m.time}</small></span></div><strong>${items.length}</strong></header><div>${items.map(row).join('')}</div></section>`}
function absenceTitle(code){return code||'Sans motif'}
function sectionAbsence(code,items,index){if(!items.length)return'';return`<details class="ra-absence-group" ${index===0?'open':''}><summary><span><b>${esc(absenceTitle(code))}</b><small>Non présents aujourd’hui</small></span><strong>${items.length}</strong></summary><div>${items.map(row).join('')}</div></details>`}
function searchResults(items){const q=norm(query.trim());if(q.length<2)return'';const found=items.filter(a=>norm([displayName(a),a.source_key,a.ghe,a.today_code].filter(Boolean).join(' ')).includes(q)).sort((a,b)=>displayName(a).localeCompare(displayName(b),'fr'));return`<section class="ra-search-results"><header><span>RÉSULTATS</span><b>${found.length}</b></header>${found.length?found.map(row).join(''):'<p>Aucun brancardier trouvé.</p>'}</section>`}
function render(){const body=$('#respPanelBody');if(!body||!directory)return;const all=(directory.items||[]).filter(isBrancardier),working=all.filter(isWorking),absent=all.filter(a=>!isWorking(a));const d=new Date(`${directory.date}T12:00:00`),dateLabel=d.toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'});const workHtml=Object.keys(SHIFT).map(code=>sectionShift(code,working.filter(a=>baseShift(a.today_code)===code).sort((a,b)=>displayName(a).localeCompare(displayName(b),'fr')))).join('');const codes=[...new Set(absent.map(a=>String(a.today_code||'')))].sort((a,b)=>{const ai=ABS_ORDER.indexOf(a),bi=ABS_ORDER.indexOf(b);if(ai!==-1||bi!==-1)return(ai===-1?999:ai)-(bi===-1?999:bi);return a.localeCompare(b,'fr')});const absHtml=codes.map((code,i)=>sectionAbsence(code,absent.filter(a=>String(a.today_code||'')===code).sort((a,b)=>displayName(a).localeCompare(displayName(b),'fr')),i)).join('');const searching=query.trim().length>=2;$('#respPanelTitle').textContent='Brancardiers';body.innerHTML=`<main class="ra-day"><header class="ra-day-head"><span>ÉQUIPE · AUJOURD’HUI</span><h1>${esc(dateLabel)}</h1><p><b>${working.length}</b> au travail <i>·</i> <b>${absent.length}</b> non présents</p></header><label class="ra-search"><span>⌕</span><input id="raSearch" type="search" autocomplete="off" spellcheck="false" value="${esc(query)}" placeholder="Rechercher un brancardier · dès 2 lettres"><button id="raSearchClear" type="button" ${query?'':'hidden'}>×</button></label>${searching?searchResults(all):`<section class="ra-present"><div class="ra-section-title"><span>EN POSTE</span><b>${working.length}</b></div>${workHtml||'<p class="ra-empty">Aucun brancardier en poste aujourd’hui.</p>'}</section><section class="ra-absent"><div class="ra-section-title"><span>NON PRÉSENTS</span><b>${absent.length}</b></div>${absHtml||'<p class="ra-empty">Aucune absence aujourd’hui.</p>'}</section>`}</main>`;wire()}
function wire(){const input=$('#raSearch');input?.addEventListener('input',e=>{query=e.target.value;render();requestAnimationFrame(()=>{const n=$('#raSearch');n?.focus();try{n?.setSelectionRange(query.length,query.length)}catch{}})});$('#raSearchClear')?.addEventListener('click',()=>{query='';render();requestAnimationFrame(()=>$('#raSearch')?.focus())});$$('[data-agent]').forEach(x=>x.onclick=()=>{const id=x.dataset.agent;if(id)location.href=`index.html?view_agent=${encodeURIComponent(id)}&readonly=1`})}
async function openPanel(){const panel=$('#respPanel');panel.classList.add('open','ra-native-panel');panel.setAttribute('aria-hidden','false');$('#respPanelTitle').textContent='Brancardiers';$('#respPanelBody').innerHTML='<div class="ra-load"><i></i><b>Lecture du planning du jour…</b></div>';query='';try{directory=await call('directory');render()}catch(e){$('#respPanelBody').innerHTML=`<div class="ra-error"><b>Impossible de charger l’équipe</b><span>${esc(e.message)}</span></div>`}}
btn.addEventListener('click',openPanel);
})();