(()=>{
'use strict';
const ROOT='https://yzsrmuxghlengnkyphxj.supabase.co/functions/v1';
const ONB=ROOT+'/stip-onboarding',EVAL=ROOT+'/stip-evaluations',STORE='stip_session_v1';
const params=new URLSearchParams(location.search);let currentCase=params.get('case')||'',currentAgent=params.get('agent')||'',caseDetail=null,bootCache=null;
const authState={user:null};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));}
function q(name){return document.querySelector(name)}
function setStatus(el,type,message){if(!el)return;el.className='status show '+type;el.innerHTML=message}
function formObject(form){return Object.fromEntries(new FormData(form).entries())}
function displayDate(iso){if(!iso)return'—';const m=String(iso).match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[3]}/${m[2]}/${m[1]}`:String(iso)}
function token(){return localStorage.getItem(STORE)||''}
function displayName(a){if(!a)return'';if(a.prenom&&a.nom)return `${a.prenom} ${a.nom}`.trim();const key=String(a.source_key||'').trim();if(key.includes('_'))return key.split('_').filter(Boolean).reverse().map(x=>x.toUpperCase()).join(' ');return String(a.nom||a.prenom||'Agent').trim()}
async function call(url,action,body={}){const t=token();if(!t)throw Object.assign(new Error('SESSION_STIP_REQUISE'),{status:401});let r;try{r=await fetch(url,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json','X-STIP-Session':t},body:JSON.stringify({action,...body})})}catch(_){throw new Error('Connexion au service impossible. Vérifiez le réseau puis réessayez.')}const j=await r.json().catch(()=>({}));if(!r.ok||j.error){const raw=j.error||`Erreur ${r.status}`,msg=typeof raw==='string'?raw:(raw?.message||JSON.stringify(raw));const e=Object.assign(new Error(msg),{status:r.status,code:j.error});throw e}return j}
const onb=(a,b={})=>call(ONB,a,b),eva=(a,b={})=>call(EVAL,a,b);
async function bootstrap(force=false){if(bootCache&&!force)return bootCache;bootCache=await onb('bootstrap');if(!bootCache.permissions?.responsable||!bootCache.manager?.can_evaluate)throw Object.assign(new Error('ACCES_EVALUATION_REQUIS'),{status:403});authState.user={...bootCache.agent,display_name:displayName(bootCache.agent)};return bootCache}
function renderAuthControls(){if(document.body.classList.contains('responsable-home-page'))return;const header=document.querySelector('.top');if(!header||header.querySelector('.auth-controls')||!authState.user)return;const box=document.createElement('div');box.className='auth-controls';box.innerHTML=`<span class="auth-identity">${esc(authState.user.display_name)}</span><a class="auth-logout" href="index.html" style="text-decoration:none">Accueil STIP</a>`;header.appendChild(box)}
const GHE_AUTH_READY=(async()=>{try{await bootstrap();document.documentElement.classList.remove('auth-pending');document.documentElement.classList.add('auth-ready');renderAuthControls();return authState.user}catch(e){document.documentElement.classList.remove('auth-pending');document.documentElement.classList.add('auth-error');if(e?.status===401)location.replace('index.html');throw e}})();
async function caseInfo(){if(caseDetail)return caseDetail;if(!currentCase)throw new Error('Agent non sélectionné.');const r=await onb('case_detail',{case_id:currentCase});caseDetail=r.case;currentAgent=caseDetail.agent?.id||currentAgent;return caseDetail}
const AgentContext={get id(){return currentAgent||caseDetail?.agent?.id||''},async load(){await GHE_AUTH_READY;const c=await caseInfo(),a={...(c.agent||{})};const p=c.profile_data&&typeof c.profile_data==='object'?c.profile_data:{};a.telephone=p.telephone??p.legacy_phone??a.telephone??'';a.matricule=p.matricule??p.legacy_matricule??'';a.experiences=c.experience_text??p.experiences??'';a.date_arrivee=c.arrival_date||'';a.verification=c.verification_status||'';document.querySelectorAll('[data-agent-name]').forEach(x=>x.textContent=displayName(a));document.querySelectorAll('[data-agent-meta]').forEach(x=>x.textContent=a.matricule?`Matricule ${a.matricule}`:'Sans matricule renseigné');document.querySelectorAll('[data-agent-link]').forEach(x=>x.href='responsable-evaluation-agents.html');const s=q('#contextStatus');if(s)s.className='status';return a},preserveLinks(){document.querySelectorAll('[data-agent-link]').forEach(x=>x.href='responsable-evaluation-agents.html')}};
async function apiGet(action,p={}){await GHE_AUTH_READY;if(action==='listEvaluations')return eva('list',{case_id:currentCase});if(action==='getEvaluation')return eva('get',{id_evaluation:p.id});if(action==='getAgentSignatureStatus')return eva('getAgentSignatureStatus',{id_evaluation:p.id});if(action==='getAgent'){const c=await caseInfo();return{agent:await AgentContext.load()}}if(action==='listDirectory'){const r=await onb('agent_search_all',{query:''});return{agents:(r.items||[]).map(a=>({...a,poste:a.role||''}))}}throw new Error('ACTION_INVALIDE')}
async function apiPost(action,p={}){await GHE_AUTH_READY;if(action==='saveEvaluationDraft')return eva('saveEvaluationDraft',{...p,case_id:currentCase});if(action==='finalizeEvaluation')return eva('finalizeEvaluation',{...p,case_id:currentCase});if(action==='createAgentSignatureRequest')return eva('createAgentSignatureRequest',p);if(action==='cancelAgentSignatureRequest')return eva('cancelAgentSignatureRequest',p);throw new Error('ACTION_INVALIDE')}
async function searchAgents(query=''){await GHE_AUTH_READY;const r=await onb('agent_search_all',{query});return r.items||[]}
function allKnownCases(b){const out=[];for(const c of b.managed_cases||[])out.push(c);if(b.own_case)out.push(b.own_case);return out}
async function ensureCase(agentId){let b=await bootstrap();let found=allKnownCases(b).find(c=>c.agent_id===agentId||c.agent?.id===agentId);if(found)return found.id;try{const r=await onb('case_create',{agent_id:agentId});bootCache=null;return r.case.id}catch(e){if(String(e.message).includes('DOSSIER_DEJA_EXISTANT')){b=await bootstrap(true);found=allKnownCases(b).find(c=>c.agent_id===agentId||c.agent?.id===agentId);if(found)return found.id}throw e}}
function openAgentEvaluation(agentId){return ensureCase(agentId).then(caseId=>{location.href=`responsable-evaluations.html?case=${encodeURIComponent(caseId)}&agent=${encodeURIComponent(agentId)}`})}
window.GHEAuth={ready:GHE_AUTH_READY,get user(){return authState.user},hasAccess:key=>Boolean(bootCache?.permissions?.[key])};window.AgentContext=AgentContext;window.apiGet=apiGet;window.apiPost=apiPost;window.esc=esc;window.q=q;window.setStatus=setStatus;window.formObject=formObject;window.displayDate=displayDate;window.GHEBase={bootstrap,searchAgents,ensureCase,openAgentEvaluation,displayName,onb,eva};
})();