(()=>{'use strict';
const API='https://yzsrmuxghlengnkyphxj.supabase.co/functions/v1/stip-agent-readonly',DATA='https://yzsrmuxghlengnkyphxj.supabase.co/functions/v1/stip-data',STORE='stip_session_v1';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const SHIFT={M:{label:'Matin',time:'06h50 – 14h40',c:'#1688d3'},J:{label:'Journée',time:'08h30 – 16h20',c:'#20a765'},J4:{label:'J4',time:'10h10 – 18h00',c:'#f2763e'},S:{label:'Soir',time:'13h30 – 21h00',c:'#dea72d'},N:{label:'Nuit',time:'21h00 – 06h50',c:'#6e55d8'}},WORK=Object.keys(SHIFT),btn=$('[data-resp-agents]');if(!btn)return;
const ICON={personal:'▦',team:'♟',change:'⇄',calendar:'#',contacts:'☎',responsable:'◎',newagent:'↗',upload:'▤',admin:'⚙'};
let directory=null,mode='today',filter='ALL',query='',current=null;
async function call(url,action,body={}){const r=await fetch(url,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json','X-STIP-Session':localStorage.getItem(STORE)||''},body:JSON.stringify({action,...body})}),j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw Error(j.error||`Erreur ${r.status}`);return j}
const ro=(action,body={})=>call(API,action,body),data=(action,body={})=>call(DATA,action,body);
function name(a){return window.GHEBase?.displayName?.(a)||[a?.prenom,a?.nom].filter(Boolean).join(' ')||'Agent'}
function ini(a){return`${String(a?.prenom||'')[0]||''}${String(a?.nom||'')[0]||''}`.toUpperCase()||'ST'}
function can(v,k){return!!v?.[k]}
function openPanel(){const p=$('#respPanel');p.classList.add('open','ra-native-panel');p.setAttribute('aria-hidden','false');$('#respPanelTitle').textContent='Brancardiers';$('#respPanelBody').innerHTML='<div class="ra-load"><i></i><b>Chargement de l’équipe…</b></div>';mode='today';filter='ALL';query='';current=null;loadDirectory()}
async function loadDirectory(){try{directory=await ro('directory');renderDirectory()}catch(e){error(e.message)}}
function working(a){return WORK.includes(String(a.today_code||'').toUpperCase())}
function list(){let x=(directory?.items||[]).filter(a=>mode==='today'?working(a):!working(a));if(mode==='away'&&filter!=='ALL')x=x.filter(a=>String(a.usual_shift||'')===filter);const q=query.trim().toLocaleLowerCase('fr-FR');if(q.length>=2)x=x.filter(a=>name(a).toLocaleLowerCase('fr-FR').includes(q)||String(a.ghe||'').toLocaleLowerCase('fr-FR').includes(q));return x.sort((a,b)=>name(a).localeCompare(name(b),'fr'))}
function person(a){const m=SHIFT[String(a.today_code||'').toUpperCase()],sub=m?`${a.today_code} · ${m.time}${a.ghe?` · GHE ${a.ghe}`:''}`:[a.usual_shift?`Shift habituel ${a.usual_shift}`:'Non planifié aujourd’hui',a.ghe?`GHE ${a.ghe}`:''].filter(Boolean).join(' · ');return`<button class="ra-person" data-agent="${esc(a.id)}"><span class="ra-person-avatar">${esc(ini(a))}</span><span><b>${esc(name(a))}</b><small>${esc(sub)}</small></span><em>›</em></button>`}
function renderDirectory(){const b=$('#respPanelBody'),all=directory?.items||[],today=all.filter(working),away=all.filter(a=>!working(a)),items=list();$('#respPanelTitle').textContent='Brancardiers';b.innerHTML=`<main class="ra-directory"><header><span>ÉQUIPE</span><h1>Brancardiers</h1><p>${today.length} planifié${today.length>1?'s':''} aujourd’hui</p></header><div class="ra-tabs"><button data-mode="today" class="${mode==='today'?'on':''}">Aujourd’hui <b>${today.length}</b></button><button data-mode="away" class="${mode==='away'?'on':''}">Autres <b>${away.length}</b></button></div><label class="ra-search"><span>⌕</span><input id="raSearch" type="search" value="${esc(query)}" placeholder="Nom ou prénom · dès 2 lettres"></label>${mode==='away'?`<div class="ra-filters"><button data-filter="ALL" class="${filter==='ALL'?'on':''}">Tous</button>${WORK.map(c=>`<button data-filter="${c}" class="${filter===c?'on':''}" style="--c:${SHIFT[c].c}">${c}</button>`).join('')}</div>`:''}<section class="ra-list">${items.length?items.map(person).join(''):'<p class="ra-empty">Aucun agent dans ce filtre.</p>'}</section></main>`;wireDirectory()}
function wireDirectory(){const i=$('#raSearch');i?.addEventListener('input',e=>{query=e.target.value;renderDirectory();requestAnimationFrame(()=>{const n=$('#raSearch');n?.focus();try{n?.setSelectionRange(query.length,query.length)}catch{}})});$$('[data-mode]').forEach(x=>x.onclick=()=>{mode=x.dataset.mode;filter='ALL';query='';renderDirectory()});$$('[data-filter]').forEach(x=>x.onclick=()=>{filter=x.dataset.filter;renderDirectory()});$$('[data-agent]').forEach(x=>x.onclick=()=>openAgent(x.dataset.agent))}
function dayObj(s){return new Date(`${s}T12:00:00`)}
function iso(d){return d.toISOString().slice(0,10)}
function week(plan){const today=new Date(),dow=today.getDay()||7,start=new Date(today);start.setDate(today.getDate()-dow+1);const by=new Map(plan.map(x=>[x.date,String(x.code||x.source_value||'').toUpperCase()]));return Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);const k=iso(d);return{d,k,c:by.get(k)||'—',today:k===iso(today)}})}
function avatar(boot){const a=boot.agent,u=boot.media?.avatars?.[a.source_key]||'';return`<span class="ra-stip-avatar">${u?`<img src="${esc(u)}" alt="">`:esc(ini(a))}</span>`}
function locked(target,viewer,key){return !can(target,key)||!can(viewer,key)}
function app(target,viewer,key,title,sub,kind){const l=locked(target,viewer,key);return`<button class="ra-stip-app ${l?'locked':''}" data-vapp="${kind}" ${!can(target,key)?'data-target-hidden="1"':''}><span>${ICON[kind]||'•'}</span><b>${esc(title)}</b><small>${esc(sub)}</small>${l?'<i>🚫</i>':'<em>›</em>'}</button>`}
function homeApps(b){const t=b.target_permissions||{},v=b.viewer_permissions||{};let out='';if(can(t,'planning')){out+=app(t,v,'planning','Planning perso','Mes horaires','personal')+app(t,v,'planning','Planning équipe','Qui travaille','team')+app(t,v,'planning','Changement','Échanges et demandes','change')+app(t,v,'calendriers','Mon agenda','Calendriers','calendar')}if(can(t,'equipe_contacts'))out+=app(t,v,'equipe_contacts','Contacts','Annuaire GHE','contacts');if(can(t,'responsable'))out+=app(t,v,'responsable','Responsable','Suivi et outils','responsable');if(can(t,'nouveaux_arrivants'))out+=app(t,v,'nouveaux_arrivants','Nouvel agent','Parcours intégration','newagent');if(can(t,'file_upload'))out+=app(t,v,'file_upload','Importer','Fichiers','upload');if(can(t,'admin'))out+=app(t,v,'admin','Admin','Administration','admin');return out||'<p class="ra-empty">Aucun outil sur ce compte.</p>'}
function profileMeta(a){return`<div class="ra-stip-meta">${a.ghe?`<span><small>GHE</small><b>${esc(a.ghe)}</b></span>`:''}${a.telephone?`<span><small>TÉLÉPHONE</small><b>${esc(a.telephone)}</b></span>`:''}${a.email?`<span class="wide"><small>E-MAIL</small><b>${esc(a.email)}</b></span>`:''}</div>`}
function renderVirtualHome(){const b=current,$b=$('#respPanelBody'),a=b.agent,w=week(b.personal||[]);$('#respPanelTitle').textContent=name(a);$b.innerHTML=`<main class="ra-stip"><button class="ra-stip-exit" id="raBackTeam">‹ Brancardiers</button><header class="ra-stip-head"><div><h1>${esc(name(a))}</h1><p>${esc(a.equipe?`Équipe ${a.equipe}`:'Mon espace personnel')}</p></div><span class="ra-ro">LECTURE SEULE</span></header><section class="ra-stip-profile">${avatar(b)}<div><span>COMPTE DE L’AGENT</span><strong>${esc(name(a))}</strong><small>${esc([a.role||'Brancardier',a.ghe?`GHE ${a.ghe}`:''].filter(Boolean).join(' · '))}</small></div>${profileMeta(a)}</section><section class="ra-stip-week"><header><span>SEMAINE EN COURS</span><b>${new Date().toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'})}</b></header><div>${w.map(x=>{const m=SHIFT[x.c];return`<button class="${x.today?'today':''}" data-vday="${x.k}"><small>${x.d.toLocaleDateString('fr-FR',{weekday:'short'}).replace('.','')}</small><b>${x.d.getDate()}</b><em style="${m?`--c:${m.c}`:''}">${esc(x.c)}</em></button>`}).join('')}</div></section><section class="ra-stip-tools"><span>MES OUTILS</span><div>${homeApps(b)}</div></section></main>`;$('#raBackTeam').onclick=renderDirectory;$$('[data-vapp]').forEach(x=>x.onclick=()=>{if(x.classList.contains('locked'))return;openVirtual(x.dataset.vapp)});$$('[data-vday]').forEach(x=>x.onclick=()=>renderPersonal(x.dataset.vday))}
async function openAgent(id){$('#respPanelBody').innerHTML='<div class="ra-load"><i></i><b>Ouverture de son STIP…</b></div>';try{current=await ro('boot',{agent_id:id});renderVirtualHome()}catch(e){error(e.message)}}
function subHead(title,sub=''){return`<header class="ra-vhead"><button id="raVBack">‹</button><div><span>LECTURE SEULE</span><h1>${esc(title)}</h1>${sub?`<p>${esc(sub)}</p>`:''}</div></header>`}
function wireBack(){const x=$('#raVBack');if(x)x.onclick=renderVirtualHome}
function renderPersonal(focus=''){const b=current,a=b.agent,rows=b.personal||[],months=[...new Set(rows.map(x=>String(x.date).slice(0,7)))].sort(),today=focus||iso(new Date()),month=today.slice(0,7),items=rows.filter(x=>String(x.date).startsWith(month));$('#respPanelBody').innerHTML=`<main class="ra-vpage">${subHead('Planning perso',name(a))}<section class="ra-vplanning"><h2>${dayObj(month+'-01').toLocaleDateString('fr-FR',{month:'long',year:'numeric'})}</h2><div>${items.map(x=>{const c=String(x.code||x.source_value||'').toUpperCase(),m=SHIFT[c];return`<article class="${x.date===today?'today':''}"><time>${dayObj(x.date).toLocaleDateString('fr-FR',{weekday:'short',day:'numeric'})}</time><b style="${m?`--c:${m.c}`:''}">${esc(c||'—')}</b><span>${esc(m?.time||x.observation||'')}</span></article>`}).join('')||'<p class="ra-empty">Aucune donnée ce mois.</p>'}</div></section></main>`;wireBack()}
async function renderTeam(){const r=$('#respPanelBody');r.innerHTML=`<main class="ra-vpage">${subHead('Planning équipe',name(current.agent))}<div class="ra-load compact"><i></i></div></main>`;wireBack();try{const d=await ro('team',{agent_id:current.agent.id}),today=iso(new Date()),rows=WORK.map(c=>({c,items:(d.planning||[]).filter(x=>x.date===today&&String(x.code||'').toUpperCase()===c)}));r.innerHTML=`<main class="ra-vpage">${subHead('Planning équipe',`Aujourd’hui · ${name(current.agent)}`)}<section class="ra-team">${rows.map(o=>`<article style="--c:${SHIFT[o.c].c}"><header><b>${o.c}</b><span>${SHIFT[o.c].label} · ${SHIFT[o.c].time}</span><em>${o.items.length}</em></header>${o.items.length?`<div>${o.items.map(x=>`<p><strong>${esc(name(x.agents||{}))}</strong><small>${esc(x.agents?.ghe?`GHE ${x.agents.ghe}`:'')}</small></p>`).join('')}</div>`:''}</article>`).join('')}</section></main>`;wireBack()}catch(e){error(e.message)}}
async function renderContacts(){const r=$('#respPanelBody');r.innerHTML=`<main class="ra-vpage">${subHead('Contacts',name(current.agent))}<div class="ra-load compact"><i></i></div></main>`;wireBack();try{const d=await data('contacts'),people=d.people||[];r.innerHTML=`<main class="ra-vpage">${subHead('Contacts',name(current.agent))}<label class="ra-search"><span>⌕</span><input id="raContactSearch" placeholder="Rechercher"></label><section class="ra-contact-list" id="raContactList"></section></main>`;wireBack();const draw=q=>{$('#raContactList').innerHTML=people.filter(p=>!q||name(p).toLocaleLowerCase('fr-FR').includes(q)||String(p.ghe||'').toLowerCase().includes(q)).slice(0,100).map(p=>`<article><b>${esc(name(p))}</b><small>${esc([p.ghe,p.role_metier].filter(Boolean).join(' · '))}</small></article>`).join('')};draw('');$('#raContactSearch').oninput=e=>draw(e.target.value.trim().toLocaleLowerCase('fr-FR'))}catch(e){error(e.message)}}
function renderReadonly(title,text){$('#respPanelBody').innerHTML=`<main class="ra-vpage">${subHead(title,name(current.agent))}<section class="ra-readpage"><span>LECTURE SEULE</span><h2>${esc(title)}</h2><p>${esc(text)}</p><div>Les actions de création, validation, signature, envoi ou modification sont désactivées dans ce mode.</div></section></main>`;wireBack()}
function openVirtual(k){if(k==='personal')return renderPersonal();if(k==='team')return renderTeam();if(k==='contacts')return renderContacts();if(k==='change')return renderReadonly('Changement','Tu consultes cet outil comme l’agent, sans pouvoir envoyer ou modifier une demande.');if(k==='calendar')return renderReadonly('Mon agenda','Le calendrier de cet agent est visible comme repère, sans abonnement ni modification.');if(k==='responsable')return renderReadonly('Responsable','L’espace Responsable de cet agent est ouvert en consultation uniquement.');if(k==='newagent')return renderReadonly('Nouvel agent','Le parcours d’intégration reste consultable sans écriture.');if(k==='upload')return renderReadonly('Importer','Les documents sont visibles uniquement en consultation.');if(k==='admin')return renderReadonly('Admin','Les fonctions administratives restent visibles sans aucune action d’écriture.')}
function error(m){$('#respPanelBody').innerHTML=`<div class="ra-error"><b>Impossible d’afficher cette vue</b><span>${esc(m||'Erreur')}</span><button id="raErrBack">Retour</button></div>`;$('#raErrBack').onclick=()=>current?renderVirtualHome():renderDirectory()}
btn.addEventListener('click',openPanel);
})();