(()=>{'use strict';
const DATA='https://yzsrmuxghlengnkyphxj.supabase.co/functions/v1/stip-data',STORE='stip_session_v1',$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];let contactsCache=null,contactQuery='';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function call(action,body={}){const r=await fetch(DATA,{method:'POST',headers:{'Content-Type':'application/json','X-STIP-Session':localStorage.getItem(STORE)||''},body:JSON.stringify({action,...body})}),j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw Error(j.error||`Erreur ${r.status}`);return j}
function moduleButton(title){return[...document.querySelectorAll('#moduleGrid .module-card')].find(b=>b.querySelector('strong')?.textContent.trim()===title)}
function showPlanning(select='personal'){window.STIPRouter?.set('planning');window.STIPRouter?.show('planningView');setTimeout(()=>{window.dispatchEvent(new HashChangeEvent('hashchange'));let tries=0;const choose=()=>{const b=document.querySelector(`[data-ph-select="${select}"]`);if(b)return b.click();if(++tries<30)setTimeout(choose,50)};choose()},0)}
function ensureHub(){let v=$('#rubricHubView');if(v)return v;v=document.createElement('section');v.id='rubricHubView';v.className='view hidden rhub-view';v.innerHTML='<div class="rhub-shell"><div class="rhub-head"><button type="button" id="rhubBack">‹</button><div><span>MON STIP</span><h1 id="rhubTitle">Rubrique</h1></div></div><div class="rhub-carousel" id="rhubCarousel"><article class="rhub-slide"><div class="rhub-widget">Chargement…</div></article></div><div class="rhub-dots" id="rhubDots"></div><nav class="rhub-apps" id="rhubApps"></nav></div>';$('#appView')?.appendChild(v);$('#rhubBack',v).onclick=()=>{window.STIPRouter?.set('home');window.STIPRouter?.show('homeView')};return v}
function showHub(){const v=ensureHub();$$('.view').forEach(x=>x.classList.add('hidden'));v.classList.remove('hidden');window.scrollTo({top:0,behavior:'auto'})}
function dots(){const d=$('#rhubDots');if(d)d.innerHTML='<i class="active"></i>'}
function expand(action){return`<button type="button" class="rhub-expand" data-rhub-expand="${action}" aria-label="Agrandir">⛶</button>`}
function icon(kind,label,symbol){return`<button type="button" class="rhub-app" data-rhub-select="${kind}"><span class="rhub-icon ${kind}">${symbol}</span><strong>${label}</strong></button>`}
function tel(v){const d=String(v||'').replace(/\D/g,'');if(!d)return'';return d.startsWith('33')?`tel:+${d}`:d.startsWith('0')?`tel:+33${d.slice(1)}`:`tel:${d}`}
function personName(p){return[p.prenom,p.nom].filter(Boolean).join(' ').trim()||'Contact'}
function peopleRows(items){return items.map(p=>`<div class="rhub-row"><div><strong>${esc(personName(p))}</strong><small>${esc([p.ghe,p.role_metier].filter(Boolean).join(' · '))}</small></div><div class="rhub-actions">${p.telephone?`<a href="${esc(tel(p.telephone))}">Appeler</a>`:''}${p.email_pro?`<a href="mailto:${esc(p.email_pro)}">Mail</a>`:''}</div></div>`).join('')}
function serviceRows(items){return items.map(s=>`<div class="rhub-row"><div><strong>${esc(s.service||'Service')}</strong><small>${esc([s.site,s.remarque].filter(Boolean).join(' · '))}</small></div><div class="rhub-actions">${s.telephone_externe?`<a href="${esc(tel(s.telephone_externe))}">Appeler</a>`:''}</div></div>`).join('')}
function vcfRow(p){const nm=personName(p);return['BEGIN:VCARD','VERSION:3.0',`N:${String(p.nom||'').replace(/;/g,'')};${String(p.prenom||'').replace(/;/g,'')};;;`,`FN:${nm}`,p.role_metier?`TITLE:${p.role_metier}`:'',p.telephone?`TEL;TYPE=CELL:${String(p.telephone).replace(/[^+0-9]/g,'')}`:'',p.email_pro?`EMAIL;TYPE=WORK:${p.email_pro}`:'',p.ghe?`ORG:GHE;${p.ghe}`:'','END:VCARD'].filter(Boolean).join('\r\n')}
function exportContacts(){const people=contactsCache?.people||[],txt=people.map(vcfRow).join('\r\n')+'\r\n';if(!txt.trim())return;const blob=new Blob([txt],{type:'text/vcard;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Contacts-GHE.vcf';document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},700)}
function openContactsFull(filter='all'){const b=moduleButton('Équipe & contacts');if(!b)return;b.click();setTimeout(()=>document.querySelector(`#contactFilters [data-filter="${filter}"]`)?.click(),120)}
function renderContacts(kind='directory'){const c=$('#rhubCarousel');if(!c||!contactsCache)return;const people=contactsCache.people||[],services=contactsCache.services||[],chefs=people.filter(p=>p.categorie==='chef');let body='';if(kind==='directory'){const q=contactQuery.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),items=people.filter(p=>!q||JSON.stringify(p).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(q));body=`<div class="rhub-widget-top"><div><span class="rhub-eyebrow">ANNUAIRE</span><h2>Contacts GHE</h2></div>${expand('contacts-all')}</div><div class="rhub-search"><input id="rhubSearch" type="search" value="${esc(contactQuery)}" placeholder="Nom, GHE, rôle, numéro…"></div><div class="rhub-list">${peopleRows(items)||'<p>Aucun résultat.</p>'}</div>`}else if(kind==='services'){body=`<div class="rhub-widget-top"><div><span class="rhub-eyebrow">SERVICES</span><h2>Numéros utiles</h2></div>${expand('contacts-services')}</div><div class="rhub-list">${serviceRows(services)||'<p>Aucun service.</p>'}</div>`}else if(kind==='chiefs'){body=`<div class="rhub-widget-top"><div><span class="rhub-eyebrow">CHEFS</span><h2>Chefs d’équipe</h2></div>${expand('contacts-chiefs')}</div><div class="rhub-list">${peopleRows(chefs)||'<p>Aucun chef.</p>'}</div>`}else{body='<span class="rhub-eyebrow">PARTAGER</span><h2>Annuaire complet</h2><p>Créer le fichier vCard des contacts publiés dans STIP.</p><button type="button" class="rhub-primary" id="rhubExport">Créer le fichier .vcf</button>'}c.innerHTML=`<article class="rhub-slide"><div class="rhub-widget">${body}</div></article>`;dots();$$('[data-rhub-select]').forEach(x=>x.classList.toggle('selected',x.dataset.rhubSelect===kind));$('#rhubSearch')?.addEventListener('input',e=>{contactQuery=e.target.value;renderContacts('directory')});$('#rhubExport')?.addEventListener('click',exportContacts)}
async function openContactsHub(kind='directory'){showHub();$('#rhubTitle').textContent='Contacts';$('#rhubApps').innerHTML=icon('directory','Annuaire','♙')+icon('services','Services','☎')+icon('chiefs','Chefs','♟')+icon('share','Partager','↥');$('#rhubCarousel').innerHTML='<article class="rhub-slide"><div class="rhub-widget rhub-loading">Chargement de l’annuaire…</div></article>';dots();try{contactsCache=contactsCache||await call('contacts');renderContacts(kind)}catch(e){$('#rhubCarousel').innerHTML=`<article class="rhub-slide"><div class="rhub-widget rhub-loading">${esc(e.message)}</div></article>`}$('#rhubApps').onclick=e=>{const b=e.target.closest('[data-rhub-select]');if(b)renderContacts(b.dataset.rhubSelect)}}
function simpleConfig(kind){return{plans:{title:'Plans',label:'Repères',text:'Les sites, secteurs et repères terrain publiés dans STIP apparaissent ici.',module:'Repères',symbol:'⌖'},files:{title:'Fichiers',label:'Procédures',text:'Les procédures et fiches pratiques publiées dans STIP apparaissent ici.',module:'Procédures',symbol:'▤'},tools:{title:'Outils',label:'Outils équipe',text:'Les outils autorisés pour ton profil apparaissent ici.',module:'Outils équipe',symbol:'⌘'}}[kind]}
function openSimpleHub(kind){const cfg=simpleConfig(kind);if(!cfg)return;showHub();$('#rhubTitle').textContent=cfg.title;$('#rhubApps').innerHTML=icon(kind,cfg.label,cfg.symbol);$('#rhubCarousel').innerHTML=`<article class="rhub-slide"><div class="rhub-widget"><div class="rhub-widget-top"><div><span class="rhub-eyebrow">${esc(cfg.label.toUpperCase())}</span><h2>${esc(cfg.title)}</h2></div>${expand('module-'+kind)}</div><p>${esc(cfg.text)}</p></div></article>`;dots();$('#rhubApps .rhub-app')?.classList.add('selected')}
function routeHomeIcons(){const map={calendar:()=>showPlanning('personal'),contacts:()=>openContactsHub(),plans:()=>openSimpleHub('plans'),files:()=>openSimpleHub('files'),tools:()=>openSimpleHub('tools'),responsable:()=>location.href='responsable.html'};$$('#homeView [data-hs-app]').forEach(b=>{const fn=map[b.dataset.hsApp];if(fn)b.onclick=e=>{e.preventDefault();fn()}})}
document.addEventListener('click',e=>{const b=e.target.closest?.('[data-rhub-expand]');if(!b)return;const a=b.dataset.rhubExpand;if(a==='contacts-all')openContactsFull('all');else if(a==='contacts-services')openContactsFull('service');else if(a==='contacts-chiefs')openContactsFull('chef');else if(a.startsWith('module-')){const cfg=simpleConfig(a.slice(7));moduleButton(cfg?.module)?.click()}},true);
const s=document.createElement('style');s.textContent=`.rhub-view{padding:0!important;background:#f7fbfc}.rhub-shell{box-sizing:border-box;width:100%;max-width:560px;margin:0 auto;padding:18px clamp(14px,4vw,22px) 36px}.rhub-head{display:flex;align-items:center;gap:12px;margin:4px 0 14px}.rhub-head>button{width:40px;height:40px;border:0;border-radius:14px;background:#fff;color:#0d4257;font-size:1.6rem}.rhub-head span,.rhub-eyebrow{font-size:.64rem;font-weight:950;letter-spacing:.12em;color:#0798b5}.rhub-head h1{margin:2px 0 0;color:#0d4257;font-size:2rem}.rhub-carousel{display:flex;overflow:auto;scroll-snap-type:x mandatory;scrollbar-width:none}.rhub-slide{flex:0 0 100%;scroll-snap-align:center}.rhub-widget{box-sizing:border-box;width:100%;min-height:250px;padding:18px;border:1px solid #d9eaee;border-radius:26px;background:#fff;box-shadow:0 12px 30px rgba(18,72,88,.08);display:flex;flex-direction:column;color:#123444}.rhub-widget-top{display:flex;justify-content:space-between;gap:12px}.rhub-widget h2{margin:7px 0 8px;color:#0d4257}.rhub-widget p{color:#667b85}.rhub-expand{width:34px;height:34px;border:0;border-radius:11px;background:#f1f7f8;color:#315866}.rhub-list{display:grid;gap:6px;margin-top:12px;max-height:210px;overflow:auto}.rhub-row{display:flex;justify-content:space-between;align-items:center;gap:10px;padding:9px 10px;border-radius:12px;background:#f4f8f9}.rhub-row strong{display:block;color:#0d4257;font-size:.72rem}.rhub-row small{display:block;color:#72858c;font-size:.59rem}.rhub-actions{display:flex;gap:4px}.rhub-actions a{text-decoration:none;padding:6px 7px;border-radius:9px;background:#eaf7f9;color:#087789;font-size:.58rem;font-weight:900}.rhub-search input{width:100%;box-sizing:border-box;border:1px solid #d7e5e8;border-radius:12px;background:#f8fbfc;padding:10px;color:#123444}.rhub-primary{margin-top:auto;min-height:42px;padding:0 14px;border:0;border-radius:13px;background:#0798b5;color:#fff;font-weight:900}.rhub-loading{display:grid;place-items:center}.rhub-dots{display:flex;justify-content:center;padding:9px}.rhub-dots i{width:18px;height:5px;border-radius:99px;background:#0798b5}.rhub-apps{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:7px}.rhub-app{min-height:58px;padding:8px 10px;border:1px solid #d8e8ec;border-radius:16px;background:#fff;color:#123444;display:flex;align-items:center;gap:10px}.rhub-app.selected{background:#f0fbfd;border-color:#7bc9d7}.rhub-icon{width:40px;height:40px;border-radius:11px;display:grid;place-items:center;background:#1688d3;color:#fff}.rhub-app strong{font-size:.72rem}@media(min-width:700px){.rhub-shell{max-width:720px;padding:28px 30px 44px}.rhub-apps{grid-template-columns:repeat(3,minmax(0,1fr))}.rhub-widget{min-height:330px}.rhub-list{max-height:280px}}`;document.head.appendChild(s);
routeHomeIcons();new MutationObserver(routeHomeIcons).observe(document.getElementById('homeView')||document.body,{childList:true,subtree:true});window.STIPHubs={planning:showPlanning,contacts:openContactsHub,simple:openSimpleHub};
})();