(()=>{'use strict';
const API='https://yzsrmuxghlengnkyphxj.supabase.co/functions/v1/stip-evaluations';
const GROUPS=[['I — Aptitude au service',['Aptitude à travailler sans contrôle','Efficacité','Esprit pratique','Souci de perfectionnement'],'Observations I — Aptitude au service'],['II — Exécution du travail',["Rapidité d'exécution",'Qualité du travail',"Sens de l'organisation",'Initiative'],'Observations II — Exécution du travail'],['III — Travail en commun',['Caractère','Relation avec le personnel infirmier','Contact avec les autres agents du service','Contact avec l’encadrement'],'Observations III — Travail en commun'],['IV — Comportement envers les malades',['Disponibilité','Discrétion','Attitude envers les visiteurs'],'Observations IV — Comportement envers les malades'],['V — Tenue, ponctualité, assiduité',['Utilisation du temps de travail','Attitude générale','Propreté dans la tenue','Régularité','Ponctualité / assiduité'],'Observations V — Tenue, ponctualité, assiduité']];
const NOT='Éléments insuffisants pour évaluer',$=id=>document.getElementById(id);
let token='',signed=false,drawing=false,ev=null;
const canvas=$('sigCanvas'),ctx=canvas.getContext('2d');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function status(t,k=''){const s=$('sigStatus');s.textContent=t;s.className='sig-status'+(k?' '+k:'')}
function fr(v){if(!v)return'—';const m=String(v).match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[3]}/${m[2]}/${m[1]}`:String(v)}
function readToken(){const raw=location.hash.startsWith('#t=')?decodeURIComponent(location.hash.slice(3)):'';if(raw){sessionStorage.setItem('stip:eval-signature-token',raw);history.replaceState(null,'',location.pathname)}return sessionStorage.getItem('stip:eval-signature-token')||''}
async function post(action,body={}){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...body}),cache:'no-store'}),j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw Error(j.error||`Erreur ${r.status}`);return j}
function render(e){
  ev=e;
  $('sigSummary').innerHTML=`<div><small>Agent</small><strong>${esc([e.agent_prenom,e.agent_nom].filter(Boolean).join(' '))}</strong></div><div><small>Responsable évaluateur</small><strong>${esc(e.evaluator_name||'—')}</strong></div><div><small>Date</small><strong>${fr(e.evaluation_date)}</strong></div><div><small>Service</small><strong>${esc(e.service||'—')}</strong></div>`;
  $('sigEvaluation').innerHTML=GROUPS.map(g=>`<section class="sig-section"><h2>${esc(g[0])}</h2><div class="sig-criteria">${g[1].map(c=>`<div class="sig-criterion"><span>${esc(c)}</span><strong class="sig-level">${esc(e.criteria?.[c]===NOT?'Non observé':e.criteria?.[c]||'Non observé')}</strong></div>`).join('')}</div>${e.observations?.[g[2]]?`<div class="sig-observation">${esc(e.observations[g[2]])}</div>`:''}</section>`).join('')+`<section class="sig-section"><h2>Conclusion</h2><div class="sig-decision"><strong>Aimeriez-vous garder cet agent ? ${esc(e.decision||'—')}</strong>${e.observations?.['Observations générales']?`<div class="sig-observation">${esc(e.observations['Observations générales'])}</div>`:''}<div class="sig-observation">Fait à Lyon, le ${fr(e.signature_date||e.evaluation_date)}</div></div></section>`;
  $('sigName').textContent=`Signature de ${[e.agent_prenom,e.agent_nom].filter(Boolean).join(' ')||'l’agent'}`;
}
function resize(){const rect=canvas.getBoundingClientRect();if(!rect.width)return;const ratio=Math.max(1,window.devicePixelRatio||1),snap=signed?canvas.toDataURL('image/png'):'';canvas.width=Math.round(rect.width*ratio);canvas.height=Math.round(160*ratio);ctx.setTransform(ratio,0,0,ratio,0,0);ctx.lineWidth=2.2;ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#17232d';if(snap){const img=new Image();img.onload=()=>ctx.drawImage(img,0,0,rect.width,160);img.src=snap}}
function point(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
canvas.addEventListener('pointerdown',e=>{e.preventDefault();drawing=true;canvas.setPointerCapture(e.pointerId);const p=point(e);ctx.beginPath();ctx.moveTo(p.x,p.y)});
canvas.addEventListener('pointermove',e=>{if(!drawing)return;e.preventDefault();const p=point(e);ctx.lineTo(p.x,p.y);ctx.stroke();signed=true});
canvas.addEventListener('pointerup',()=>drawing=false);canvas.addEventListener('pointercancel',()=>drawing=false);
$('sigClear').onclick=()=>{ctx.clearRect(0,0,canvas.width,canvas.height);signed=false};
$('sigSubmit').onclick=async()=>{if(!signed){status('Ajoutez votre signature avant de continuer.','error');return}if(!$('sigConfirm').checked){status('Confirmez avoir relu l’évaluation.','error');return}const b=$('sigSubmit');b.disabled=true;status('Enregistrement de votre signature…');try{await post('public_signature_submit',{token,signature:canvas.toDataURL('image/png')});sessionStorage.removeItem('stip:eval-signature-token');$('sigContent').hidden=true;$('sigStatus').hidden=true;$('sigDone').hidden=false}catch(e){status(e.message||'Impossible d’enregistrer la signature.','error');b.disabled=false}};
async function boot(){token=readToken();if(!token){status('Ce lien est incomplet ou n’est plus disponible.','error');return}try{const d=await post('public_signature_get',{token});if(d.request?.statut==='SIGNE'){sessionStorage.removeItem('stip:eval-signature-token');$('sigStatus').hidden=true;$('sigDone').hidden=false;return}render(d.evaluation||{});$('sigContent').hidden=false;status(`Lien valable jusqu’au ${new Date(d.request?.expire_le).toLocaleString('fr-FR')}.`,'ok');requestAnimationFrame(resize)}catch(e){status(e.message||'Ce lien n’est plus disponible.','error')}}
window.addEventListener('resize',resize);boot();
})();