(()=>{'use strict';
const baseFetch=window.fetch.bind(window),active=new Map();let hud=null,hideTimer=null,seq=0;
const META={login:['auth','Connexion à STIP'],bootstrap:['planning','Préparation de STIP'],personal:['planning','Chargement du planning'],official:['team','Chargement du planning équipe'],spirit:['team','Chargement de l’équipe'],contacts:['contacts','Chargement des contacts'],directory:['contacts','Chargement de l’annuaire'],responsable_agents:['responsable','Chargement des brancardiers'],responsable_agent:['agent','Ouverture de la fiche'],agent_search_all:['agent','Recherche des brancardiers'],case_detail:['agent','Ouverture du dossier'],getEvaluation:['evaluation','Ouverture de l’évaluation']};
const VISIBLE=new Set(Object.keys(META)),SHOW_AFTER=420;
function ensure(){if(hud)return hud;hud=document.createElement('div');hud.id='stipLoadHud';hud.className='stip-load-hud';hud.setAttribute('aria-live','polite');hud.innerHTML='<div class="stip-load-row"><span class="stip-load-icon" aria-hidden="true"></span><span class="stip-load-copy"><strong>Chargement…</strong><small>Lecture des données…</small></span></div><div class="stip-load-track"><div class="stip-load-bar"></div></div>';document.body.appendChild(hud);return hud}
function paint(task){if(!task?.shown)return;const h=ensure(),p=Math.max(4,Math.min(96,Math.round(task.progress)));h.dataset.kind=task.kind;h.querySelector('.stip-load-copy strong').textContent=task.label;h.querySelector('.stip-load-copy small').textContent=task.phase;h.querySelector('.stip-load-bar').style.width=p+'%';h.classList.add('show');h.classList.remove('done')}
function leader(){return [...active.values()].filter(x=>x.shown).sort((a,b)=>b.started-a.started)[0]||null}
function update(){const t=leader();if(t){paint(t);return}if(hud){hud.classList.add('done');clearTimeout(hideTimer);hideTimer=setTimeout(()=>hud?.classList.remove('show','done'),180)}}
function start(action){if(!VISIBLE.has(action))return null;const [kind,label]=META[action],id=++seq,t={id,action,kind,label,started:performance.now(),progress:10,phase:'Lecture des données…',shown:false,timer:null,showTimer:null};active.set(id,t);t.showTimer=setTimeout(()=>{if(!active.has(id))return;t.shown=true;paint(t);t.timer=setInterval(()=>{const ms=performance.now()-t.started;if(ms>2600)t.progress=Math.min(90,t.progress+2);else if(ms>1100)t.progress=Math.min(72,t.progress+4);else t.progress=Math.min(42,t.progress+5);paint(t)},220)},SHOW_AFTER);return t}
function done(t,ok=true){if(!t)return;clearTimeout(t.showTimer);clearInterval(t.timer);if(t.shown){t.progress=96;t.phase=ok?'Terminé':'Chargement impossible';paint(t)}active.delete(t.id);if(t.shown)setTimeout(update,ok?100:500);else update()}
function body(init){try{return typeof init?.body==='string'?JSON.parse(init.body):null}catch{return null}}
window.fetch=async function(input,init){const b=body(init),action=String(b?.action||''),t=start(action);if(!t)return baseFetch(input,init);try{const r=await baseFetch(input,init);done(t,r.ok);return r}catch(e){done(t,false);throw e}};
window.STIPLoading={start:(label='Chargement',kind='generic')=>{const id=++seq,t={id,action:'manual',kind,label,started:performance.now(),progress:18,phase:'Lecture des données…',shown:true,timer:null,showTimer:null};active.set(id,t);paint(t);return()=>done(t,true)},active:()=>active.size};
})();
