(()=>{'use strict';
const baseFetch=window.fetch.bind(window),active=new Map();let hud=null,hideTimer=null,seq=0;
const META={
 me:['auth','Vérification de ta session'],login:['auth','Connexion à STIP'],logout:['auth','Fermeture de session'],bootstrap:['planning','Préparation de STIP'],home:['generic','Mise à jour de l’accueil'],contacts:['contacts','Chargement des contacts'],directory:['contacts','Recherche dans l’annuaire'],spirit:['team','Chargement de l’équipe'],team:['team','Chargement de l’équipe'],team_today:['team','Équipe d’aujourd’hui'],team_week:['team','Planning équipe de la semaine'],manager_list:['responsable','Chargement responsable'],responsable_list:['responsable','Demandes responsable'],agent_search_all:['agent','Recherche des brancardiers'],case_detail:['agent','Ouverture de l’agent'],listEvaluations:['evaluation','Chargement des évaluations'],list:['evaluation','Chargement des évaluations'],getEvaluation:['evaluation','Ouverture de l’évaluation'],getAgentSignatureStatus:['evaluation','Vérification de la signature'],agenda:['planning','Chargement de l’agenda'],calendar:['planning','Synchronisation calendrier']
};
function meta(action,url=''){const a=String(action||'');if(META[a])return META[a];if(/onboarding|agent|readonly/i.test(url))return['agent','Chargement de l’agent'];if(/evaluation/i.test(url))return['evaluation','Chargement de l’évaluation'];if(/change/i.test(url))return['planning','Chargement du changement'];if(/calendar/i.test(url))return['planning','Chargement du calendrier'];return['generic','Chargement des données']}
function ensure(){if(hud)return hud;hud=document.createElement('div');hud.id='stipLoadHud';hud.className='stip-load-hud';hud.setAttribute('aria-live','polite');hud.innerHTML='<div class="stip-load-row"><span class="stip-load-icon" aria-hidden="true"></span><span class="stip-load-copy"><strong>Chargement…</strong><small>Initialisation</small></span><span class="stip-load-pct">0%</span></div><div class="stip-load-track"><div class="stip-load-bar"></div></div>';document.body.appendChild(hud);return hud}
function paint(task){const h=ensure(),p=Math.max(1,Math.min(100,Math.round(task.progress)));h.dataset.kind=task.kind;h.querySelector('.stip-load-copy strong').textContent=task.label;h.querySelector('.stip-load-copy small').textContent=task.phase;h.querySelector('.stip-load-pct').textContent=p+'%';h.querySelector('.stip-load-bar').style.width=p+'%';h.classList.add('show');h.classList.remove('done')}
function leader(){return [...active.values()].sort((a,b)=>b.started-a.started)[0]||null}
function update(){const t=leader();if(t)paint(t);else if(hud){hud.classList.add('done');clearTimeout(hideTimer);hideTimer=setTimeout(()=>hud?.classList.remove('show','done'),240)}}
function phase(t,p,label){if(!active.has(t.id))return;t.progress=Math.max(t.progress,p);t.phase=label;paint(t)}
function start(action,url){const [kind,label]=meta(action,url),id=++seq,t={id,action,kind,label,started:performance.now(),progress:8,phase:'Connexion au service…',timer:null};active.set(id,t);update();t.timer=setInterval(()=>{const ms=performance.now()-t.started;if(ms>2800&&t.progress<88){t.progress=Math.min(88,t.progress+2);t.phase='Traitement en cours…'}else if(ms>1100&&t.progress<72){t.progress=Math.min(72,t.progress+3);t.phase='Lecture des données…'}else if(t.progress<38){t.progress=Math.min(38,t.progress+4);t.phase='Connexion établie…'}paint(t)},180);return t}
function done(t,ok=true){if(!t)return;clearInterval(t.timer);if(ok){t.progress=100;t.phase='Terminé';paint(t)}else{t.progress=100;t.phase='Impossible de charger';paint(t)}setTimeout(()=>{active.delete(t.id);update()},ok?180:700)}
function body(init){try{return typeof init?.body==='string'?JSON.parse(init.body):null}catch{return null}}
window.fetch=async function(input,init){const url=typeof input==='string'?input:(input?.url||String(input)),b=body(init),action=b?.action||'';const should=/supabase\.co\/functions\/v1/i.test(url)||!!action;if(!should)return baseFetch(input,init);const t=start(action,url);try{phase(t,22,'Connexion établie…');const r=await baseFetch(input,init);phase(t,82,r.ok?'Réponse reçue…':'Erreur reçue…');done(t,r.ok);return r}catch(e){done(t,false);throw e}};
function classifyText(s=''){s=String(s).toLowerCase();if(/équipe|brancardier|agent/.test(s))return'team';if(/planning|calendrier|agenda/.test(s))return'planning';if(/responsable|demande|suivi/.test(s))return'responsable';if(/contact|annuaire/.test(s))return'contacts';if(/évaluation|signature/.test(s))return'evaluation';return'generic'}
function decorate(root=document){root.querySelectorAll?.('.ph-page-load,.route-loading,.resp-empty[aria-busy="true"],.ro-load,[class*="loading"],[class*="loader"]').forEach(el=>{if(el.id==='stipLoadHud'||el.closest?.('#stipLoadHud'))return;if(el.dataset.stipDecorated)return;el.dataset.stipDecorated='1';el.classList.add('stip-inline-load');el.dataset.loadKind=classifyText(el.textContent)})}
new MutationObserver(ms=>ms.forEach(m=>m.addedNodes.forEach(n=>{if(n.nodeType===1)decorate(n)}))).observe(document.documentElement,{subtree:true,childList:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>decorate());else decorate();window.STIPLoading={start:(label='Chargement',kind='generic')=>{const t=start('',kind);t.label=label;t.kind=kind;paint(t);return()=>done(t,true)},active:()=>active.size};
})();
