(()=>{
'use strict';
const ROOT='https://yzsrmuxghlengnkyphxj.supabase.co/functions/v1',ONB=ROOT+'/stip-onboarding',EVAL=ROOT+'/stip-evaluations',STORE='stip_session_v1';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const state={boot:null,current:null,tab:'profile',stage:null,evals:[],eval:null,sig:{}};
const LEVELS=['Insuffisant','Médiocre','Passable','Assez bien','Bien','Très bien','Exceptionnel','Éléments insuffisants pour évaluer'];
const ESECTIONS=[['I — Aptitude au service',['Aptitude à travailler sans contrôle','Efficacité','Esprit pratique','Souci de perfectionnement'],'Observations I — Aptitude au service'],['II — Exécution du travail',["Rapidité d'exécution",'Qualité du travail',"Sens de l'organisation",'Initiative'],'Observations II — Exécution du travail'],['III — Travail en commun',['Caractère','Relation avec le personnel infirmier','Contact avec les autres agents du service','Contact avec l’encadrement'],'Observations III — Travail en commun'],['IV — Comportement envers les malades',['Disponibilité','Discrétion','Attitude envers les visiteurs'],'Observations IV — Comportement envers les malades'],['V — Tenue, ponctualité, assiduité',['Utilisation du temps de travail','Attitude générale','Propreté dans la tenue','Régularité','Ponctualité / assiduité'],'Observations V — Tenue, ponctualité, assiduité']];
const token=()=>localStorage.getItem(STORE)||'',today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Paris',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),fmt=v=>v?new Date(String(v).slice(0,10)+'T12:00:00').toLocaleDateString('fr-FR',{day:'2-digit',month:'short',year:'numeric'}):'Non renseigné';
const person=a=>[a?.prenom,a?.nom].filter(Boolean).join(' ').trim()||String(a?.source_key||'Agent').replaceAll('_',' '),initials=a=>person(a).split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase(),slug=v=>String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/gi,'_').replace(/^_|_$/g,'').toLowerCase();
async function call(url,action,body={}){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','X-STIP-Session':token()},body:JSON.stringify({action,...body})});const j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw new Error(j.error||`Erreur ${r.status}`);return j}
const onb=(a,b={})=>call(ONB,a,b),eva=(a,b={})=>call(EVAL,a,b),manage=()=>!!state.boot?.can_manage,evaluate=()=>!!state.boot?.manager?.can_evaluate;
function message(el,t,k=''){el.textContent=t||'';el.className=`message ${k}`.trim()}
function fatal(e){$('#loading').classList.add('hidden');$('#dashboard').classList.add('hidden');$('#casePanel').classList.add('hidden');$('#fatalText').textContent=e.message||String(e);$('#fatal').classList.remove('hidden')}
function agentOf(c){return c?.agent||{id:c?.agent_id,nom:c?.profile_data?.legacy_nom,prenom:c?.profile_data?.legacy_prenom}}
function card(c,own=false){const a=agentOf(c),p=c.progress||{final:0};return `<article class="case-card" data-case="${esc(c.id)}"><strong>${esc(person(a))}</strong><small>${esc(a.role||'Agent')} · arrivée ${esc(fmt(c.arrival_date))}</small><div class="stage-progress"><span style="width:${Math.min(100,(p.final||0)/6*100)}%"></span></div><small>${own?'Mon dossier · ':''}${p.final||0}/6 étapes validées</small></article>`}
function renderCases(items){const q=$('#caseFilter').value.trim().toLocaleLowerCase('fr'),rows=(items||[]).filter(c=>!q||person(agentOf(c)).toLocaleLowerCase('fr').includes(q));$('#caseList').innerHTML=rows.map(c=>card(c)).join('')||'<div class="empty">Aucun dossier suivi.</div>';$$('#caseList [data-case]').forEach(x=>x.onclick=()=>openCase(x.dataset.case))}
function dashboard(){const b=state.boot;$('#identity').textContent=person(b.agent);$('#heroText').textContent=b.can_manage?'Gérez les intégrations, évaluations officielles, situations et documents depuis la Base STIP.':'Consultez votre dossier d’intégration et vos étapes de suivi.';$('#newCaseBtn').classList.toggle('hidden',!b.can_manage);$('#managerBlock').classList.toggle('hidden',!b.can_manage);if(b.can_manage)renderCases(b.managed_cases||[]);$('#ownBlock').classList.toggle('hidden',!b.own_case);if(b.own_case){$('#ownCase').innerHTML=card(b.own_case,true);$('#ownCase [data-case]').onclick=()=>openCase(b.own_case.id)}$('#loading').classList.add('hidden');$('#dashboard').classList.remove('hidden')}
async function openCase(id){$('#dashboard').classList.add('hidden');$('#casePanel').classList.remove('hidden');$('#tabContent').innerHTML='<section class="panel centered"><div class="spinner"></div></section>';const r=await onb('case_detail',{case_id:id});state.current=r.case;state.tab='profile';head();tabs();renderTab()}
function head(){const c=state.current,a=agentOf(c);$('#caseAvatar').textContent=initials(a);$('#caseName').textContent=person(a);$('#caseMeta').textContent=[a.role,a.equipe&&`Équipe ${a.equipe}`,a.ghe&&`GHE ${a.ghe}`,`Arrivée ${fmt(c.arrival_date)}`].filter(Boolean).join(' · ');$('#caseStatus').textContent=c.status==='active'?'Actif':c.status==='completed'?'Terminé':'Archivé';$('#caseStatus').className=`status-pill ${c.status}`;$('#evalTab').classList.toggle('hidden',!evaluate())}
function tabs(){$$('#tabs button').forEach(b=>{b.classList.toggle('active',b.dataset.tab===state.tab);b.onclick=()=>{state.tab=b.dataset.tab;tabs();renderTab()}})}
function renderTab(){if(state.tab==='profile')profile();else if(state.tab==='integration')integration();else if(state.tab==='evaluations')evaluations();else if(state.tab==='events')events();else documents()}
function profile(){const c=state.current,a=agentOf(c),p=c.profile_data||{};$('#tabContent').innerHTML=`<section class="panel"><div class="section-head"><div><p class="kicker">Dossier</p><h2>Informations agent</h2></div></div><div class="grid"><div class="field"><label>Nom</label><input value="${esc(a.nom||'')}" disabled></div><div class="field"><label>Prénom</label><input value="${esc(a.prenom||'')}" disabled></div><div class="field"><label>Téléphone</label><input id="profPhone" value="${esc(p.telephone??p.legacy_phone??a.telephone??'')}"></div><div class="field"><label>Matricule</label><input id="profMat" value="${esc(p.matricule??p.legacy_matricule??'')}"></div><div class="field"><label>Date d’arrivée</label><input id="profArrival" type="date" value="${esc(c.arrival_date||'')}" ${manage()?'':'disabled'}></div><div class="field"><label>Statut de vérification</label><input id="profVerify" value="${esc(c.verification_status||'')}" ${manage()?'':'disabled'}></div><div class="field wide"><label>Expériences / éléments utiles</label><textarea id="profExp">${esc(c.experience_text??p.experiences??'')}</textarea></div></div><div class="actions"><button id="profSave" class="btn primary">Enregistrer</button></div><p id="profMsg" class="message"></p>${manage()?`<div class="danger-zone"><strong>État du dossier</strong><div class="actions"><button class="btn secondary" data-status="active">Actif</button><button class="btn secondary" data-status="completed">Terminé</button><button class="btn danger" data-status="archived">Archiver</button></div></div>`:''}</section>`;$('#profSave').onclick=saveProfile;$$('[data-status]').forEach(b=>b.onclick=()=>statusCase(b.dataset.status))}
async function saveProfile(){const m=$('#profMsg');message(m,'Enregistrement…');try{await onb('profile_update',{case_id:state.current.id,arrival_date:$('#profArrival')?.value,verification_status:$('#profVerify')?.value,experience_text:$('#profExp').value,profile_data:{telephone:$('#profPhone').value,matricule:$('#profMat').value,experiences:$('#profExp').value}});state.current=(await onb('case_detail',{case_id:state.current.id})).case;head();message(m,'Dossier enregistré dans Base.','ok')}catch(e){message(m,e.message,'err')}}
async function statusCase(status){if(!confirm(status==='archived'?'Archiver ce dossier ?':'Changer le statut du dossier ?'))return;await onb('case_status',{case_id:state.current.id,status});state.current=(await onb('case_detail',{case_id:state.current.id})).case;state.boot=await onb('bootstrap');head();profile()}
function integration(){const rows=state.current.stages||[];$('#tabContent').innerHTML=`<section class="panel"><div class="section-head"><div><p class="kicker">Parcours</p><h2>Suivi d’intégration</h2><p>1er jour, 1re semaine, fin de doublure, 1 mois, 3 mois et 6 mois.</p></div></div><div class="card-list">${rows.map(s=>{const r=s.record;return `<article class="stage-card ${r?.status==='final'?'final':r?'draft':''}" data-stage="${esc(s.stage_key)}"><strong>${esc(s.label)}</strong><small>${r?.status==='final'?`Validé · ${fmt(r.validation_date)}`:r?'Brouillon enregistré':'À faire'}</small></article>`}).join('')}</div></section>`;$$('[data-stage]').forEach(x=>x.onclick=()=>openStage(x.dataset.stage))}
function grouped(schema){const g=new Map();for(const i of schema.items||[]){const k=i.section||'Étapes';if(!g.has(k))g.set(k,[]);g.get(k).push(i)}return g}
function openStage(key){const s=(state.current.stages||[]).find(x=>x.stage_key===key);if(!s)return;state.stage=s;$('#stageTitle').textContent=s.label;$('#stageObjective').textContent=s.form_schema?.objective||'';const sc=s.form_schema||{},p=s.record?.payload||{},items=p.items||{};let h='';for(const [title,list] of grouped(sc)){h+=`<section class="stage-section"><h3>${esc(title)}</h3>${list.map(i=>{const v=items[i.key]||{};return `<div class="criterion"><strong>${esc(i.label)}</strong><div class="level-row">${(sc.levels||[]).map(l=>`<label><input type="radio" name="st_${esc(i.key)}" value="${esc(l)}" ${v.level===l?'checked':''}><span>${esc(l)}</span></label>`).join('')}</div><textarea data-stobs="${esc(i.key)}" placeholder="Observation si nécessaire">${esc(v.observation||'')}</textarea></div>`}).join('')}</section>`}if((sc.bilan_fields||[]).length)h+=`<section class="stage-section"><h3>Bilan</h3>${sc.bilan_fields.map(f=>`<div class="field"><label>${esc(f.label)}</label><textarea data-bilan="${esc(f.key)}">${esc(p.bilan?.[f.key]||'')}</textarea></div>`).join('')}</section>`;if((sc.choices||[]).length){const gs=[...new Set(sc.choices.map(c=>c.group))];h+=`<section class="stage-section"><h3>Avis</h3>${gs.map(g=>`<div class="field"><label>Choix</label><select data-choice="${esc(g)}"><option value="">Choisir…</option>${sc.choices.filter(c=>c.group===g).map(c=>`<option value="${esc(c.key)}" ${p.choices?.[g]===c.key?'selected':''}>${esc(c.label)}</option>`).join('')}</select></div>`).join('')}</section>`}h+=`<section class="stage-section"><div class="field"><label>Note complémentaire</label><textarea id="stageNote">${esc(p.note||'')}</textarea></div></section>`;$('#stageFields').innerHTML=h;const locked=s.record?.status==='final';$('#stageSave').classList.toggle('hidden',locked);$('#stageFinalize').classList.toggle('hidden',locked||!manage());message($('#stageMessage'),locked?'Étape validée et protégée.':'');$('#stageDialog').showModal()}
function stagePayload(){const sc=state.stage.form_schema||{},items={},bilan={},choices={};for(const i of sc.items||[])items[i.key]={level:document.querySelector(`[name="st_${CSS.escape(i.key)}"]:checked`)?.value||'',observation:document.querySelector(`[data-stobs="${CSS.escape(i.key)}"]`)?.value||''};$$('[data-bilan]').forEach(x=>bilan[x.dataset.bilan]=x.value);$$('[data-choice]').forEach(x=>choices[x.dataset.choice]=x.value);return{items,bilan,choices,note:$('#stageNote')?.value||''}}
async function saveStage(finalize){const m=$('#stageMessage');message(m,finalize?'Validation…':'Enregistrement…');try{await onb(finalize?'stage_finalize':'stage_save',{case_id:state.current.id,stage_key:state.stage.stage_key,payload:stagePayload(),validation_date:today()});state.current=(await onb('case_detail',{case_id:state.current.id})).case;$('#stageDialog').close();integration()}catch(e){message(m,e.message,'err')}}
async function evaluations(){if(!evaluate()){state.tab='profile';tabs();return profile()}$('#tabContent').innerHTML='<section class="panel centered"><div class="spinner"></div></section>';try{state.evals=(await eva('list',{case_id:state.current.id})).evaluations||[];$('#tabContent').innerHTML=`<section class="panel"><div class="section-head"><div><p class="kicker">Évaluation 2026</p><h2>Évaluations officielles</h2><p>Versions immuables, signatures, PDF et SHA-256 dans Base.</p></div><button id="newEval" class="btn primary">Nouvelle évaluation</button></div><div class="card-list">${state.evals.map(e=>`<article class="eval-card" data-eid="${esc(e.id)}"><strong>${esc(fmt(e.date_evaluation))} · version ${esc(e.version)}</strong><small>${esc(e.evaluateur||'Évaluateur')} · ${e.statut==='VALIDE'?'Officielle':'Brouillon'}</small><span class="badge ${e.statut==='VALIDE'?'good':'warn'}">${e.statut==='VALIDE'?'Validée':'Brouillon'}</span></article>`).join('')||'<div class="empty">Aucune évaluation.</div>'}</div></section>`;$('#newEval').onclick=()=>openEval(null);$$('[data-eid]').forEach(x=>x.onclick=()=>openEval(state.evals.find(e=>e.id===x.dataset.eid)))}catch(e){$('#tabContent').innerHTML=`<section class="panel"><p class="message err">${esc(e.message)}</p></section>`}}
function obsLegacy(key){const i=ESECTIONS.findIndex(x=>x[2]===key);return i>=0?`observations_${i+1}`:'observations_generales'}
function evalFields(e){const lock=e?.statut==='VALIDE',cr=e?.criteres||{},ob=e?.observations||{};let h=`<div class="grid"><div class="field"><label>Date évaluation</label><input id="evDate" type="date" value="${esc(e?.date_evaluation||today())}" ${lock?'disabled':''}></div><div class="field"><label>Date signature</label><input id="evSignDate" type="date" value="${esc(e?.lyon_le||today())}" ${lock?'disabled':''}></div><div class="field"><label>Grade</label><input id="evGrade" value="${esc(e?.grade||state.current?.agent?.role||'Brancardier')}" ${lock?'disabled':''}></div><div class="field"><label>Service</label><input id="evService" value="${esc(e?.service||'STIP')}" ${lock?'disabled':''}></div><div class="field wide"><label>Aimeriez-vous garder cet agent ?</label><select id="evDecision" ${lock?'disabled':''}><option value="">Choisir…</option><option value="OUI" ${e?.garder_agent==='OUI'?'selected':''}>Oui</option><option value="NON" ${e?.garder_agent==='NON'?'selected':''}>Non</option></select></div></div>`;for(const [title,labels,key] of ESECTIONS)h+=`<section class="eval-section"><h3>${esc(title)}</h3>${labels.map(l=>`<div class="criterion"><strong>${esc(l)}</strong><div class="level-row">${LEVELS.map(v=>`<label><input type="radio" name="ev_${slug(l)}" value="${esc(v)}" ${(cr[l]||LEVELS.at(-1))===v?'checked':''} ${lock?'disabled':''}><span>${esc(v===LEVELS.at(-1)?'Non observé':v)}</span></label>`).join('')}</div></div>`).join('')}<div class="obs-block"><label>Observation<textarea data-evobs="${esc(key)}" ${lock?'disabled':''}>${esc(ob[key]||e?.[obsLegacy(key)]||'')}</textarea></label></div></section>`;h+=`<section class="eval-section"><h3>Observations générales</h3><textarea id="evGeneral" ${lock?'disabled':''}>${esc(ob['Observations générales']||e?.observations_generales||'')}</textarea></section>`;if(!lock)h+=`<section class="eval-section"><h3>Signatures</h3><div class="signature-wrap">${['agent','responsable','direction'].map(r=>`<div class="signature-box" data-sig="${r}"><strong>${r==='responsable'?'Responsable (obligatoire)':r==='agent'?'Agent':'Direction (facultatif)'}</strong><canvas></canvas><button type="button" class="ghost-btn" data-clear="${r}">Effacer</button></div>`).join('')}</div></section>`;if(e?.url_document)h+=`<div class="actions"><a class="btn primary" href="${esc(e.url_document)}" target="_blank" rel="noopener">Ouvrir le PDF officiel</a></div>`;return h}
function openEval(e){state.eval=e;$('#evaluationTitle').textContent=e?`${e.id_evaluation} · v${e.version}`:'Nouvelle évaluation';$('#evaluationFields').innerHTML=evalFields(e);const lock=e?.statut==='VALIDE';$('#evaluationSave').classList.toggle('hidden',lock);$('#evaluationFinalize').classList.toggle('hidden',lock);message($('#evaluationMessage'),lock?'Version officielle protégée.':'');if(!lock)signatures();$('#evaluationDialog').showModal()}
function signatures(){state.sig={};$$('[data-sig]').forEach(box=>{const role=box.dataset.sig,c=box.querySelector('canvas'),x=c.getContext('2d'),p={canvas:c,ctx:x,drawing:false,signed:false};state.sig[role]=p;const r=c.getBoundingClientRect(),ratio=Math.max(1,devicePixelRatio||1);c.width=Math.round(r.width*ratio);c.height=Math.round(120*ratio);x.setTransform(ratio,0,0,ratio,0,0);x.lineWidth=2.1;x.lineCap='round';x.strokeStyle='#102330';const pos=e=>{const b=c.getBoundingClientRect();return{x:e.clientX-b.left,y:e.clientY-b.top}};c.onpointerdown=e=>{p.drawing=true;c.setPointerCapture(e.pointerId);const q=pos(e);x.beginPath();x.moveTo(q.x,q.y)};c.onpointermove=e=>{if(!p.drawing)return;const q=pos(e);x.lineTo(q.x,q.y);x.stroke();p.signed=true};c.onpointerup=()=>p.drawing=false;c.onpointercancel=()=>p.drawing=false;box.querySelector('[data-clear]').onclick=()=>{x.clearRect(0,0,c.width,c.height);p.signed=false}})}
function evalPayload(){const criteria={},observations={},signatures={};for(const [,labels] of ESECTIONS)for(const l of labels)criteria[l]=document.querySelector(`[name="ev_${slug(l)}"]:checked`)?.value||LEVELS.at(-1);$$('[data-evobs]').forEach(x=>observations[x.dataset.evobs]=x.value);observations['Observations générales']=$('#evGeneral').value;for(const [r,p] of Object.entries(state.sig))if(p.signed)signatures[r]=p.canvas.toDataURL('image/png');return{case_id:state.current.id,evaluation_id:state.eval?.statut==='BROUILLON'?state.eval.id:null,evaluation_date:$('#evDate').value,signature_date:$('#evSignDate').value,grade:$('#evGrade').value,service:$('#evService').value,decision:$('#evDecision').value,criteria,observations,signatures}}
async function saveEval(finalize){const m=$('#evaluationMessage');if(finalize&&!state.sig.responsable?.signed)return message(m,'La signature du responsable est obligatoire.','err');message(m,finalize?'Génération du PDF et validation…':'Enregistrement…');try{const r=await eva(finalize?'finalize':'save_draft',evalPayload());$('#evaluationDialog').close();if(finalize&&r.evaluation?.url_document)window.open(r.evaluation.url_document,'_blank','noopener');evaluations()}catch(e){message(m,e.message,'err')}}
function events(){const rows=state.current.events||[];$('#tabContent').innerHTML=`<section class="panel"><div class="section-head"><div><p class="kicker">Situations / événements</p><h2>Historique</h2></div></div><div class="grid"><div class="field"><label>Type</label><select id="eventType"><option value="observation">Observation</option><option value="situation">Situation</option><option value="meeting">Entretien / réunion</option><option value="note">Note</option></select></div><div class="field"><label>Titre</label><input id="eventTitle" placeholder="Résumé court"></div><div class="field wide"><label>Notes</label><textarea id="eventNotes" placeholder="Faits, contexte, suite donnée…"></textarea></div></div><div class="actions"><button id="eventAdd" class="btn primary">Ajouter</button></div><p id="eventMsg" class="message"></p><div class="timeline">${rows.map(e=>`<article class="event-card"><strong>${esc(e.title)}</strong><small>${esc(e.event_type)} · ${esc(new Date(e.occurred_at).toLocaleString('fr-FR'))}</small>${e.notes?`<p>${esc(e.notes)}</p>`:''}</article>`).join('')||'<div class="empty">Aucune situation enregistrée.</div>'}</div></section>`;$('#eventAdd').onclick=addEvent}
async function addEvent(){const m=$('#eventMsg');message(m,'Enregistrement…');try{await onb('event_add',{case_id:state.current.id,event_type:$('#eventType').value,title:$('#eventTitle').value,notes:$('#eventNotes').value});state.current=(await onb('case_detail',{case_id:state.current.id})).case;events()}catch(e){message(m,e.message,'err')}}
function documents(){const rows=state.current.documents||[];$('#tabContent').innerHTML=`<section class="panel"><div class="section-head"><div><p class="kicker">Documents</p><h2>Documents du dossier</h2><p>Ouverture par URL signée Supabase Storage.</p></div></div><div class="card-list">${rows.map(d=>`<article class="doc-card" data-doc="${esc(d.id)}"><strong>${esc(d.file_name)}</strong><small>${esc(d.document_kind)} · ${d.byte_size?Math.round(d.byte_size/1024)+' Ko':''}</small>${d.checksum_sha256?`<small>SHA-256 ${esc(d.checksum_sha256.slice(0,16))}…</small>`:''}</article>`).join('')||'<div class="empty">Aucun document.</div>'}</div></section>`;$$('[data-doc]').forEach(x=>x.onclick=()=>openDoc(x.dataset.doc))}
async function openDoc(id){try{const r=await onb('document_url',{document_id:id});if(r.source!=='supabase')throw new Error('Document non migré dans Base.');window.open(r.url,'_blank','noopener')}catch(e){alert(e.message)}}
async function agentSearch(q=''){const r=await onb('agent_search',{query:q}),box=$('#agentResults');box.innerHTML=(r.items||[]).map(a=>`<article class="result-card" data-agent="${esc(a.id)}"><strong>${esc(person(a))}</strong><small>${esc([a.role,a.equipe&&`Équipe ${a.equipe}`,a.ghe&&`GHE ${a.ghe}`].filter(Boolean).join(' · '))}</small></article>`).join('')||'<div class="empty">Aucun agent disponible.</div>';$$('[data-agent]').forEach(x=>x.onclick=()=>createCase(x.dataset.agent))}
async function createCase(id){try{const r=await onb('case_create',{agent_id:id,arrival_date:null,verification_status:'À vérifier',profile_data:{}});$('#agentDialog').close();state.boot=await onb('bootstrap');renderCases(state.boot.managed_cases||[]);openCase(r.case.id)}catch(e){alert(e.message)}}
$('#newCaseBtn').onclick=async()=>{$('#agentDialog').showModal();$('#agentSearch').value='';agentSearch('')};$('#agentSearch').oninput=e=>agentSearch(e.target.value);$('#caseFilter').oninput=()=>renderCases(state.boot.managed_cases||[]);$('#backBtn').onclick=async()=>{state.current=null;$('#casePanel').classList.add('hidden');$('#dashboard').classList.remove('hidden');state.boot=await onb('bootstrap');dashboard()};$('#stageSave').onclick=()=>saveStage(false);$('#stageFinalize').onclick=()=>saveStage(true);$('#evaluationSave').onclick=()=>saveEval(false);$('#evaluationFinalize').onclick=()=>saveEval(true);
(async()=>{if(!token())throw new Error('Session STIP absente. Connectez-vous depuis l’accueil STIP.');state.boot=await onb('bootstrap');dashboard()})().catch(fatal);
})();
