(()=>{
'use strict';
const API='https://yzsrmuxghlengnkyphxj.supabase.co/functions/v1/stip-responsable-tools',STORE='stip_session_v1';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function call(action,body={}){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','X-STIP-Session':localStorage.getItem(STORE)||''},body:JSON.stringify({action,...body})});const j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw new Error(j.error||`Erreur ${r.status}`);return j}
function ensureUI(){const dash=$('#dashboard');if(!dash||$('#responsableTools'))return;const panel=document.createElement('section');panel.id='responsableTools';panel.className='panel';panel.innerHTML='<div class="section-head"><div><p class="kicker">Outils complémentaires</p><h2>Responsable</h2><p>Les outils qui existaient dans Responsable sont ici en version Base.</p></div></div><div class="card-list"><article class="stage-card" id="quickNotesCard"><strong>Notes rapides</strong><small>Notes privées enregistrées dans Base.</small></article><article class="stage-card" id="traineeCard"><strong>Stagiaires</strong><small>Voir les stages à venir et ajouter une période.</small></article></div>';dash.appendChild(panel);$('#quickNotesCard').onclick=openNotes;$('#traineeCard').onclick=openTrainees}
function modal(id,title,body){document.getElementById(id)?.remove();const d=document.createElement('dialog');d.id=id;d.innerHTML=`<div class="dialog-card wide-dialog"><div class="section-head"><div><p class="kicker">STIP · Base</p><h2>${esc(title)}</h2></div><button class="icon-btn" type="button" data-close>×</button></div><div data-body>${body}</div></div>`;document.body.appendChild(d);d.querySelector('[data-close]').onclick=()=>d.close();d.showModal();return d}
async function openNotes(){const d=modal('notesDialog','Notes rapides','<p class="message">Chargement…</p>');try{const r=await call('notes_list');renderNotes(d,r.items||[])}catch(e){d.querySelector('[data-body]').innerHTML=`<p class="message err">${esc(e.message)}</p>`}}
function renderNotes(d,items){d.querySelector('[data-body]').innerHTML=`<div class="field"><label>Nouvelle note</label><textarea id="newQuickNote" placeholder="Information à conserver pour vous…"></textarea></div><div class="actions"><button id="addQuickNote" class="btn primary">Enregistrer</button></div><p id="notesMsg" class="message"></p><div class="timeline" id="notesList">${items.map(n=>`<article class="event-card"><strong>${n.pinned?'Épinglée':'Note'}</strong><small>${new Date(n.created_at).toLocaleString('fr-FR')}</small><p>${esc(n.note)}</p><div class="actions"><button class="ghost-btn" data-pin="${n.id}" data-state="${n.pinned?'1':'0'}">${n.pinned?'Désépingler':'Épingler'}</button><button class="ghost-btn" data-archive="${n.id}">Archiver</button></div></article>`).join('')||'<div class="empty">Aucune note.</div>'}</div>`;$('#addQuickNote').onclick=async()=>{const v=$('#newQuickNote').value.trim(),m=$('#notesMsg');if(!v)return;m.textContent='Enregistrement…';try{await call('note_add',{note:v});openNotes();d.close()}catch(e){m.className='message err';m.textContent=e.message}};d.querySelectorAll('[data-pin]').forEach(b=>b.onclick=async()=>{await call('note_pin',{id:b.dataset.pin,pinned:b.dataset.state!=='1'});d.close();openNotes()});d.querySelectorAll('[data-archive]').forEach(b=>b.onclick=async()=>{if(confirm('Archiver cette note ?')){await call('note_archive',{id:b.dataset.archive});d.close();openNotes()}})}
async function openTrainees(){const d=modal('traineeDialog','Stagiaires','<p class="message">Chargement…</p>');try{const r=await call('stagiaires_list');renderTrainees(d,r.items||[])}catch(e){d.querySelector('[data-body]').innerHTML=`<p class="message err">${esc(e.message)}</p>`}}
function renderTrainees(d,items){d.querySelector('[data-body]').innerHTML=`<section class="stage-section"><h3>Ajouter un stagiaire</h3><div class="grid"><div class="field"><label>Nom</label><input id="stNom"></div><div class="field"><label>Prénom</label><input id="stPrenom"></div><div class="field"><label>Début</label><input id="stDebut" type="date"></div><div class="field"><label>Fin</label><input id="stFin" type="date"></div><div class="field"><label>Horaires</label><input id="stHoraires" placeholder="Ex. 8h-16h"></div><div class="field"><label>Référent</label><input id="stReferent"></div><div class="field wide"><label>Observation</label><textarea id="stObservation"></textarea></div></div><div class="actions"><button id="stAdd" class="btn primary">Ajouter dans Base</button></div><p id="stMsg" class="message"></p></section><section class="stage-section"><h3>Stages à venir</h3><div class="card-list">${items.map(s=>`<article class="event-card"><strong>${esc([s.prenom,s.nom].filter(Boolean).join(' ')||'Stagiaire')}</strong><small>${esc(s.date_debut||'')} → ${esc(s.date_fin||'')}</small>${s.horaires?`<small>${esc(s.horaires)}</small>`:''}${s.referent?`<small>Référent : ${esc(s.referent)}</small>`:''}${s.observation?`<p>${esc(s.observation)}</p>`:''}</article>`).join('')||'<div class="empty">Aucun stage à venir.</div>'}</div></section>`;$('#stAdd').onclick=async()=>{const m=$('#stMsg');m.textContent='Enregistrement…';try{await call('stagiaire_add',{nom:$('#stNom').value,prenom:$('#stPrenom').value,date_debut:$('#stDebut').value,date_fin:$('#stFin').value,horaires:$('#stHoraires').value,referent:$('#stReferent').value,observation:$('#stObservation').value});d.close();openTrainees()}catch(e){m.className='message err';m.textContent=e.message}}}
new MutationObserver(ensureUI).observe(document.body,{childList:true,subtree:true});ensureUI();
})();
