(() => {
'use strict';
const DATA_API='https://yzsrmuxghlengnkyphxj.supabase.co/functions/v1/stip-data';
const CAL_API='https://yzsrmuxghlengnkyphxj.supabase.co/functions/v1/stip-calendar';
const STORAGE='stip_session_v1';
const LAYOUT='stip_test_real_layout_v1';
const WALL='stip_test_real_wall_v1';
const $=s=>document.querySelector(s);
const appsEl=$('#apps'),dockEl=$('#dock'),home=$('#home'),panel=$('#panel'),panelBody=$('#panelBody');
let bootstrap=null,activeKey='personal',editing=false,toastTimer=0;
const icons={
 calendar:'<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M3 10h18M8 3v4M16 3v4M8 14h.01M12 14h.01M16 14h.01M8 17h.01M12 17h.01"/>',
 personal:'<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M3 10h18M8 3v4M16 3v4"/><circle cx="9" cy="15" r="2"/><path d="M13 17c.7-1.8 1.9-2.7 3.5-2.7"/>',
 team:'<circle cx="9" cy="8" r="3"/><circle cx="17" cy="9" r="2.3"/><path d="M3 20c.6-4 2.6-6 6-6s5.4 2 6 6M14 15c3.8-.3 6 1.4 6.5 5"/>',
 contacts:'<rect x="4" y="4" width="16" height="17" rx="3"/><circle cx="12" cy="10" r="2.5"/><path d="M8 17c.8-2.1 2.1-3.1 4-3.1s3.2 1 4 3M8 2v4M16 2v4"/>',
 document:'<path d="M7 3h7l4 4v14H7a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2Z"/><path d="M14 3v5h5M9 12h6M9 16h6"/>',
 pin:'<path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.6"/>',
 sparkle:'<path d="M12 3l1.2 3.8L17 8l-3.8 1.2L12 13l-1.2-3.8L7 8l3.8-1.2L12 3Z"/><path d="M18.5 13l.8 2.2 2.2.8-2.2.8-.8 2.2-.8-2.2-2.2-.8 2.2-.8.8-2.2Z"/>',
 tools:'<path d="m14.6 6.4 3-3a4 4 0 0 1-5 5L6 15l3 3-2 2-5-5 2-2 3 3 6.6-6.6a4 4 0 0 1 1-3Z"/><path d="m14 14 6 6"/>',
 print:'<path d="M7 9V3h10v6M7 18H5a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"/><rect x="7" y="14" width="10" height="7" rx="1"/>',
 swap:'<path d="M4 7h13l-3-3M20 17H7l3 3M17 4l3 3-3 3M7 14l-3 3 3 3"/>',
 bulb:'<path d="M9 18h6M10 22h4"/><path d="M8.5 15.5A7 7 0 1 1 15.5 15.5c-.9.7-1.5 1.5-1.5 2.5h-4c0-1-.6-1.8-1.5-2.5Z"/>'
};
const apps=[
 {key:'planning',label:'Planning',title:'Planning collectif',theme:'blue',icon:'calendar'},
 {key:'personal',label:'Mon planning',title:'Mon planning',theme:'cyan',icon:'personal'},
 {key:'team',label:'Équipe',title:'Esprit d’équipe',theme:'purple',icon:'team'},
 {key:'contacts',label:'Contacts',title:'Contacts',theme:'mint',icon:'contacts'},
 {key:'procedures',label:'Procédures',title:'Procédures',theme:'navy',icon:'document'},
 {key:'landmarks',label:'Repères',title:'Repères terrain',theme:'coral',icon:'pin'},
 {key:'newcomers',label:'Nouveaux',title:'Nouveaux arrivants',theme:'lime',icon:'sparkle'},
 {key:'tools',label:'Outils',title:'Outils équipe',theme:'navy',icon:'tools'},
 {key:'print',label:'Imprimer',title:'Imprimer mon planning',theme:'sun',icon:'print'},
 {key:'ideas',label:'Idées',title:'Boîte à idées',theme:'purple',icon:'bulb'},
 {key:'swap',label:'Échanger',title:'Demande de changement',theme:'rose',icon:'swap'}
];
const byKey=new Map(apps.map(x=>[x.key,x]));
const defaults={grid:['planning','procedures','landmarks','newcomers','tools','print','ideas'],dock:['personal','team','contacts','swap']};
function token(){return localStorage.getItem(STORAGE)||''}
async function data(action,body={}){const r=await fetch(DATA_API,{method:'POST',headers:{'Content-Type':'application/json','X-STIP-Session':token()},body:JSON.stringify({action,...body})});const j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw new Error(j.error||`Erreur ${r.status}`);return j}
async function calendar(kind){const r=await fetch(CAL_API,{method:'POST',headers:{'Content-Type':'application/json','X-STIP-Session':token()},body:JSON.stringify({kind})});const j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw new Error(j.error||'Calendrier indisponible');return j}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function icon(app){return `<span class="app-icon"><svg viewBox="0 0 24 24" aria-hidden="true">${icons[app.icon]}</svg></span>`}
function appButton(key){const a=byKey.get(key);const b=document.createElement('button');b.type='button';b.className='app';b.dataset.key=key;b.dataset.theme=a.theme;b.innerHTML=`${icon(a)}<span class="app-label">${a.label}</span>`;b.onclick=()=>editing?toggleFavorite(key):openApp(key);return b}
function readLayout(){try{const x=JSON.parse(localStorage.getItem(LAYOUT)||'null');if(!x)return defaults;const all=new Set(apps.map(a=>a.key));const dock=(x.dock||[]).filter(k=>all.has(k)).slice(0,4);const grid=(x.grid||[]).filter(k=>all.has(k)&&!dock.includes(k));for(const k of all)if(!dock.includes(k)&&!grid.includes(k))grid.push(k);return{grid,dock}}catch{return defaults}}
function render(layout=readLayout()){appsEl.replaceChildren(...layout.grid.map(appButton));dockEl.replaceChildren(...layout.dock.map(appButton))}
function save(){localStorage.setItem(LAYOUT,JSON.stringify({grid:[...appsEl.children].map(x=>x.dataset.key),dock:[...dockEl.children].map(x=>x.dataset.key)}))}
function toggleFavorite(key){const node=document.querySelector(`.app[data-key="${key}"]`);if(!node)return;if(node.parentElement===dockEl){appsEl.appendChild(node);toast('Retiré des favoris')}else{if(dockEl.children.length>=4)appsEl.appendChild(dockEl.lastElementChild);dockEl.appendChild(node);toast('Ajouté aux favoris')}save()}
function toast(msg){clearTimeout(toastTimer);const t=$('#toast');t.textContent=msg;t.classList.add('show');toastTimer=setTimeout(()=>t.classList.remove('show'),1800)}
function fmt(v,opts={weekday:'short',day:'2-digit',month:'short'}){if(!v)return'—';return new Date(String(v).slice(0,10)+'T12:00:00').toLocaleDateString('fr-FR',opts)}
function codeOf(x){return x?.code||'—'}
function nameOf(a){return String(a?.prenom||a?.nom||'Agent').replace(/_/g,' ').trim()}
function openPanel(title,kicker='STIP'){$('#panelTitle').textContent=title;$('#panelKicker').textContent=kicker;panel.classList.add('open');panel.setAttribute('aria-hidden','false');panelBody.innerHTML='<div class="empty">Chargement…</div>'}
function closePanel(){panel.classList.remove('open');panel.setAttribute('aria-hidden','true')}
function rows(items){return `<div class="list">${items.map(x=>`<div class="row"><div class="date">${esc(fmt(x.date))}<small>${esc(String(x.date||''))}</small></div><div class="main"><strong>${esc(x.label||x.agents?.nom||x.agent_source_key||'')}</strong>${x.observation?`<small>${esc(x.observation)}</small>`:''}</div><span class="chip">${esc(codeOf(x))}</span></div>`).join('')}</div>`}
async function openPersonal(print=false){openPanel(print?'Imprimer mon planning':'Mon planning',print?'IMPRESSION':'PERSONNEL');try{const r=await data('personal'),items=r.items||[];const today=new Date().toISOString().slice(0,10);const future=items.filter(x=>x.date>=today).slice(0,20);panelBody.innerHTML=`<section class="hero-card"><small>PLANNING PERSONNEL</small><h3>${future.length?esc(codeOf(future[0]))+' · '+esc(fmt(future[0].date,{weekday:'long',day:'numeric',month:'long'})):'Aucun service futur'}</h3><p>${future.length?'Données lues directement dans STIP.':'Aucune donnée à afficher pour le moment.'}</p></section>${rows(future)}<div class="actions">${print?'<button class="action" id="printNow">Imprimer / PDF</button>':'<button class="action" id="iosCal">Ajouter sur iPhone</button><button class="action secondary" id="androidCal">Lien Android</button>'}</div>`;if(print)$('#printNow').onclick=()=>window.print();else{$('#iosCal').onclick=()=>subscribe('personal','ios');$('#androidCal').onclick=()=>subscribe('personal','android')}}catch(e){panelBody.innerHTML=`<div class="card"><h3>Connexion nécessaire</h3><p>${esc(e.message)}. Reviens sur STIP et reconnecte-toi.</p><div class="actions"><button class="action" onclick="location.href='index.html'">Ouvrir STIP</button></div></div>`}}
async function openOfficial(){openPanel('Planning collectif','ÉQUIPE');try{const r=await data('official'),items=r.items||[];const today=new Date().toISOString().slice(0,10);const next=items.filter(x=>x.date>=today).slice(0,60);panelBody.innerHTML=`<section class="hero-card"><small>PLANNING OFFICIEL · ${esc(r.team||'ÉQUIPE')}</small><h3>${next.length} lignes à venir</h3><p>Données réelles de la base STIP.</p></section>${rows(next)}`;}catch(e){panelBody.innerHTML=`<div class="card"><h3>Indisponible</h3><p>${esc(e.message)}</p></div>`}}
async function openTeam(){openPanel('Esprit d’équipe','AUJOURD’HUI');try{const r=await data('spirit');const today=new Date().toISOString().slice(0,10);const day=(r.planning||[]).filter(x=>x.date===today);const notices=[...(r.formations||[]).filter(x=>String(x.date_debut).slice(0,10)===today).map(x=>`Formation : ${x.intitule||''}`),...(r.stagiaires||[]).filter(x=>today>=x.date_debut&&today<=x.date_fin).map(x=>`Stagiaire : ${[x.prenom,x.nom].filter(Boolean).join(' ')}`)];panelBody.innerHTML=`<section class="hero-card"><small>ÉQUIPE DU JOUR</small><h3>${day.length} agent${day.length>1?'s':''} affiché${day.length>1?'s':''}</h3><p>${notices.length?esc(notices.join(' · ')):'Aucune information particulière.'}</p></section>${rows(day)}<div class="actions"><button class="action" id="iosTeam">Ajouter sur iPhone</button><button class="action secondary" id="androidTeam">Lien Android</button></div>`;$('#iosTeam').onclick=()=>subscribe('team','ios');$('#androidTeam').onclick=()=>subscribe('team','android')}catch(e){panelBody.innerHTML=`<div class="card"><p>${esc(e.message)}</p></div>`}}
async function openContacts(){openPanel('Contacts','RÉPERTOIRE');try{const r=await data('agents'),items=r.items||[];panelBody.innerHTML=`<div class="card"><h3>${items.length} contacts STIP</h3><p>Répertoire lu depuis les données accessibles à ta session.</p></div><div class="list">${items.slice(0,120).map(a=>`<div class="row"><div class="date">${esc((a.nom||a.source_key||'A').slice(0,1).toUpperCase())}</div><div class="main"><strong>${esc(a.nom||a.source_key||'Agent')}</strong><small>${esc(a.email||a.role||'')}</small></div><span class="chip">›</span></div>`).join('')}</div>`}catch(e){panelBody.innerHTML=`<div class="card"><p>${esc(e.message)}</p></div>`}}
async function openSwap(){openPanel('Demande de changement','PLANNING');try{bootstrap=bootstrap||await data('bootstrap');const personal=bootstrap.personal||[];const future=personal.filter(x=>x.date>=new Date().toISOString().slice(0,10)).slice(0,100);panelBody.innerHTML=`<div class="card"><h3>Préparer une demande</h3><p>Cette version test utilise le même moteur STIP, mais l’envoi final reste volontairement dans le module principal pour éviter une mauvaise manipulation pendant le test.</p><div class="actions"><button class="action" id="openMainChange">Ouvrir le module réel</button></div></div>${rows(future.slice(0,10))}`;$('#openMainChange').onclick=()=>location.href='index.html'}catch(e){panelBody.innerHTML=`<div class="card"><p>${esc(e.message)}</p></div>`}}
function openGeneric(key){const a=byKey.get(key);openPanel(a.title,'STIP');if(key==='newcomers'){panelBody.innerHTML=`<div class="card"><h3>Parcours d’intégration</h3><p>Le site Nouvel Agent est déjà relié à STIP.</p><div class="actions"><button class="action" id="newAgent">Ouvrir le parcours</button><button class="action secondary" id="newFollow">Ouvrir mon suivi</button></div></div>`;$('#newAgent').onclick=()=>location.href='https://nouvel-agent.esapin.com/';$('#newFollow').onclick=()=>location.href='https://nouvel-agent.esapin.com/suivi.html';return}panelBody.innerHTML=`<div class="card"><h3>${esc(a.title)}</h3><p>Le contenant est prêt dans cette nouvelle interface. Ce module n’a pas encore de source de données autonome suffisamment propre pour être branché sans inventer de contenu.</p></div>`}
function openApp(key){activeKey=key;if(key==='personal')return openPersonal(false);if(key==='planning')return openOfficial();if(key==='team')return openTeam();if(key==='contacts')return openContacts();if(key==='print')return openPersonal(true);if(key==='swap')return openSwap();openGeneric(key)}
async function subscribe(kind,platform){try{const r=await calendar(kind);if(platform==='ios'){location.href=r.webcal_url;return}await navigator.clipboard.writeText(r.https_url);toast('Lien calendrier copié')}catch(e){toast(e.message)}}
async function hydrate(){const now=new Date();$('#todayDay').textContent=now.toLocaleDateString('fr-FR',{day:'2-digit'});$('#todayMonth').textContent=now.toLocaleDateString('fr-FR',{month:'short'}).replace('.','').toUpperCase();if(!token()){$('#connectionState').textContent='Session STIP absente · données fictives limitées';$('#todayTitle').textContent='Connecte-toi à STIP pour activer les données';$('#todaySub').textContent='Le design reste testable sans connexion.';return}try{bootstrap=await data('bootstrap');const a=bootstrap.agent||{};$('#hello').textContent='Bonjour '+nameOf(a);$('#connectionState').textContent='Données STIP connectées';const today=now.toISOString().slice(0,10),personal=bootstrap.personal||[];const current=personal.find(x=>x.date===today);const next=personal.find(x=>x.date>today);if(current){$('#todayKicker').textContent=`AUJOURD’HUI · ${codeOf(current)}`;$('#todayTitle').textContent=`Service ${codeOf(current)}`;$('#todaySub').textContent=current.observation||'Planning personnel à jour.'}else{$('#todayKicker').textContent='AUJOURD’HUI';$('#todayTitle').textContent='Pas de service prévu aujourd’hui';$('#todaySub').textContent=next?`Prochain : ${codeOf(next)} · ${fmt(next.date)}`:'Aucun service futur trouvé.'}if(next){$('#nextShift').textContent=codeOf(next);$('#nextShiftDate').textContent=fmt(next.date,{weekday:'long',day:'numeric',month:'short'})}data('spirit').then(r=>{const count=(r.planning||[]).filter(x=>x.date===today).length;$('#teamCount').textContent=count;$('#teamLabel').textContent=count?`${count} présent${count>1?'s':''}`:'Aucune ligne aujourd’hui'}).catch(()=>{})}catch(e){$('#connectionState').textContent='Session STIP à reconnecter';$('#todayTitle').textContent='Connexion requise';$('#todaySub').textContent='Ouvre STIP puis reviens dans Test.'}}
$('#todayWidget').onclick=()=>openPersonal(false);$('#todayWidget').onkeydown=e=>{if(e.key==='Enter'||e.key===' ')openPersonal(false)};document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openApp(b.dataset.open));$('#panelBack').onclick=closePanel;$('#panelRefresh').onclick=()=>openApp(activeKey);$('#editBtn').onclick=()=>{editing=true;home.classList.add('editing');$('#editBtn').hidden=true;$('#doneBtn').hidden=false;toast('Touchez une application pour la déplacer vers/depuis le dock')};$('#doneBtn').onclick=()=>{editing=false;home.classList.remove('editing');$('#editBtn').hidden=false;$('#doneBtn').hidden=true};$('#paletteBtn').onclick=()=>openSheet();function openSheet(){$('#backdrop').hidden=false;$('#wallpaperSheet').classList.add('open');$('#wallpaperSheet').setAttribute('aria-hidden','false')}function closeSheet(){$('#wallpaperSheet').classList.remove('open');$('#wallpaperSheet').setAttribute('aria-hidden','true');setTimeout(()=>$('#backdrop').hidden=true,250)}document.querySelectorAll('[data-close-sheet]').forEach(b=>b.onclick=closeSheet);$('#backdrop').onclick=closeSheet;document.querySelectorAll('[data-wall]').forEach(b=>b.onclick=()=>{document.body.dataset.wallpaper=b.dataset.wall;localStorage.setItem(WALL,b.dataset.wall);closeSheet()});document.body.dataset.wallpaper=localStorage.getItem(WALL)||'sunset';render();hydrate();
})();
