(()=>{"use strict";
const CSS="tomorrow-hub.css?v=20260920-access6";let page=null,opened=false,scrollLock="",selectedDay="";
function core(){return window.STIPTomorrow}
function remote(){return window.STIPTomorrowRemote}
function notice(msg){try{window.STIPToast?.show?.(msg)}catch{}if(!window.STIPToast?.show)window.alert?.(msg)}
async function taskSave(day,item){const c=core(),r=remote(),next={...item};if(!next.id)next.id="td-"+Date.now()+"-"+Math.random().toString(36).slice(2,7);if(r?.taskUpsert){try{await r.taskUpsert(day,next);return true}catch(e){if(next.remoteId){notice(e?.message||"Synchronisation impossible.");return false}}}c.upsert(day,next);return true}
async function taskToggle(day,id){const c=core(),item=c.tasks(day).find(x=>x.id===id);if(!item)return;if(item.remoteId&&remote()?.taskStatus){try{return await remote().taskStatus(day,item,!item.done)}catch(e){notice(e?.message||"Synchronisation impossible.");return}}c.toggle(day,id)}
async function taskDelete(day,id){const c=core(),item=c.tasks(day).find(x=>x.id===id);if(!item)return;if(item.remoteId&&remote()?.taskDelete){try{return await remote().taskDelete(day,item)}catch(e){notice(e?.message||"Suppression impossible.");return}}c.remove(day,id)}
async function taskNext(day,id){const c=core(),item=c.tasks(day).find(x=>x.id===id);if(!item)return;if(item.remoteId&&remote()?.taskMoveNext){try{return await remote().taskMoveNext(day,item)}catch(e){notice(e?.message||"Report impossible.");return}}c.moveNext(day,id)}
async function taskOrder(day,ids){const rows=core().tasks(day),hasRemote=rows.some(x=>x.remoteId);if(hasRemote&&remote()?.taskReorder){try{return await remote().taskReorder(day,ids)}catch(e){notice(e?.message||"Réorganisation impossible.");return}}core().reorder(day,ids)}
function canUse(){if(window.STIPAccess?.app)return!!window.STIPAccess.app("tomorrow");const p={...(window.STIPSession?.permissions||{}),...(window.STIPBootCache?.permissions||{})};return!!p.tomorrow}
function disable(){document.querySelectorAll("#homeView [data-td-card]").forEach(x=>x.remove());if(page&&!page.hidden){page.hidden=true;unlock()}}
function ensureCss(){if(document.querySelector('link[data-td-css]'))return;const l=document.createElement("link");l.rel="stylesheet";l.href=CSS;l.dataset.tdCss="1";document.head.appendChild(l)}
function codeClass(c){return"code-"+String(c||"none").toLowerCase().replace(/[^a-z0-9]/g,"")}
function openTasks(s){return s.tasks.filter(x=>!x.done)}
function warning(s){return s.insights.find(x=>x.level==="warning")}
function activeDay(){const c=core();if(!c)return"";const min=c.tomorrow();if(!selectedDay||selectedDay<min)selectedDay=min;return selectedDay}
function isTomorrow(day=activeDay()){const c=core();return!!c&&day===c.tomorrow()}
function setDay(day){const c=core();if(!c)return;const min=c.tomorrow(),next=String(day||"").slice(0,10);selectedDay=!next||next<min?min:next;renderPage()}
function navDays(){const c=core(),current=activeDay(),days=c.futureDays(8);if(current&&!days.includes(current))days.push(current);return days}
function dayNavHtml(){const c=core(),current=activeDay();return '<section class="td-day-nav"><div class="td-day-strip" aria-label="Jours à venir">'+navDays().map(day=>{const s=c.snapshot(day),d=c.dateObj(day),dow=d.toLocaleDateString("fr-FR",{weekday:"short"}).replace(/\./g,"").toUpperCase(),count=s.events.length+s.tasks.filter(x=>!x.done).length,code=s.shift.code==="—"?"—":s.shift.code;return '<button type="button" data-day="'+c.esc(day)+'" class="'+(day===current?"on":"")+'" aria-label="'+c.esc(c.fullDate(day))+'"><small>'+c.esc(dow)+'</small><b>'+d.getDate()+'</b><em>'+c.esc(code)+'</em>'+(count?'<i>'+count+'</i>':"")+'</button>'}).join("")+'</div><button class="td-date-pick" type="button" data-pick-date aria-label="Choisir une date">Date</button></section>'}
function reassurance(s){const warnings=s.insights.filter(x=>x.level==="warning").length,open=openTasks(s).length;if(s.shift.rest&&!s.events.length&&!open)return"Rien ne ressort : repos, aucun rendez-vous et rien à préparer.";if(warnings)return warnings+" point"+(warnings>1?"s":"")+" peut"+(warnings>1?"vent":"")+" vraiment changer ta journée.";if(s.shift.code==="—")return"Le planning manque : c’est le seul point à vérifier pour l’instant.";if(!s.insights.length)return"Rien d’utile à signaler pour l’instant.";return"Pas d’alerte terrain détectée pour l’instant."}
function insightHtml(x){const c=core();return '<article class="td-insight"><i>'+c.esc(x.icon)+'</i><div><strong>'+c.esc(x.title)+'</strong><p>'+c.esc(x.text)+'</p></div></article>'}
function eventHtml(x){const c=core(),time=x.time||"—",sub=[x.type,x.place].filter(Boolean).join(" · ");return '<article class="td-row"><div class="td-row-time">'+c.esc(time)+'</div><div><strong>'+c.esc(x.title)+'</strong><small>'+c.esc(sub||"Élément STIP")+'</small></div><span class="td-tag">STIP</span></article>'}
function taskHtml(x){const c=core();return '<article class="td-task '+(x.done?"done":"")+'" data-task-id="'+c.esc(x.id)+'"><div class="td-task-main"><button class="td-drag" type="button" data-drag aria-label="Déplacer">⋮⋮</button><div class="td-task-time">'+c.esc(x.time||"—")+'</div><div class="td-copy"><strong>'+c.esc(x.title)+'</strong>'+(x.note?'<small>'+c.esc(x.note)+'</small>':"")+'</div><button class="td-edit" type="button" data-edit aria-label="Modifier">✎</button><button class="td-check" type="button" data-check aria-label="'+(x.done?"Rouvrir":"Terminer")+'">'+(x.done?"✓":"")+'</button></div></article>'}
function renderPage(){if(!page||page.hidden||!core())return;const c=core(),day=activeDay(),s=c.snapshot(day),openCount=openTasks(s).length,tom=isTomorrow(day),sectionLabel=tom?"Analyse de demain":"Analyse de la journée",heroLabel=tom?"DEMAIN EN BREF":"JOURNÉE EN BREF",returnBtn=tom?"":'<button class="td-back-tomorrow" type="button" data-tomorrow>↩ Revenir à demain</button>';page.innerHTML='<header class="td-head"><button type="button" data-close aria-label="Retour">‹</button><div class="td-title"><small>POUR DEMAIN</small><h2>'+c.esc(s.fullDate)+'</h2></div><button type="button" data-minimize aria-label="Minimiser">—</button><button class="add" type="button" data-add aria-label="Ajouter">+</button></header><main class="td-body">'+returnBtn+dayNavHtml()+'<section class="td-hero '+codeClass(s.shift.code)+'"><div class="td-hero-top"><div><div class="td-kicker">'+heroLabel+'</div><h1>'+c.esc(s.shift.label)+'</h1><div class="td-time">'+c.esc(s.shift.time||"Horaire à confirmer")+'</div></div><div class="td-shift">'+c.esc(s.shift.code)+'<small>'+c.esc(s.shift.rest?"REPOS":"SHIFT")+'</small></div></div><p class="td-reassure">'+c.esc(reassurance(s))+'</p><div class="td-stats"><span><b>'+s.events.length+'</b><small>événement'+(s.events.length>1?"s":"")+'</small></span><span><b>'+openCount+'</b><small>à faire</small></span><span><b>'+s.insights.filter(x=>x.level==="warning").length+'</b><small>attention</small></span></div></section><details class="td-section" open><summary>'+sectionLabel+'</summary><div class="td-content">'+(s.insights.length?s.insights.map(insightHtml).join(""):'<p class="td-empty">Aucun signal particulier.</p>')+'</div></details><details class="td-section" open><summary>Horaire & rendez-vous</summary><div class="td-content">'+(s.events.length?s.events.map(eventHtml).join(""):'<p class="td-empty">Aucun rendez-vous détecté pour cette journée.</p>')+'</div></details><details class="td-section" open><summary>Notes & préparation</summary><div class="td-content" data-task-list>'+(s.tasks.length?s.tasks.map(taskHtml).join(""):'<p class="td-empty">Ajoute ce que tu veux préparer, emmener ou faire ce jour-là.</p>')+'<button class="td-add-inline" type="button" data-add>+ Ajouter quelque chose</button></div></details></main>';bindPage();window.dispatchEvent(new CustomEvent("stip:tomorrow-page",{detail:{day}}))}
function bindPage(){if(!page)return;page.querySelector("[data-close]")?.addEventListener("click",close);page.querySelector("[data-minimize]")?.addEventListener("click",minimize);page.querySelector("[data-tomorrow]")?.addEventListener("click",()=>setDay(core().tomorrow()));page.querySelector("[data-pick-date]")?.addEventListener("click",pickDateSheet);page.querySelectorAll("[data-day]").forEach(b=>b.addEventListener("click",()=>setDay(b.dataset.day)));page.querySelectorAll("[data-add]").forEach(b=>b.addEventListener("click",()=>editSheet()));page.querySelectorAll(".td-task").forEach(bindTask)}
function bindTask(row){const id=row.dataset.taskId,day=activeDay();row.querySelector("[data-check]")?.addEventListener("click",()=>taskToggle(day,id));row.querySelector("[data-edit]")?.addEventListener("click",()=>editSheet(id));bindDrag(row)}
function bindDrag(row){const h=row.querySelector("[data-drag]");if(!h)return;let active=false;h.addEventListener("pointerdown",e=>{active=true;e.preventDefault();h.setPointerCapture?.(e.pointerId);row.style.opacity=".72"});h.addEventListener("pointermove",e=>{if(!active)return;const list=row.parentElement,others=[...list.querySelectorAll(".td-task")].filter(x=>x!==row),target=others.find(x=>e.clientY<x.getBoundingClientRect().top+x.getBoundingClientRect().height/2);target?list.insertBefore(row,target):list.insertBefore(row,list.querySelector(".td-add-inline"))});const end=()=>{if(!active)return;active=false;row.style.opacity="";const ids=[...row.parentElement.querySelectorAll(".td-task")].map(x=>x.dataset.taskId);taskOrder(activeDay(),ids)};h.addEventListener("pointerup",end);h.addEventListener("pointercancel",end)}
function pickDateSheet(){const c=core(),wrap=document.createElement("div");wrap.className="td-sheet-wrap";wrap.innerHTML='<section class="td-sheet"><h3>Choisir un jour futur</h3><form class="td-form"><label>Date<input name="day" type="date" min="'+c.esc(c.tomorrow())+'" value="'+c.esc(activeDay())+'" required></label><div class="td-actions"><button type="button" data-cancel>Annuler</button><button class="primary" type="submit">Afficher</button></div></form></section>';document.body.appendChild(wrap);const closeSheet=()=>wrap.remove();wrap.addEventListener("click",e=>{if(e.target===wrap)closeSheet()});wrap.querySelector("[data-cancel]")?.addEventListener("click",closeSheet);wrap.querySelector("form").addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.currentTarget);setDay(f.get("day"));closeSheet()})}
function editSheet(id=""){const c=core(),day=activeDay(),item=c.tasks(day).find(x=>x.id===id)||{title:"",time:"",note:""},wrap=document.createElement("div"),when=isTomorrow(day)?"pour demain":"pour "+c.shortDate(day);wrap.className="td-sheet-wrap";wrap.innerHTML='<section class="td-sheet"><h3>'+(id?"Modifier":"Ajouter "+when)+'</h3><form class="td-form"><label>Ce qu’il faut faire<input name="title" maxlength="120" required value="'+c.esc(item.title)+'" placeholder="Ex. prendre un document"></label><label>Heure facultative<input name="time" type="time" value="'+c.esc(item.time)+'"></label><label>Note facultative<textarea name="note" maxlength="300" placeholder="Détail utile">'+c.esc(item.note)+'</textarea></label><div class="td-actions"><button type="button" data-cancel>Annuler</button><button class="primary" type="submit">Enregistrer</button></div></form>'+(id?'<button class="secondary" type="button" data-next>Reporter au jour suivant</button><button class="secondary danger" type="button" data-remove>Supprimer</button>':"")+'</section>';document.body.appendChild(wrap);const closeSheet=()=>wrap.remove();wrap.addEventListener("click",e=>{if(e.target===wrap)closeSheet()});wrap.querySelector("[data-cancel]")?.addEventListener("click",closeSheet);wrap.querySelector("form").addEventListener("submit",async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form),submit=form.querySelector('[type="submit"]');submit.disabled=true;submit.textContent="Enregistrement…";const ok=await taskSave(day,{...item,id:id||undefined,title:f.get("title"),time:f.get("time"),note:f.get("note")});if(ok)closeSheet();else{submit.disabled=false;submit.textContent="Enregistrer"}});wrap.querySelector("[data-remove]")?.addEventListener("click",async()=>{await taskDelete(day,id);closeSheet()});wrap.querySelector("[data-next]")?.addEventListener("click",async()=>{await taskNext(day,id);closeSheet()});setTimeout(()=>wrap.querySelector('[name="title"]')?.focus(),40)}
function lock(){if(opened)return;opened=true;scrollLock=document.documentElement.style.overflow;document.documentElement.style.overflow="hidden"}
function unlock(){opened=false;document.documentElement.style.overflow=scrollLock}
function open(){if(!canUse())return;ensureCss();if(!selectedDay&&core())selectedDay=core().tomorrow();if(!page){page=document.createElement("section");page.className="td-page";page.id="tdPage";document.body.appendChild(page)}page.hidden=false;lock();renderPage()}
function close(){if(page)page.hidden=true;unlock()}
function minimize(){if(page)page.hidden=true;unlock()}
function refresh(){if(!canUse()){disable();return}ensureCss();if(page&&!page.hidden)renderPage()}
["stip:home-rendered","stip:boot-updated","stip:tomorrow-updated","stip:tomorrow-ready","stip:permissions-live","stip:session-ready"].forEach(n=>window.addEventListener(n,()=>setTimeout(refresh,0)));document.addEventListener("keydown",e=>{if(e.key==="Escape"&&page&&!page.hidden)close()});setTimeout(refresh,120);
window.STIPTomorrowUI={open,close,minimize,refresh};
})();