(()=>{'use strict';
const URL='https://yzsrmuxghlengnkyphxj.supabase.co';
const API={access:`${URL}/functions/v1/stip-access`,data:`${URL}/functions/v1/stip-data`};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={token:localStorage.getItem('stip_session_v2')||'',me:null,boot:null,view:'home'};
const parisISO=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Paris',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
async function post(url,body){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',...(state.token?{'x-stip-session':state.token}:{})},body:JSON.stringify(body)}),j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw Error(j.error||`Erreur ${r.status}`);return j}
const fmtDate=v=>{if(!v)return'—';const d=new Date(String(v).length===10?v+'T12:00:00':v);return d.toLocaleDateString('fr-FR',{weekday:'short',day:'numeric',month:'short'})};
const fmtName=a=>[a?.prenom,a?.nom].filter(Boolean).join(' ')||'Utilisateur';
const teamLabel=t=>t==='nuit'?'Équipe nuit':t==='chefs'?'Chefs d’équipe':'Équipe jour';
function loginMode(msg=''){$('#loginView').classList.remove('hidden');$('#appView').classList.add('hidden');$('#loginMsg').textContent=msg}
function appMode(){$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden')}
async function session(){if(!state.token)return loginMode();try{state.me=await post(API.access,{action:'me'});state.boot=await post(API.data,{action:'bootstrap'});appMode();renderHome()}catch{localStorage.removeItem('stip_session_v2');state.token='';loginMode('Session expirée. Entre ton code.')}}
async function login(code){const j=await post(API.access,{action:'login',code});state.token=j.session_token;state.me=j;localStorage.setItem('stip_session_v2',state.token);state.boot=await post(API.data,{action:'bootstrap'});appMode();renderHome()}
async function logout(){try{await post(API.access,{action:'logout'})}catch{}localStorage.removeItem('stip_session_v2');location.reload()}
function currentShift(){const today=parisISO();return state.boot?.personal?.find(x=>x.date===today)||null}
function nextShift(){const today=parisISO();return state.boot?.personal?.find(x=>x.date>=today&&!/^(RH|RTT|RC|CA|AA|MA|RF|RTa|SYR)$/i.test(x.code||''))||null}
function permitted(k){const p=state.boot?.permissions||state.me?.permissions||{};if(['home','planning','requests','profile'].includes(k))return true;if(k==='team')return !!p.equipe_contacts||!!p.responsable;if(k==='info')return true;if(k==='manager')return !!p.responsable||/chef|cadre|responsable/i.test(state.me?.agent?.role||'');return !!p[k]}
function setTitle(t){$('#viewTitle').textContent=t}
function route(v){state.view=v;$$('[data-view-panel]').forEach(x=>x.classList.add('hidden'));const target=$(`[data-view-panel="${v}"]`)||$('[data-view-panel="home"]');target.classList.remove('hidden');if(v==='home')renderHome();if(v==='planning')renderPlanning();if(v==='team')renderTeam();if(v==='requests')renderRequests();if(v==='info')renderInfo();if(v==='profile')renderProfile();if(v==='manager')renderManager();window.scrollTo({top:0,behavior:'smooth'})}
function renderHome(){const a=state.boot?.agent||state.me?.agent||{},today=currentShift(),next=nextShift();$('#hello').textContent=fmtName(a);$('#teamName').textContent=teamLabel(state.boot?.team);$('#todayCode').textContent=today?.code||'Repos';$('#todayMeta').textContent=today?`${fmtDate(today.date)}${today.observation?' · '+today.observation:''}`:'Aucun poste aujourd’hui';$('#nextCode').textContent=next?.code||'—';$('#nextMeta').textContent=next?`${fmtDate(next.date)}${next.observation?' · '+next.observation:''}`:'Aucun prochain poste trouvé';const defs=[['planning','PL','Planning','Mon mois et mes horaires'],['team','EQ','Équipe','Qui travaille et contacts'],['requests','DE','Demandes','Échange ou changement'],['info','IN','Infos','Stagiaires et formations'],['profile','PR','Profil','Mes informations'],['manager','CH','Gestion chef','Demandes et suivi équipe']],grid=$('#navGrid');grid.innerHTML=defs.filter(x=>permitted(x[0])).map(([k,i,t,s])=>`<button class="nav-card" data-nav="${k}"><span class="icon">${i}</span><strong>${t}</strong><span>${s}</span></button>`).join('');grid.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>route(b.dataset.nav))}
function monthItems(){const rows=state.boot?.personal||[],ym=parisISO().slice(0,7);return rows.filter(x=>x.date?.startsWith(ym))}
function renderPlanning(){setTitle('Mon planning');const rows=monthItems(),today=parisISO(),[y,m]=today.split('-').map(Number),first=new Date(y,m-1,1),days=new Date(y,m,0).getDate(),offset=(first.getDay()+6)%7,by=Object.fromEntries(rows.map(x=>[Number(x.date.slice(-2)),x]));let cells='';for(let i=0;i<offset;i++)cells+='<div class="day off"></div>';for(let d=1;d<=days;d++){const x=by[d];cells+=`<div class="day"><b>${d}</b><strong>${esc(x?.code||'—')}</strong></div>`}const label=new Intl.DateTimeFormat('fr-FR',{timeZone:'Europe/Paris',month:'long',year:'numeric'}).format(new Date());$('#planningBody').innerHTML=`<div class="panel-head"><div><span class="eyebrow">${esc(label)}</span><h2>Planning individuel</h2></div></div><div class="calendar">${cells}</div>`}
async function renderTeam(){setTitle('Mon équipe');const body=$('#teamBody');body.innerHTML='<div class="empty">Chargement…</div>';try{const j=await post(API.data,{action:'spirit'}),today=parisISO(),rows=(j.planning||[]).filter(x=>x.date===today&&!/^(RH|RTT|RC|CA|AA|MA|RF|RTa|SYR)$/i.test(x.code||''));body.innerHTML=`<div class="panel-head"><div><span class="eyebrow">Aujourd’hui</span><h2>${rows.length} présent(s)</h2></div></div><div class="list">${rows.map(x=>`<div class="row"><div class="row-main"><strong>${esc(fmtName(x.agents))}</strong><small>${esc(x.agents?.ghe||'')}</small></div><span class="badge">${esc(x.code||'')}</span></div>`).join('')||'<div class="empty">Aucun agent trouvé aujourd’hui.</div>'}</div>`}catch(e){body.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
async function renderRequests(){setTitle('Mes demandes');const body=$('#requestsBody');body.innerHTML='<div class="empty">Chargement…</div>';try{const h=await post(API.data,{action:'change_history'});body.innerHTML=`<div class="form-grid"><label>Type<select id="reqType"><option value="change">Changement</option><option value="exchange">Échange</option><option value="other">Autre</option></select></label><label>Date<input id="reqDate" type="date"></label><label>Code souhaité<input id="reqCode" maxlength="20" placeholder="Ex. J4"></label><label>Message<textarea id="reqMsg" rows="4" placeholder="Explique brièvement la demande"></textarea></label><button class="primary" id="reqSend">Envoyer la demande</button><div id="reqState" class="status"></div></div><div class="list" style="margin-top:18px">${(h.items||[]).map(x=>`<div class="row"><div class="row-main"><strong>${esc(x.request_type)}</strong><small>${esc(fmtDate(x.date_from))} · ${esc(x.message||'')}</small></div><span class="badge">${esc(x.status)}</span></div>`).join('')||'<div class="empty">Aucune demande.</div>'}</div>`;$('#reqSend').onclick=async()=>{const b=$('#reqSend');b.disabled=true;try{await post(API.data,{action:'change_submit',request_type:$('#reqType').value,date_from:$('#reqDate').value,desired_code:$('#reqCode').value,message:$('#reqMsg').value});$('#reqState').textContent='Demande envoyée.';renderRequests()}catch(e){$('#reqState').textContent=e.message;b.disabled=false}}}catch(e){body.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
async function renderInfo(){setTitle('Informations');const body=$('#infoBody');body.innerHTML='<div class="empty">Chargement…</div>';try{const j=await post(API.data,{action:'spirit'}),items=[...(j.formations||[]).slice(0,8).map(x=>`<div class="row"><div class="row-main"><strong>${esc(x.intitule||'Formation')}</strong><small>${esc(fmtDate(x.date_debut))}${x.lieu?' · '+esc(x.lieu):''}</small></div><span class="badge">Formation</span></div>`),...(j.stagiaires||[]).slice(0,8).map(x=>`<div class="row"><div class="row-main"><strong>${esc(fmtName(x))}</strong><small>${esc(fmtDate(x.date_debut))} → ${esc(fmtDate(x.date_fin))}</small></div><span class="badge">Stagiaire</span></div>`)];body.innerHTML=`<div class="panel-head"><h2>À venir</h2></div><div class="list">${items.join('')||'<div class="empty">Aucune information à venir.</div>'}</div>`}catch(e){body.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function renderProfile(){setTitle('Mon profil');const a=state.boot?.agent||{};$('#profileBody').innerHTML=`<div class="list"><div class="row"><div class="row-main"><strong>${esc(fmtName(a))}</strong><small>${esc(a.role||'Agent')}</small></div></div><div class="row"><div class="row-main"><strong>Équipe</strong><small>${esc(teamLabel(state.boot?.team))}</small></div></div><div class="row"><div class="row-main"><strong>Téléphone</strong><small>${esc(a.telephone||'Non renseigné')}</small></div></div><div class="row"><div class="row-main"><strong>Email</strong><small>${esc(a.email||'Non renseigné')}</small></div></div></div>`}
async function renderManager(){setTitle('Gestion chef');const body=$('#managerBody');body.innerHTML='<div class="empty">Chargement…</div>';try{const j=await post(API.access,{action:'responsable_list_requests'});body.innerHTML=`<div class="panel-head"><div><span class="eyebrow">Équipe</span><h2>Demandes reçues</h2></div></div><div class="list">${(j.items||[]).map(x=>`<div class="row"><div class="row-main"><strong>${esc(x.request_type||'Demande')}</strong><small>${esc(fmtDate(x.date_from))} · ${esc(x.message||'')}</small></div><span class="badge">${esc(x.status||'submitted')}</span></div>`).join('')||'<div class="empty">Aucune demande en attente.</div>'}</div>`}catch(e){body.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const code=$('#code').value.trim(),msg=$('#loginMsg');msg.textContent='Connexion…';try{await login(code)}catch(err){msg.textContent=err.message}});$('#logout').onclick=logout;$$('[data-back]').forEach(b=>b.onclick=()=>route('home'));session();
})();