import 'jsr:@supabase/functions-js/edge-runtime.d.ts'
import { createClient } from 'npm:@supabase/supabase-js@2'
const URL=Deno.env.get('SUPABASE_URL')!, SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!, db=createClient(URL,SERVICE)
async function canonicalSourceKey(raw:string){const key=String(raw||'').trim();if(!key)return key;const {data:alias,error}=await db.from('stip_agent_identity_aliases').select('canonical_agent_id').eq('incoming_source_key',key).eq('active',true).maybeSingle();if(error)throw error;if(!alias?.canonical_agent_id)return key;const {data:agent,error:ae}=await db.from('agents').select('source_key').eq('id',alias.canonical_agent_id).maybeSingle();if(ae)throw ae;return String(agent?.source_key||key)}
const C={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type,x-stip-session','Access-Control-Allow-Methods':'POST,OPTIONS'}
const J=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...C,'Content-Type':'application/json','Cache-Control':'no-store'}})
const hex=(a:ArrayBuffer)=>[...new Uint8Array(a)].map(b=>b.toString(16).padStart(2,'0')).join('')
async function sha256(s:string){return hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))}
async function session(req:Request){const token=req.headers.get('x-stip-session')||'';if(!token)throw new Error('Session STIP requise.');const h=await sha256(token);const {data:s,error}=await db.from('stip_access_sessions').select('profile_id,expires_at,revoked_at').eq('token_hash',h).maybeSingle();if(error)throw error;if(!s||s.revoked_at||new Date(s.expires_at)<=new Date())throw new Error('Session expirée.');const {data:p,error:pe}=await db.from('stip_access_profiles').select('active,permissions,agent_id').eq('id',s.profile_id).maybeSingle();if(pe)throw pe;if(!p?.active)throw new Error('Accès désactivé.');const ok=p.permissions?.agent_directory||p.permissions?.planning_team||p.permissions?.planning_personal||p.permissions?.contacts||p.permissions?.responsable||p.permissions?.admin||p.permissions?.planning;if(!ok)throw new Error('Accès Planning non autorisé.');return p}

function norm(v:unknown){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleUpperCase('fr-FR').replace(/[^A-Z0-9]+/g,' ').trim()}
function splitRefs(v:unknown){return String(v||'').split(/\s*(?:\+|\/|;|&|\bet\b)\s*/i).map(x=>x.trim()).filter(Boolean)}
function refMatches(v:unknown,a:any){const q=norm(v);if(!q)return false;const vals=[a?.source_key,a?.prenom,a?.nom,[a?.prenom,a?.nom].filter(Boolean).join(' '),[a?.nom,a?.prenom].filter(Boolean).join(' ')].map(norm);const parts=String(a?.source_key||'').split('_').filter(Boolean);if(parts.length)vals.push(norm(parts.at(-1)));return vals.includes(q)}
async function extras(a:any,full:boolean){const today=new Date();today.setDate(today.getDate()-31);const from=today.toISOString().slice(0,10),future=new Date();future.setDate(future.getDate()+370);const to=future.toISOString().slice(0,10);const [ag,fr,st]=await Promise.all([
  db.from('stip_agent_agenda_items').select('id,display_mode,title,body,event_date,all_day,start_time,end_time,location,importance,source_type,event_kind,icon,updated_at').eq('agent_id',a.id).eq('status','active').gte('event_date',from).lte('event_date',to).order('event_date').order('start_time'),
  db.from('formations').select('id,intitule,date_debut,date_fin,lieu,statut,horaire,updated_at').eq('agent_source_key',a.source_key).gte('date_fin',from+'T00:00:00Z').lte('date_debut',to+'T23:59:59Z').order('date_debut'),
  db.from('stagiaires').select('id,nom,prenom,date_debut,date_fin,horaires,referent,observation,updated_at').gte('date_fin',from).lte('date_debut',to).order('date_debut')
]);if(ag.error)throw ag.error;if(fr.error)throw fr.error;if(st.error)throw st.error;
const agenda=(ag.data||[]).map((x:any)=>{if(full)return x;const medical=/medical|mobi_lit|visite/i.test(String(x.source_type||''));return{...x,title:medical?'Rendez-vous':x.title,body:null,location:medical?null:x.location,icon:medical?'📅':x.icon,event_kind:medical?'rendezvous':x.event_kind,source_type:medical?'private_appointment':x.source_type}});
return{agenda_items:agenda,personal_formations:fr.data||[],personal_stagiaires:(st.data||[]).filter((x:any)=>splitRefs(x.referent).some((r:string)=>refMatches(r,a)))}}

async function shiftDefinitions(){
  const {data,error}=await db.from('stip_shift_registry')
    .select('code,base_code,label,start_time,end_time,icon,sort_order,color_hex,soft_color_hex,on_color_hex,kind,family,is_working,schedule_mode,window_start,window_end,duration_minutes,source_label')
    .order('sort_order').order('code');
  if(error)throw error;
  return data||[]
}
async function media(){const {data,error}=await db.from('media_assets').select('kind,agent_source_key,code,storage_path,metadata').eq('active',true).in('kind',['avatar_agent','shift']);if(error)throw error;const avatars:Record<string,string>={},shifts:Record<string,string>={};for(const x of data||[]){const bucket=String(x?.metadata?.bucket||'ghe-media');const {data:s}=await db.storage.from(bucket).createSignedUrl(x.storage_path,3600);if(!s?.signedUrl)continue;if(x.kind==='avatar_agent'&&x.agent_source_key)avatars[x.agent_source_key]=s.signedUrl;if(x.kind==='shift'&&x.code)shifts[String(x.code).toUpperCase()]=s.signedUrl}return{avatars,shifts}}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:C});if(req.method!=='POST')return J({error:'Méthode non autorisée.'},405);try{const viewer=await session(req);const b=await req.json().catch(()=>({}));const sourceKey=await canonicalSourceKey(String(b.source_key||'').trim());if(!sourceKey)throw new Error('Agent manquant.');const {data:contact,error}=await db.from('contacts_ghe').select('source_key,categorie,ghe,icone,nom,prenom,alias,telephone,email_pro,role_metier').eq('source_key',sourceKey).eq('actif',true).maybeSingle();if(error)throw error;const {data:a,error:ae}=await db.from('agents').select('id,source_key,equipe,type_planning,ghe,telephone,email,nom,prenom,role,profile_photo_url,avatar_url,quotite').eq('source_key',sourceKey).eq('actif',true).maybeSingle();if(ae)throw ae;if(!a&&!contact)throw new Error('Agent introuvable.');const self=Boolean(a&&String(viewer.agent_id||'')===String(a.id)),canViewOthers=Boolean(viewer.permissions?.agent_directory||viewer.permissions?.planning_team||viewer.permissions?.contacts||viewer.permissions?.responsable||viewer.permissions?.admin);if(!self&&!canViewOthers)throw new Error('Accès au planning de cet agent non autorisé.');if(!a&&!viewer.permissions?.contacts&&!viewer.permissions?.responsable&&!viewer.permissions?.admin)throw new Error('Accès au contact non autorisé.');let items:any[]=[],extra:any={agenda_items:[],personal_formations:[],personal_stagiaires:[]};const full=Boolean(self||viewer.permissions?.responsable||viewer.permissions?.admin);if(a){const {data:p,error:pe}=await db.from('planning').select('date,code,observation,equipe,source_value').eq('agent_id',a.id).order('date');if(pe)throw pe;items=p||[];extra=await extras(a,full)}const canContacts=Boolean(viewer.permissions?.contacts||viewer.permissions?.responsable||viewer.permissions?.admin);const safeContact=contact?{...contact,...(!canContacts&&!full?{telephone:null,email_pro:null}:{})}:a;const safeAgent=a?{...a,...(!canContacts&&!full?{telephone:null,email:null}:{})}:a;const canCalendar=Boolean(viewer.permissions?.calendar_subscribe||viewer.permissions?.calendriers),canSubscribeTarget=Boolean(canCalendar&&(self||viewer.permissions?.responsable||viewer.permissions?.admin)),canSubscribeTeam=Boolean(canCalendar&&viewer.permissions?.planning_team);const [mediaData,shiftDefs]=await Promise.all([media(),shiftDefinitions()]);return J({contact:safeContact,agent:safeAgent,items,...extra,media:mediaData,shift_definitions:shiftDefs,viewer:{detail_level:full?'full':'operational',can_manage:Boolean(viewer.permissions?.responsable||viewer.permissions?.admin),can_contacts:canContacts,can_subscribe_target:canSubscribeTarget,can_subscribe_team:canSubscribeTeam,is_self:self}})}catch(e){return J({error:e instanceof Error?e.message:String(e)},400)}})
