import 'jsr:@supabase/functions-js/edge-runtime.d.ts'
import { createClient } from 'npm:@supabase/supabase-js@2'

const URL=Deno.env.get('SUPABASE_URL')!, SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
const db=createClient(URL,SERVICE,{auth:{persistSession:false}})
const ORIGINS=new Set(['https://stip.esapin.com','https://esapin69.github.io'])
const BUCKET='stip-onboarding-documents'
const text=(v:unknown,m=8000)=>String(v??'').trim().slice(0,m)
async function sha(v:string){const a=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return[...new Uint8Array(a)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function shaBytes(b:Uint8Array){const a=await crypto.subtle.digest('SHA-256',b);return[...new Uint8Array(a)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function errText(e:unknown){if(e instanceof Error)return e.message;if(e&&typeof e==='object'&&'message' in e)return String((e as any).message);try{return JSON.stringify(e)}catch{return String(e)}}
function parisToday(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Paris',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),g=(k:string)=>parts.find(x=>x.type===k)?.value||'';return`${g('year')}-${g('month')}-${g('day')}`}
function parisDay(offset=0){const base=parisToday();if(!offset)return base;const d=new Date(base+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+offset);return d.toISOString().slice(0,10)}
function cors(req:Request){const o=req.headers.get('origin')||'',ok=!o||ORIGINS.has(o);return{ok,h:{'Access-Control-Allow-Origin':ok&&o?o:'https://stip.esapin.com','Access-Control-Allow-Headers':'content-type,x-stip-session','Access-Control-Allow-Methods':'POST,OPTIONS','Vary':'Origin'}}}
function json(req:Request,b:unknown,s=200){return new Response(JSON.stringify(b),{status:s,headers:{...cors(req).h,'Content-Type':'application/json','Cache-Control':'no-store'}})}
async function ctx(req:Request){const raw=req.headers.get('x-stip-session')||'';if(!raw)throw Error('SESSION_STIP_REQUISE');const th=await sha(raw),s=await db.from('stip_access_sessions').select('id,profile_id,expires_at,revoked_at').eq('token_hash',th).maybeSingle();if(s.error)throw s.error;if(!s.data||s.data.revoked_at||new Date(s.data.expires_at)<=new Date())throw Error('SESSION_EXPIREE');const p=await db.from('stip_access_profiles').select('id,agent_id,active,permissions').eq('id',s.data.profile_id).maybeSingle();if(p.error)throw p.error;if(!p.data?.active)throw Error('ACCES_DESACTIVE');const a=await db.from('agents').select('id,source_key,nom,prenom,equipe,ghe,role,actif').eq('id',p.data.agent_id).maybeSingle();if(a.error)throw a.error;if(!a.data?.actif)throw Error('AGENT_INACTIF');return{profile:p.data,agent:a.data}}
function canManage(c:any){return Boolean(c.profile.permissions?.responsable||c.profile.permissions?.admin)}
function requireResp(c:any){if(!canManage(c))throw Error('ACCES_RESPONSABLE_REQUIS')}
async function ensureTarget(id:string){const q=await db.from('agents').select('id,source_key,nom,prenom,equipe,ghe,telephone,role').eq('id',id).eq('actif',true).maybeSingle();if(q.error)throw q.error;if(!q.data)throw Error('AGENT_INTROUVABLE');return q.data}
async function notifications(c:any){const q=await db.from('stip_notifications').select('*').eq('agent_id',c.agent.id).order('created_at',{ascending:false}).limit(80);if(q.error)throw q.error;return q.data||[]}
async function listActions(c:any){const q=await db.from('stip_action_requests').select('*').eq('target_agent_id',c.agent.id).eq('status','pending').order('priority',{ascending:false}).order('created_at',{ascending:false}).limit(40);if(q.error)throw q.error;return q.data||[]}
async function actionDetail(c:any,id:string){const q=await db.from('stip_action_requests').select('*').eq('id',id).eq('target_agent_id',c.agent.id).maybeSingle();if(q.error)throw q.error;if(!q.data||q.data.status!=='pending')throw Error('ACTION_INTROUVABLE');const a:any=q.data;if(!a.seen_at){const now=new Date().toISOString();await db.from('stip_action_requests').update({seen_at:now,updated_at:now}).eq('id',id).is('seen_at',null);a.seen_at=now;await db.from('stip_notifications').update({read_at:now}).eq('agent_id',c.agent.id).eq('action_id',id).is('read_at',null)}if(a.source_type==='evaluation_signature'&&a.source_ref){const r=await db.from('stip_evaluation_signature_requests').select('*').eq('id',a.source_ref).maybeSingle();if(r.error)throw r.error;const e=await db.from('stip_agent_evaluations').select('*').eq('id',r.data?.evaluation_id).maybeSingle();if(e.error)throw e.error;a.evaluation=e.data;a.signature_request=r.data}return a}
function png(v:unknown){const s=text(v,450000);if(!/^data:image\/png;base64,[A-Za-z0-9+/=]+$/.test(s))throw Error('SIGNATURE_INVALIDE');const raw=atob(s.split(',')[1]),b=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)b[i]=raw.charCodeAt(i);return b}
async function submitSignature(c:any,b:any){const a=await actionDetail(c,text(b.action_id,80));if(a.kind!=='signature')throw Error('ACTION_NON_SIGNABLE');const req=await db.from('stip_evaluation_signature_requests').select('*').eq('id',a.source_ref).eq('agent_id',c.agent.id).maybeSingle();if(req.error)throw req.error;if(!req.data||req.data.status!=='pending')throw Error('DEMANDE_SIGNATURE_INVALIDE');const bytes=png(b.signature),path=`evaluations/actions/${req.data.evaluation_id}/signatures/agent-${req.data.id}.png`,blob=new Blob([bytes],{type:'image/png'}),up=await db.storage.from(BUCKET).upload(path,blob,{contentType:'image/png',upsert:true});if(up.error)throw Error(errText(up.error));const now=new Date().toISOString(),hash=await shaBytes(bytes);const u=await db.from('stip_evaluation_signature_requests').update({status:'signed',signed_at:now,storage_path:path,signature_hash:hash,updated_at:now}).eq('id',req.data.id).select('*').single();if(u.error){await db.storage.from(BUCKET).remove([path]).catch(()=>{});throw Error(errText(u.error))}return u.data}
async function createAction(c:any,b:any){requireResp(c);const target=text(b.target_agent_id,80),title=text(b.title,180),body=text(b.body,1500),kind=text(b.kind,40)||'request',sourceType=text(b.source_type,60)||'manual',sourceRef=text(b.source_ref,80)||null;if(!target||!title)throw Error('CHAMPS_MANQUANTS');await ensureTarget(target);const r=await db.from('stip_action_requests').insert({kind,target_agent_id:target,requester_agent_id:c.agent.id,source_type:sourceType,source_ref:sourceRef,title,body,priority:Number(b.priority||50),status:'pending',metadata:b.metadata||{}}).select('*').single();if(r.error)throw r.error;await db.from('stip_notifications').insert({agent_id:target,type:'action_required',title,body,action_id:r.data.id,source_type:sourceType,source_ref:sourceRef,metadata:b.metadata||{}});return r.data}
async function sendNotification(c:any,b:any){requireResp(c);const target=text(b.target_agent_id,80),title=text(b.title,180),body=text(b.body,1500);if(!target||!title)throw Error('CHAMPS_MANQUANTS');await ensureTarget(target);const r=await db.from('stip_notifications').insert({agent_id:target,type:'manager_message',title,body,source_type:'manual_message',metadata:{dismissible:true}}).select('*').single();if(r.error)throw r.error;return r.data}
function agendaPayload(b:any){const display_mode=text(b.display_mode,20)==='day_note'?'day_note':'event',event_date=text(b.event_date,10),title=text(b.title,180),body=text(b.body,1800),all_day=display_mode==='day_note'?true:Boolean(b.all_day),start_time=all_day?null:text(b.start_time,8)||null,end_time=all_day?null:text(b.end_time,8)||null,location=text(b.location,240)||null,importance=['normal','important','urgent'].includes(text(b.importance,20))?text(b.importance,20):'normal',event_kind=['rendezvous','formation','reunion','information','autre'].includes(text(b.event_kind,30))?text(b.event_kind,30):'autre',defaults:any={rendezvous:'📅',formation:'🎓',reunion:'👥',information:'ℹ️',autre:'📌'},icon=text(b.icon,24)||defaults[event_kind]||'📌';if(!/^\d{4}-\d{2}-\d{2}$/.test(event_date)||!title)throw Error('AGENDA_CHAMPS_MANQUANTS');if(display_mode==='event'&&!all_day&&(!/^\d{2}:\d{2}/.test(start_time||'')||!/^\d{2}:\d{2}/.test(end_time||'')))throw Error('AGENDA_HORAIRE_REQUIS');return{display_mode,event_date,title,body,all_day,start_time,end_time,location,importance,event_kind,icon}}
async function insertAgenda(c:any,target:string,p:any,sourceType='manual',sourceRef:string|null=null,creatorId:string|null=null){await ensureTarget(target);const q=await db.from('stip_agent_agenda_items').insert({agent_id:target,created_by_agent_id:creatorId||c.agent.id,source_type:sourceType,source_ref:sourceRef,...p,status:'active'}).select('*').single();if(q.error)throw q.error;return q.data}
async function agendaDirect(c:any,b:any){const requested=text(b.target_agent_id,80),target=requested||String(c.agent.id||'');if(!target)throw Error('AGENT_REQUIS');const self=String(target)===String(c.agent.id);if(!self&&!canManage(c))throw Error('ACCES_RESPONSABLE_REQUIS');if(self&&!canManage(c)&&!c.profile.permissions?.planning_personal)throw Error('ACCES_PLANNING_REQUIS');return insertAgenda(c,target,agendaPayload(b),self?'manual_self':'manual_direct',null)}
async function agendaPropose(c:any,b:any){requireResp(c);const target=text(b.target_agent_id,80);if(!target)throw Error('AGENT_REQUIS');const p=agendaPayload(b),when=p.all_day?p.event_date:`${p.event_date} · ${p.start_time}`;return createAction(c,{target_agent_id:target,title:`📅 ${p.title}`,body:[when,p.location].filter(Boolean).join(' · '),kind:'agenda_proposal',source_type:'manual_agenda_proposal',priority:p.importance==='urgent'?90:p.importance==='important'?70:50,metadata:{agenda:p}})}
async function acceptAgenda(c:any,b:any){const a=await actionDetail(c,text(b.action_id,80));if(a.kind!=='agenda_proposal')throw Error('ACTION_INVALIDE');const p=a.metadata?.agenda?agendaPayload(a.metadata.agenda):null;if(!p)throw Error('AGENDA_INVALIDE');const item=await insertAgenda(c,c.agent.id,p,'accepted_proposal',a.id,a.requester_agent_id||null);const now=new Date().toISOString();const u=await db.from('stip_action_requests').update({status:'done',completed_at:now,updated_at:now}).eq('id',a.id).eq('target_agent_id',c.agent.id).eq('status','pending');if(u.error)throw u.error;await db.from('stip_notifications').delete().eq('agent_id',c.agent.id).eq('action_id',a.id);return item}
async function declineAgenda(c:any,b:any){const id=text(b.action_id,80),q=await db.from('stip_action_requests').select('id,kind,status').eq('id',id).eq('target_agent_id',c.agent.id).maybeSingle();if(q.error)throw q.error;if(!q.data||q.data.status!=='pending'||q.data.kind!=='agenda_proposal')throw Error('ACTION_INVALIDE');const now=new Date().toISOString(),u=await db.from('stip_action_requests').update({status:'cancelled',cancelled_at:now,updated_at:now}).eq('id',id);if(u.error)throw u.error;await db.from('stip_notifications').delete().eq('agent_id',c.agent.id).eq('action_id',id);return{ok:true}}
async function dismissNotification(c:any,b:any){const id=text(b.notification_id,80);if(!id)throw Error('NOTIFICATION_REQUISE');const q=await db.from('stip_notifications').delete().eq('id',id).eq('agent_id',c.agent.id).select('id').maybeSingle();if(q.error)throw q.error;if(!q.data)throw Error('NOTIFICATION_INTROUVABLE');return{ok:true}}
async function managerAgents(c:any){requireResp(c);const q=await db.from('agents').select('id,source_key,nom,prenom,equipe,type_planning,role,ghe,telephone').eq('actif',true).order('nom');if(q.error)throw q.error;return q.data||[]}
async function managerAgendaList(c:any){requireResp(c);const q=await db.from('stip_agent_agenda_items').select('*,agent:agents!stip_agent_agenda_items_agent_id_fkey(id,source_key,nom,prenom,equipe,ghe)').eq('created_by_agent_id',c.agent.id).eq('status','active').gte('event_date',parisDay(-1)).order('event_date').order('start_time').limit(120);if(q.error)throw q.error;return q.data||[]}
async function managerAgendaCancel(c:any,b:any){requireResp(c);const id=text(b.id,80),now=new Date().toISOString();const q=await db.from('stip_agent_agenda_items').update({status:'cancelled',updated_at:now}).eq('id',id).eq('created_by_agent_id',c.agent.id).eq('status','active').select('id').maybeSingle();if(q.error)throw q.error;if(!q.data)throw Error('ELEMENT_INTROUVABLE');return{ok:true}}
async function managerList(c:any){requireResp(c);const q=await db.from('stip_action_requests').select('*,target:agents!stip_action_requests_target_agent_id_fkey(id,nom,prenom,source_key,equipe,role)').eq('requester_agent_id',c.agent.id).eq('status','pending').order('updated_at',{ascending:false}).limit(60);if(q.error)throw q.error;return q.data||[]}
async function managerRemind(c:any,b:any){requireResp(c);const id=text(b.action_id,80),q=await db.from('stip_action_requests').select('*').eq('id',id).eq('requester_agent_id',c.agent.id).maybeSingle();if(q.error)throw q.error;if(!q.data||q.data.status!=='pending')throw Error('ACTION_NON_RELANCABLE');const now=new Date().toISOString(),count=Number(q.data.reminder_count||0)+1,u=await db.from('stip_action_requests').update({reminder_count:count,last_reminded_at:now,updated_at:now}).eq('id',id).select('*').single();if(u.error)throw u.error;await db.from('stip_notifications').insert({agent_id:q.data.target_agent_id,type:'action_reminder',title:'Rappel',body:q.data.title,action_id:id,source_type:q.data.source_type,source_ref:q.data.source_ref});return u.data}
async function managerCancel(c:any,b:any){requireResp(c);const id=text(b.action_id,80),q=await db.from('stip_action_requests').select('*').eq('id',id).eq('requester_agent_id',c.agent.id).maybeSingle();if(q.error)throw q.error;if(!q.data||q.data.status!=='pending')throw Error('ACTION_NON_ANNULABLE');const now=new Date().toISOString();if(q.data.source_type==='evaluation_signature'&&q.data.source_ref){const r=await db.from('stip_evaluation_signature_requests').update({status:'cancelled',cancelled_at:now,updated_at:now}).eq('id',q.data.source_ref).eq('status','pending').select('id').maybeSingle();if(r.error)throw r.error}else{const u=await db.from('stip_action_requests').update({status:'cancelled',cancelled_at:now,updated_at:now}).eq('id',id).eq('status','pending').select('id').maybeSingle();if(u.error)throw u.error}await db.from('stip_notifications').delete().eq('action_id',id);return{ok:true}}

Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors(req).h});try{const c=await ctx(req),b=await req.json().catch(()=>({})),a=text(b.action,80);if(a==='home')return json(req,{agent:c.agent,permissions:c.profile.permissions,actions:await listActions(c),notifications:await notifications(c)});if(a==='list')return json(req,{actions:await listActions(c)});if(a==='get')return json(req,{action:await actionDetail(c,text(b.action_id,80))});if(a==='submit_signature')return json(req,{ok:true,signature:await submitSignature(c,b)});if(a==='notifications')return json(req,{notifications:await notifications(c)});if(a==='dismiss_notification')return json(req,{ok:true,result:await dismissNotification(c,b)});if(a==='accept_agenda')return json(req,{ok:true,item:await acceptAgenda(c,b)});if(a==='decline_agenda')return json(req,{ok:true,result:await declineAgenda(c,b)});if(a==='create')return json(req,{ok:true,action:await createAction(c,b)});if(a==='send_notification')return json(req,{ok:true,notification:await sendNotification(c,b)});if(a==='agenda_direct')return json(req,{ok:true,item:await agendaDirect(c,b)});if(a==='agenda_propose')return json(req,{ok:true,action:await agendaPropose(c,b)});if(a==='manager_agents')return json(req,{agents:await managerAgents(c)});if(a==='manager_agenda_list')return json(req,{items:await managerAgendaList(c)});if(a==='manager_agenda_cancel')return json(req,{ok:true,result:await managerAgendaCancel(c,b)});if(a==='manager_list')return json(req,{actions:await managerList(c)});if(a==='manager_remind')return json(req,{ok:true,action:await managerRemind(c,b)});if(a==='manager_cancel')return json(req,{ok:true,action:await managerCancel(c,b)});return json(req,{error:'ACTION_INVALIDE'},400)}catch(e){const m=errText(e);return json(req,{error:m},/SESSION/.test(m)?401:/ACCES/.test(m)?403:400)}})
