from pathlib import Path
p=Path('places.html')
s=p.read_text()
start=s.index('function publicContactsHtml(g){')
end=s.index('\nfunction appCard',start)
s=s[:start]+r'''function publicContactsHtml(g){const contacts=[];g.publicPhone.forEach(v=>contacts.push(publicContactItemHtml('Téléphone public',v,'phone')));g.publicEmail.forEach(v=>contacts.push(publicContactItemHtml('E-mail public',v,'email')));g.publicUrl.forEach(v=>contacts.push(publicContactItemHtml('Site officiel',v,'url')));return contacts.length?`<p class="contact-scope">Coordonnées destinées aux personnes extérieures au service.</p><div class="public-contact-grid">${contacts.join('')}</div>`:''}'''+s[end:]
start=s.index('function serviceGuideHtml(p){')
end=s.index('\n\nfunction completionRowHtml',start)
s=s[:start]+r'''function serviceGuideHtml(p){const g=serviceGuideData(p),intro=g.purpose.length?valuesHtml(g.purpose):'',arrival=g.arrival.length?valuesHtml(g.arrival):'',inside=g.inside.length?valuesHtml(g.inside):'',landmarks=g.landmarks.length?valuesHtml(g.landmarks):'',access=g.access.length?valuesHtml(g.access):'',contact=publicContactsHtml(g);const cards=[];if(g.routeMarkup)cards.push(appCard('#service-route','Comment y aller','Trajet, étage et repères'));if(g.nearMarkup)cards.push(appCard('#service-near','À proximité','Services et destinations proches'));if(inside||landmarks)cards.push(appCard('#service-inside','Dans le service','Organisation et repères sur place'));if(contact)cards.push(appCard('#service-contact','Contact','Coordonnées publiques'));if(access)cards.push(appCard('#service-access','Accessibilité','Accès et parcours adaptés'));if(arrival)cards.push(appCard('#service-arrival','Reconnaître l’arrivée','Savoir que tu es au bon endroit'));const sections=[];if(g.routeMarkup)sections.push(`<section class="service-app-section" id="service-route"><h2>Comment y aller</h2>${g.routeMarkup}</section>`);if(g.nearMarkup)sections.push(`<section class="service-app-section" id="service-near"><h2>À proximité</h2>${g.nearMarkup}</section>`);if(arrival)sections.push(`<section class="service-app-section" id="service-arrival"><h2>Reconnaître l’arrivée</h2>${arrival}</section>`);if(inside||landmarks)sections.push(`<section class="service-app-section" id="service-inside"><h2>Dans le service</h2>${inside}${landmarks?`<div class="guide-block"><h2>Repères et équipements utiles</h2>${landmarks}</div>`:''}</section>`);if(contact)sections.push(`<section class="service-app-section" id="service-contact"><h2>Contact</h2>${contact}</section>`);if(access)sections.push(`<section class="service-app-section" id="service-access"><h2>Accessibilité</h2>${access}</section>`);return `<section class="service-app">${intro?`<div class="service-app-intro"><h2>Le service</h2>${intro}</div>`:''}${cards.length?`<div class="service-app-grid">${cards.join('')}</div>`:''}${sections.join('')}</section>`}'''+s[end:]
s='\n'.join(line.rstrip() for line in s.splitlines())+'\n'
p.write_text(s)
