create table if not exists public.stip_access_activity (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.stip_access_profiles(id) on delete cascade,
  session_id uuid references public.stip_access_sessions(id) on delete set null,
  page_key text not null check (char_length(page_key) between 1 and 80),
  occurred_at timestamptz not null default now()
);

comment on table public.stip_access_activity is
  'Historique minimal STIP des ouvertures de modules authentifiees. Aucun contenu de fiche, texte saisi ou detail de clic n est enregistre.';

create index if not exists stip_access_activity_profile_time_idx
  on public.stip_access_activity(profile_id, occurred_at desc);
create index if not exists stip_access_activity_time_idx
  on public.stip_access_activity(occurred_at desc);
create index if not exists stip_access_activity_session_idx
  on public.stip_access_activity(session_id);

alter table public.stip_access_activity enable row level security;
revoke all on table public.stip_access_activity from anon, authenticated;
