create table if not exists public.admin_cleanup_settings (
  singleton boolean primary key default true check (singleton),
  config jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

comment on table public.admin_cleanup_settings is
  'Réglages centraux du moteur de tri et de contrôle Admin. Aucune suppression automatique sans décision patron.';

create table if not exists public.admin_cleanup_sources (
  source_key text primary key,
  source_type text not null check (source_type in ('github','supabase_db','supabase_storage','vercel','drive','url')),
  label text not null,
  locator text,
  mode text not null default 'automatic' check (mode in ('automatic','connector_assisted','manual')),
  active boolean not null default true,
  config jsonb not null default '{}'::jsonb,
  last_scan_at timestamptz,
  last_status text,
  last_error text,
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_cleanup_scan_runs (
  id uuid primary key default gen_random_uuid(),
  trigger_kind text not null default 'manual',
  status text not null default 'running' check (status in ('running','completed','completed_with_warnings','failed')),
  scope text[] not null default '{}'::text[],
  summary jsonb not null default '{}'::jsonb,
  error_text text,
  started_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.admin_cleanup_cases (
  id uuid primary key default gen_random_uuid(),
  fingerprint text not null unique,
  evidence_hash text not null,
  source_key text references public.admin_cleanup_sources(source_key) on delete set null,
  category text not null,
  status text not null default 'open'
    check (status in ('open','validated','modify_requested','refused','delete_approved','executing','done','execution_failed','superseded')),
  title text not null,
  question text not null,
  context_text text not null default '',
  facts jsonb not null default '[]'::jsonb,
  metrics jsonb not null default '{}'::jsonb,
  evidence jsonb not null default '[]'::jsonb,
  uncertainties jsonb not null default '[]'::jsonb,
  proposed_action text not null default '',
  proposed_plan jsonb not null default '[]'::jsonb,
  executable_action jsonb,
  evidence_score smallint not null default 0 check (evidence_score between 0 and 100),
  gpt_packet text not null default '',
  gpt_prompts jsonb not null default '[]'::jsonb,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  last_changed_at timestamptz not null default now(),
  decision_kind text check (decision_kind is null or decision_kind in ('validate','modify','refuse','delete')),
  decision_note text,
  decision_at timestamptz,
  decision_by text,
  execution_status text,
  execution_log jsonb not null default '[]'::jsonb,
  result jsonb not null default '{}'::jsonb
);

create index if not exists admin_cleanup_cases_status_idx
  on public.admin_cleanup_cases(status, last_seen_at desc);
create index if not exists admin_cleanup_cases_source_idx
  on public.admin_cleanup_cases(source_key, status);
create index if not exists admin_cleanup_cases_category_idx
  on public.admin_cleanup_cases(category, status);

create table if not exists public.admin_cleanup_case_events (
  id bigint generated by default as identity primary key,
  case_id uuid not null references public.admin_cleanup_cases(id) on delete cascade,
  event_type text not null,
  actor text,
  note text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_cleanup_case_events_case_idx
  on public.admin_cleanup_case_events(case_id, created_at desc);

alter table public.admin_cleanup_settings enable row level security;
alter table public.admin_cleanup_sources enable row level security;
alter table public.admin_cleanup_scan_runs enable row level security;
alter table public.admin_cleanup_cases enable row level security;
alter table public.admin_cleanup_case_events enable row level security;

revoke all on public.admin_cleanup_settings from anon, authenticated;
revoke all on public.admin_cleanup_sources from anon, authenticated;
revoke all on public.admin_cleanup_scan_runs from anon, authenticated;
revoke all on public.admin_cleanup_cases from anon, authenticated;
revoke all on public.admin_cleanup_case_events from anon, authenticated;

insert into public.admin_cleanup_settings(singleton, config)
values (
  true,
  jsonb_build_object(
    'github_large_code_bytes', 100000,
    'github_layer_marker_count', 6,
    'github_important_count', 45,
    'storage_large_bytes', 15728640,
    'storage_unreferenced_days', 30,
    'db_zero_row_unreferenced', true,
    'db_dormant_min_days', 60,
    'vercel_stale_days', 30,
    'drive_large_bytes', 15728640,
    'drive_stale_days', 90,
    'scan_frequency_hours', 6,
    'auto_execute_after_patron_approval', true,
    'never_delete_without_patron_decision', true
  )
)
on conflict (singleton) do nothing;

insert into public.admin_cleanup_sources(source_key, source_type, label, locator, mode, config)
values
  ('supabase:db', 'supabase_db', 'Supabase · Base de données', 'yzsrmuxghlengnkyphxj', 'automatic', '{}'::jsonb),
  ('supabase:storage', 'supabase_storage', 'Supabase · Storage', 'yzsrmuxghlengnkyphxj', 'automatic', '{}'::jsonb),
  ('github:stip', 'github', 'GitHub · STIP', 'esapin69/stip', 'automatic', '{"branch":"main"}'::jsonb),
  ('github:admin-ghe', 'github', 'GitHub · Admin', 'esapin69/admin-ghe', 'automatic', '{"branch":"main"}'::jsonb),
  ('github:esapin', 'github', 'GitHub · eSapin', 'esapin69/esapin', 'automatic', '{"branch":"main"}'::jsonb),
  ('vercel:stip', 'vercel', 'Vercel · STIP', 'prj_lCSJuRSTLCAnQ7TWRu3lyK8A1gH5', 'connector_assisted', '{}'::jsonb),
  ('vercel:admin-ghe', 'vercel', 'Vercel · Admin', 'prj_j8EuzvWbF05L2NrZuRaHHRT9vcEh', 'connector_assisted', '{}'::jsonb),
  ('vercel:admin-ghe-test', 'vercel', 'Vercel · Admin test', 'prj_e51bIFGcKjzaB06lEyapCmXfYEYi', 'connector_assisted', '{}'::jsonb),
  ('vercel:esapin', 'vercel', 'Vercel · eSapin', 'prj_dwk0NC6jpLI9kuufXTRGG8LuyOz1', 'connector_assisted', '{}'::jsonb),
  ('vercel:esapin-sqcq', 'vercel', 'Vercel · eSapin sqcq', 'prj_ZRHPhcPmBkd6t5rj6XpGotNGA8dM', 'connector_assisted', '{}'::jsonb),
  ('vercel:esapin-y5zc', 'vercel', 'Vercel · eSapin y5zc', 'prj_WhDdTgV7eY1qFzmIdu9cj6dJMTmq', 'connector_assisted', '{}'::jsonb),
  ('drive:master', 'drive', 'Drive · Dossier maître', '1HGb7vD5jXWApf7O75YlhiJvKbcvwypqE', 'connector_assisted',
    '{"url":"https://drive.google.com/drive/folders/1HGb7vD5jXWApf7O75YlhiJvKbcvwypqE"}'::jsonb)
on conflict (source_key) do update
set label=excluded.label,
    locator=excluded.locator,
    mode=excluded.mode,
    config=excluded.config,
    updated_at=now();

create or replace function public.admin_cleanup_known_storage_refs()
returns table(source_table text, bucket text, path text)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  r record;
begin
  for r in
    select c.table_name
    from information_schema.columns c
    where c.table_schema='public'
      and c.column_name in ('storage_bucket','storage_path')
    group by c.table_name
    having count(distinct c.column_name)=2
  loop
    return query execute format(
      'select %L::text, storage_bucket::text, storage_path::text
       from public.%I
       where storage_path is not null and btrim(storage_path::text) <> ''''',
      r.table_name,
      r.table_name
    );
  end loop;
end;
$$;

revoke all on function public.admin_cleanup_known_storage_refs() from public, anon, authenticated;

create or replace function public.admin_cleanup_table_inventory()
returns table(
  table_name text,
  estimated_rows bigint,
  total_bytes bigint,
  total_size text
)
language sql
security definer
set search_path = public, pg_temp
as $$
  select
    c.relname::text,
    greatest(c.reltuples::bigint,0),
    pg_total_relation_size(c.oid),
    pg_size_pretty(pg_total_relation_size(c.oid))
  from pg_class c
  join pg_namespace n on n.oid=c.relnamespace
  where n.nspname='public' and c.relkind='r'
  order by pg_total_relation_size(c.oid) desc, c.relname;
$$;

revoke all on function public.admin_cleanup_table_inventory() from public, anon, authenticated;
